### ISSUE TITLE
MATCH_HIDDEN in relations is not working

### ISSUE THREAD

**Issue by jfcere** [udos86/ng-dynamic-forms#1002]
## I'm submitting a

```
[x] Bug / Regression
[ ] Feature Request / Proposal
```

## I'm using

```
NG Dynamic Forms Version: `8.1.1`
Angular Version: `8.2.0`
Angular Material Version: `8.1.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
```

## Description

Using `MATCH_HIDDEN` in `relations` property doesn't work (at least with Material).

What I checked from the issues I've found...
- `HIDDEN_MATCHER` is provided in `AppModule`
- Other matchers work correctly
- Using `HiddenMatcher.match` did not work either

I've created a minimal reproduction example:
https://stackblitz.com/edit/ng-dynamic-forms-issue-1002

Thanks in advance!

**Comment by jfcere** [comment]
I noticed that the `hidden` property doesn't seems to work at all with Material!

Here is a stackblitz example where I set `hidden: true` on both radio and input controls but they are still visible: https://stackblitz.com/edit/ng-dynamic-forms-issue-1002-hidden

**Comment by udos86** [comment]
@jfcere Hi!

There's no bug here. The `hidden` attribute is correctly applied to the corresponding `DynamicMaterialFormControlComponent`.

There's just no default style defined for `[hidden]` in Material Theme.

So just add it yourself:

> [hidden] {
>   display: none;
> }

**Comment by jfcere** [comment]
@udos86 oh well that was my first thought but i was like "no way this is the say to do" ... thanks anyway!

**Comment by udos86** [comment]
@jfcere 

The intention was to embrace web standards: https://www.w3schools.com/tags/att_global_hidden.asp
