### ISSUE TITLE
bootstrap multiple not working on select element

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1003]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ x] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hello, your library is awesome thank you. But i am trying to create a multi select using bootstrap but adding `multiple: true` does not work.

I know you mentioned in #303 that its better to use checkboxes, but was this support ever added for bootstrap? I see it works for Material.

My client doesn't want to use checkboxes because there are many items

**Comment by udos86** [comment]
@drkhannah Hi!

> Hello, your library is awesome thank you.

Thanks for giving it a try.

> but was this support ever added for bootstrap? 

As both ngx-bootstrap and ng-bootstrap do not provide a multi select component no direct support can be provided at the moment. 

However, you could make use of

* ng-bootstrap's user-friendly non-native [checkbox buttons ](https://ng-bootstrap.github.io/#/components/buttons/examples#checkboxreactive)
* a [custom form control ](https://github.com/udos86/ng-dynamic-forms#custom-form-controls)

**Comment by drkhannah** [comment]
is it possible to mix UI modules. 

Example: Most of the controls I use are bootstrap controls, but I want to use Prime-NG's multi select.

is this possible, or would i have to go all in with Prime-NG?

**Comment by udos86** [comment]
> is this possible, or would i have to go all in with Prime-NG?

It is possible to mix multiple forms either by using different dynamic form components or by adding a custom form control.
