### ISSUE TITLE
PrimeNG mutliselect selection limit

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1008]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ x] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x ] Prime NG
</code></pre>

## Description
is it possible to set a selection limit for a PrimeNG multiselect control?

**Comment by CAlex-Wilson** [comment]
@drkhannah I am not familiar with PrimeNG, but would you be able to listen for a valuechange/selectionchange event for this? You could trigger a method that will disable or remove the not-selected options in the multiselect, if the selected array length equals your limit n.

You would just update the form control model appropriately.
