### ISSUE TITLE
Kendo multiselect or how to access @ViewChild of any element

### ISSUE THREAD

**Issue by sehaxx** [udos86/ng-dynamic-forms#1020]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[x] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hello, 
Hope you guys can help me. 
**Kendo Original Example**
I need to filter some data on the Kendo [Multiselect](https://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/filtering/) in the Kendo example they are using:
`@ViewChild("list") list;`

and the later in the ngAfterInit:
`this.list.filterChange.asObservable().pipe(...)`

**Dynamic forms implementation**
How can I achieve that. I saw in DynamicKendoMultiSelectComponent we have:
`@ViewChild("kendoMultiSelect") kendoMultiSelect: MultiSelectComponent;`

and also a getter:
`  get viewChild(): MultiSelectComponent {
      return this.kendoMultiSelect;
  }`

But I can't get it to work in my app. I try it with:
`  ngAfterViewInit() {
    this.multiSelectComponent = this.componentService.getFormControlRef("selectFilter").location.nativeElement;
    this.multiSelectComponent.kendoMultiSelect.filterChange.asObservable().pipe(
    );
  }`

Where Component is:

`multiSelectComponent: DynamicKendoMultiSelectComponent;`

**My current error**
 Cannot read property 'filterChange' of undefined

Hope you can help me with that. 
Also I have asked on stackoverflow: https://stackoverflow.com/questions/57773587/how-to-use-filterchange-on-kendo-theme-in-ng-dynamic-forms

Thanks

**Comment by bobingham** [comment]
This is something which should be referred to the [Kendo](https://www.telerik.com/forums/kendo-angular-ui) forum.
If your multi-select is in a form you can probably get your values through the form getter.

**Comment by sehaxx** [comment]
The Kendo part is working fine. I can't get the component. It is undefinded. The model and FormControl are fine. But how to get the DynamicKendoMultiSelectComponent from  those two. I cant find the correct way. Do you have an example?
```
  model: DynamicFormControlModel[];
  formGroupHolder: FormGroup;
```

**Comment by bobingham** [comment]
Try build a simple reactive form, without _ng-dynamic-forms_, and add the component to the form.  I don't think it's about _ng-dynamic-forms_ but as a result of using a kendo component in a reactive form.  You should be able to get to the value by using
`this.yourFormName.controls['yourControlName'].value`
Then do your filtering and then reset using 
`this.yourFormName.controls['yourControlName'].setValue(...)`

**Comment by sehaxx** [comment]
Not sure why do you push this issue to Kendo. The kendo control is working fine on its own. But I can't find a way to use the @ViewChild, so that I can add filterChange method.

Here is an StackBliz Demo from CleanKendo(Working) and DemoDynamicForms(Partial Working).
By Partial working, i mean it will render and select the correct items. But it will not filter them. As I do not find a way to use filterChange

https://stackblitz.com/edit/angular-b3xeez?embed=1&file=src/app/demo-kendo/demo-kendo.component.ts

**Comment by bobingham** [comment]
@sehaxx, ok you're right.  Good luck.  The demo you have shown does not have the component in a reactive form, maybe that's the problem.  But don't blame _ng-dynamic-forms_, it's simply a dynamic representation of angular's reactive forms.  Try outside the _ng-dynamic-forms_ environment before you post it as a problem here.  As I said, you have a problem with a kendo component, maybe you should buy a licence and find out what the problem is from kendo before you cry that your unlicensed product doesn't work the way you think it should.
This is my last post on this issue, please try outside of the _ng-dynamic-forms_ environment and then talk to kendo.

**Comment by sehaxx** [comment]
Finally I had time to get back to this issue. After checking the source code and debug a little bit i found how it should be used to get the ViewChild from any component you need.

Maybe the solution will help others:

```
@Component({
  selector: 'app-kendo-v8',
  templateUrl: './kendo-v8.component.html',
  styleUrls: ['./kendo-v8.component.scss']
})
export class KendoV8Component implements AfterViewInit {
	modelBox: DynamicFormControlModel[];
	formGroupHolder: FormGroup;
	multiselectCustomControl: ComponentRef<DynamicTemplateableFormControl>;
	
	constructor(private formService: DynamicFormService,
              private cpvService: CpvService,
              private componentService: DynamicFormComponentService,
              private cd: ChangeDetectorRef) {
    this.modelBox = this.formService.fromJSON(JSON.stringify(FORMMODEL));
    this.formGroupHolder = this.formService.createFormGroup(this.modelBox);
  }
  
  ngAfterViewInit() {
    //basic multiselect
    this.multiselectCustomControl = this.componentService.getFormControlRef("selectFilter") as ComponentRef<DynamicTemplateableFormControl>;
	this.templateMultiControl = this.multiselectCustomControl.instance;
    this.templateMultiControl.viewChild.filterChange.asObservable().pipe(
      debounceTime(400),
      startWith(''),
      distinctUntilChanged(),
      switchMap(term => from(this.cpvService.GetAll(term + '')
      ).pipe(
        )))
      .subscribe(data => {
        this.multiselectModel.options = data;
      });
  }
}
```

So it was up to this line:
this.multiselectCustomControl = this.componentService.getFormControlRef("selectFilter") as ComponentRef<DynamicTemplateableFormControl>;

I was using componentService.getFormControlRef before but with the wrong FormControl. The TemplateableFormControl has viewChild which then works with the multiselect filter.

Cheers
