### ISSUE TITLE
DynamicDatePicker switches date values

### ISSUE THREAD

**Issue by carstenbaumhoegger** [udos86/ng-dynamic-forms#1024]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `9.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I've implemented the `DynamicDatePicker` into our application and at first everything seemed to work fine.

A problem occurs, if I try to edit date values manually, e.g. changing `10.09.2019` to `11.09.2019`. When the picker is left the value switches to `09.11.2019`.
If I pick the date inside the picker and don't enter it manually, everything works as expected.

I've attached a video to show the current behavior.
https://youtu.be/pQNh4iLOLPE

Here's the picker implementation code:
```ts
      new DynamicDatePickerModel({
        id: 'article-purchase-date',
        label: 'Kaufdatum',
        placeholder: 'Kaufdatum',
        additional: {
          field: 'purchaseDate'
        }
      }, {
        element: {
          host: 'col-sm-12 col-md-6 col-lg-4',
          errors: 'mat-input-error mat-select-error'
        }
      })
```

**Comment by mischkl** [comment]
Same problem here. I managed to work around it by using [@angular/material-moment-adapter](https://www.npmjs.com/package/@angular/material-moment-adapter) as follows:

```ts
import { DateAdapter, MAT_DATE_FORMATS, MatDateFormats } from '@angular/material/core';
import { MomentDateAdapter } from '@angular/material-moment-adapter';

const DATESTRING_DATE_FORMATS: MatDateFormats = {
  parse: {
    dateInput: 'D.MM.YYYY'
  },
  display: {
    dateInput: 'DD.MM.YYYY',
    monthYearLabel: 'MMMM Y',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM Y'
  }
};

@NgModule({
  ...
  providers: [
    ...
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE] },
    { provide: MAT_DATE_FORMATS, useValue: DATESTRING_DATE_FORMATS }
  ]
})

export class AppModule {
```

But yeah, this is a pretty nasty bug.

**Comment by carstenbaumhoegger** [comment]
@mischkl thank you for the workaround!

I've tried to implement it into our application but unfortunately it doesn't work there.

**Comment by udos86** [comment]
I'm trying to fix this

**Comment by udos86** [comment]
@carstenbaumhoegger @mischkl 

Alright, after some short investigation I can confirm this is not a bug, it's a default behavior of Angular Material.

Here, I forked an official StackBlitz sample from the Material Docs and just added the `MAT_DATE_LOCALE`: https://stackblitz.com/edit/angular-bhvf9s?file=src%2Fapp%2Fmaterial-module.ts

**Comment by udos86** [comment]
This is the critical paragraph in the docs:

> Please note: MatNativeDateModule is based off of the functionality available in JavaScript's native Date object, and is thus not suitable for many locales. One of the biggest shortcomings of the native Date object is the inability to set the parse format. We highly recommend using the MomentDateAdapter or a custom DateAdapter that works with the formatting/parsing library of your choice.

https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Comment by carstenbaumhoegger** [comment]
@udos86 thanks for looking into this!
I have now gotten the fix from @mischkl to work :+1:
