### ISSUE TITLE
value updates doesn't exist on DynamicSelectModel

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1025]
## I'm submitting a

<pre><code>
[ x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `9.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ x] Prime NG
</code></pre>

## Description
in the sample project I can use this code just fine

`const multiSelectControl = this.formService
              .findById($event.model.id, this.formModel) as DynamicSelectModel<string>;
          const value = multiSelectControl._value.slice(0, 2);
          multiSelectControl.valueUpdates.next(value);`

but when I use this code in another project where i used npm to install this lib it says

`property _value is private and only accesible inside of DynamicSelectModel<T>`

and 

`Property valueUpdates does not exist on type DynamicSelectModel<string>`

why does this code work in the sample project and not when you install this lib in a project of your own

I have noticed that in the sample project DynamicSelectModel its select() method looks like this

`select(...indices: number[]): void {

        let value = this.multiple ? indices.map(index => this.get(index).value) : this.get(indices[0]).value;

        this.valueUpdates.next(value);
    }`

but in my project where i installed this lib via npm the DynamicSelectModel select() method looks like this.

`select(...indices: number[]): void;`

any idea why this is?

**Comment by drkhannah** [comment]
looks like the sample project uses version 8.1.0, should I switch to that?

**Comment by davnat** [comment]
Trying to understand how to set the values for my forms I just found that:

- the documentation doesn't help (also, most of the links to the sample projects are broken)
- searching in the issues the only suggestion is "you should use `valueUpdates.next(value)`"
- `$ grep -rn valueUpdates node_modules/@ng-dynamic-forms/` doesn't produce any result

As a last resort I checked in the changelog for clues, and finally found it:

> # 9.0.0
> 
> ### **Breaking Changes**
> 
> Updating `value` and `disabled` properties of any `DynamicFormControlModel` is now possible via simple setters:
>
>**BEFORE:**
>```ts
> myModel.valueUpdates.next("New Value");
> myModel.disabledUpdates.next(true);
> ```
>
> **AFTER:**
> ```ts
> myModel.value = "New Value";
> myModel.disabled = true;
> ```
>
> Therefore both `valueUpdates` and `disabledUpdates` `Subject`s have been removed from `DynamicFormControlModel`.
>
> You can still track changes via newly introduced `valueChanges` and `disabledChanges` `Observable`s.

Hope it helps.

**Comment by udos86** [comment]
@drkhannah 

As @davnat pointed out `valueUpdates` has been dismissed in favor of `value` setter.

@davnat 

Your error output is correct. `value` is a property of `DynamicFormValueControlModel<T>` which inherits from `DynamicFormControlModel`.

**Comment by drkhannah** [comment]
awesome thank you so much
