### ISSUE TITLE
Clearing a form value when it is hidden by a relation

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1032]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `8.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ x] Prime NG
</code></pre>

## Description
I have controls that are hidden by relations defined in json

I notice that if i enter data into a input, then make it hidden, the value i entered is still in the form value object

 is it possible to clear values out of controls that are hidden?

**Comment by udos86** [comment]
> is it possible to clear values out of controls that are hidden?

No as long as the input is not disabled as well.

**Comment by drkhannah** [comment]
so disabling it will set it back to its default value?
