### ISSUE TITLE
don't submit values of HIDDEN controls to server 

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1033]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `8.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I have been working with the HIDDEN relation, but i have noticed that values for hidden controls are still in the formGroup.value object

I don't want to pass values to my server for controls that have been hidden on the UI

what is the best way to handle this?

**Comment by udos86** [comment]
> what is the best way to handle this?

You need to disable the field at the same time as only disabled form controls are removed from the value object.

**Comment by drkhannah** [comment]
awesome, so since my form is built form json i can just add the DisabledMatcher to all my HiddenMatchers.

Ill try it out thank you so much

**Comment by drkhannah** [comment]
is this the best way to have multiple matchers? 

`{
        id: "myTextArea",
        label: "My Textarea",
        relations: [
            {
                match: "HIDDEN",
                when: [
                    { id: "mySelect", value: "option-3" }
                ]
            },
           {
                match: "DISABLED",
                when: [
                    { id: "mySelect", value: "option-3" }
                ]
            }
        ]
    }`

**Comment by drkhannah** [comment]
using the DisabledMatcher and HiddenMatcher together worked thank you
