### ISSUE TITLE
Text-Mask Incorrect work

### ISSUE THREAD

**Issue by sergeivalko** [udos86/ng-dynamic-forms#1056]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I have a problem.
When i use mask and enter value on view this value valid on formModel invalid.
VIEW:
![image](https://user-images.githubusercontent.com/21295107/72843879-77ca2780-3cac-11ea-9729-a9e8d005b530.png)

and on FOMRGROUP:
![image](https://user-images.githubusercontent.com/21295107/72843818-6254fd80-3cac-11ea-8ce2-c5d99d096500.png)
FORMMODEL:
![image](https://user-images.githubusercontent.com/21295107/72843853-6e40bf80-3cac-11ea-8870-97765b9746c3.png)

[app.model](https://gist.github.com/sergeivalko/4c84b2cbac51c1cbb9faf1a3fbb0f71c)

**Comment by sehaxx** [comment]
can you share your app.component.ts I use the same mask without problems this "s" at the end is strange. And which UI do you use?

**Comment by sergeivalko** [comment]
> can you share your app.component.ts I use the same mask without problems this "s" at the end is strange. And which UI do you use?
Material UI
[app.component.ts](https://gist.github.com/sergeivalko/fa680bb2602a6210347934ac5270e5e0)
[app.component.html] (https://gist.github.com/sergeivalko/4783d77f735b87d0caaeef3152c81af4)

**Comment by sergeivalko** [comment]
> can you share your app.component.ts I use the same mask without problems this "s" at the end is strange. And which UI do you use?

i prepare simple example for u)

[example](https://github.com/sergeivalko/exampleBrokenTextMask)

**Comment by sehaxx** [comment]
Hi,

Thanks for the example, helped to check the issue.

Ok I see your error. I used it on Bootstrap and did not have any issues. It seems there is an issue with some libraries like Material design and ION which is disscussed here:
ION - https://github.com/text-mask/text-mask/issues/294
MAT- https://github.com/angular/angular/issues/16755

https://stackoverflow.com/questions/50777859/is-there-any-way-to-mask-material-input-control

As it seems you will need to find a workaround with Material and text-mask.
