### ISSUE TITLE
Circular Dependency issue

### ISSUE THREAD

**Issue by stekontar** [udos86/ng-dynamic-forms#1058]
## I'm submitting a

<pre><code>
[X ] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `10.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I just download the hole project (version 10.1.0)
1. running `npm i`

2. running `npm run build:core`
everything went as expected, perferct

3. third step, running `npm run build:ui-material`

Circular dependency: dist/ng-dynamic-forms/ui-material/esm2015/lib/form-array/dynamic-material-form-array.component.js -> dist/ng-dynamic-forms/ui-material/esm2015/lib/dynamic-material-form-control-container.component.js -> dist/ng-dynamic-forms/ui-material/esm2015/lib/form-array/dynamic-material-form-array.component.js

WARNING: 
Circular dependency: dist/ng-dynamic-forms/ui-material/esm2015/lib/dynamic-material-form-control-container.component.js -> dist/ng-dynamic-forms/ui-material/esm2015/lib/form-group/dynamic-material-form-group.component.js -> dist/ng-dynamic-forms/ui-material/esm2015/lib/dynamic-material-form-control-container.component.js 

any suggestions?
Regards,
S.

**Comment by danielreiser** [comment]
Same for the basic ui etc.

**Comment by begandroide** [comment]
hi @danielreiser how you solve this issue? 

Regards!!

**Comment by sergeivalko** [comment]
@udos86 
Is there any kind of information on fixing dependencies?

**Comment by udos86** [comment]
closed as of #1140
