### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by pabloxn** [udos86/ng-dynamic-forms#1059]
Warning for installation in Angular 9 environment.

## I'm using
<pre><code>
NG Dynamic Forms Version: `10.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ x] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Warning for installation in Angular 9 environment.

**Comment by krzcho** [comment]
I have pushed my changes for current Angular 9 env to https://github.com/krzcho/ng-dynamic-forms/tree/development
I will be testing material and primeng interfaces soon
I can share dist folder for anyone willing to test it?

**Comment by rernens** [comment]
@krzcho 
we have a project which is dependent on ng-dynamic-forms with material and we are waiting for this update.
Happy to help in testing it

**Comment by krzcho** [comment]
https://drive.google.com/drive/folders/17mdZb8isB40KR4Kgf3LG3MD3wtBs90Ba?usp=sharing
I was reading about github packages and I could potentially submit it there but I think it will be simpler to just share them here
it is marked as 11.0 but of course author may put other version to it at the end
primeng seems to work for me; material as well however here I got some display issues but it may be just a wrong CSS on my side

**Comment by udos86** [comment]
closed as of `11.0.1`
