### ISSUE TITLE
Error on DynamicFormService.detectChanges()

### ISSUE THREAD

**Issue by mischkl** [udos86/ng-dynamic-forms#1060]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `10.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

The following error occurs in some cases when calling `DynamicFormService.detectChanges()` on a form component:
```
TypeError: Cannot read property 'instance' of undefined
	    at DynamicMaterialFormControlContainerComponent.markForCheck 
	    at QueryList.forEach 
	    at DynamicMaterialFormComponent.markForCheck 
	    at DynamicFormService.detectChanges 
````

**Comment by mischkl** [comment]
Fix submitted: #1061

**Comment by mischkl** [comment]
@udos86 It would be great if you could merge this simple change, as it is causing us to use lots of try/catch all over the place at the moment.

**Comment by mischkl** [comment]
New version, and this bug still isn't fixed despite a pull request already being submitted? What gives? @udos86

**Comment by udos86** [comment]
@mischkl 

Maintaining a huge open source project over multiple years is just a lousy business when working a full-time job, teaching at university, having a family while living in effing corona times.

`11.0.3` should fix it

**Comment by mischkl** [comment]
@udos86 thanks for the fix, didn't mean to be harsh, was just frustrated since I kept running into the same issue repeatedly. :wink:
