### ISSUE TITLE
Including default DynamicFormControlMatcher as Provider Fails

### ISSUE THREAD

**Issue by zeeshanalisyed** [udos86/ng-dynamic-forms#1076]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `11.0.1`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I am trying to use relations in dynamic form and generating forms from json model, now when I try to include this 
```javascript
providers: [
    HIDDEN_MATCHER,
    DISABLED_MATCHER,
    REQUIRED_MATCHER
 ]
```
in my app module file it gives me an error that providers are invalid.
I also see this message given below
```
Error: "Invalid provider for the NgModule 'AlertModule' - only instances of Provider and Type are allowed, got: [?[object Object]?, ..., ...]"
```

**Comment by zeeshanalisyed** [comment]
Never Mind found the solution, new to angula so.

**Comment by drkhannah** [comment]
what was the solution?
