### ISSUE TITLE
Library broken with Angular v10

### ISSUE THREAD

**Issue by gkalpak** [udos86/ng-dynamic-forms#1085]
You seem to be relying on the private `looseIdentical()` helper in [dynamic-select.model.ts][1] and [dynamic-select.model.spec.ts][2]. This private helper (which is not supposed to be used by external modules) has been removed in angular/angular#37191. Therefore, building an app that uses this library with Angular v10 fails.

The fix is to replace `looseIdentical()` with your own helper (it's just one line of code) or use `Object.is()` (as Angular did).

##
(For reference, we ran into this on our [ngcc-validation][3] repo. Here is an example of a failing CI job: https://circleci.com/gh/angular/ngcc-validation/8853#tests/containers/2)

[1]: https://github.com/udos86/ng-dynamic-forms/blob/b5fd26de93bd69188e19d0f2201d600cfc4c9c65/projects/ng-dynamic-forms/core/src/lib/model/select/dynamic-select.model.ts#L1
[2]: https://github.com/udos86/ng-dynamic-forms/blob/b5fd26de93bd69188e19d0f2201d600cfc4c9c65/projects/ng-dynamic-forms/core/src/lib/model/select/dynamic-select.model.spec.ts#L4
[3]: https://github.com/angular/ngcc-validation

**Comment by udos86** [comment]
@gkalpak 

Thank you for reporting this. I'll patch this with the next version.

**Comment by drkhannah** [comment]
im experiencing this issue as well, do you know when this lib will support angular v10?

**Comment by drkhannah** [comment]
@gkalpak  how would you actually use Object.is() in this line?

```        this.compareWithFn = isFunction(config.compareWithFn) ? config.compareWithFn : looseIdentical; ```

**Comment by gkalpak** [comment]
How about `this.compareWithFn = isFunction(config.compareWithFn) ? config.compareWithFn : Object.is;`?

**Comment by drkhannah** [comment]
awesome thats what i was assuming thanks for verifying

**Comment by drkhannah** [comment]
@udos86 is there an ETA for upgrading this lib to work with Angular 10? its keeping me from upgrading my project

**Comment by SoulOnFire** [comment]
> @udos86 is there an ETA for upgrading this lib to work with Angular 10? its keeping me from upgrading my project

@udos86  I'm in the same situation!!! Any news on this?

**Comment by phgachoud** [comment]
Replacing into core.js `looseIdentical` by `Object.is` as @gkalpak mentioned it solved my migration to 10, but still it should be included into current version

**Comment by mischkl** [comment]
Sorry but I am really wondering... if this is high priority for a one-line code change, what is taking over a month? According to the tests of the Angular team itself this is the only thing preventing this library from being compatible with Angular 10.

**Comment by udos86** [comment]
New version will be released today

**Comment by hemachandran85** [comment]
I have followed below steps to run the samples.. but still I am facing above reported issue. Is there any solution ? I have downloaded the master branch 

http://ng2-dynamic-forms.udos86.de/docs/index.html
