### ISSUE TITLE
Add support for Angular 11

### ISSUE THREAD

**Issue by martine777** [udos86/ng-dynamic-forms#1116]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ x] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `12.0.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
rt,thx

**Comment by udos86** [comment]
closed as of #1118
