### ISSUE TITLE
Hi Udo!

### ISSUE THREAD

**Issue by matheo** [udos86/ng-dynamic-forms#1124]
We've started a brand-new approach to build Dynamic Forms and support many types of controls:
https://dev.to/myndpm/a-new-approach-to-have-dynamic-forms-in-angular-5d11

I'd like to know from your experience with this library,
what could be improved in the configuration to be more generic and maintain it better.

Thanks for this great stuff!

**Comment by matheo** [comment]
(I spammed a little bit to some experienced users, pardon me please)

**Comment by udos86** [comment]
@matheo 

Always good to see someone trying to push the boundaries. 

My project here is far from perfect. The main limitation comes from Angular's core itself: the separation of component code and template makes styling and providing custom form control logic / markup from the outside much harder. 

Frameworks that do rely on "UI as Code" like React or Flutter do have a native advantage when it comes to dynamic forms.

Keep up the good work! I wish you all the best and good luck for your project!
