### ISSUE TITLE
Will be Dynamic Form compatible with Angular 12.x? 

### ISSUE THREAD

**Issue by andrea-rossi** [udos86/ng-dynamic-forms#1141]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ x] Feature Request / Proposal
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `12.0.0`

[ ] Basic UI
[ x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

When I try to update I get:
  **Package "@ng-dynamic-forms/core" has an incompatible peer dependency to "@angular/common" (requires "^10.0.0" (extended), would install "12.1.1").
                  Package "@ng-dynamic-forms/core" has an incompatible peer dependency to "@angular/core" (requires "^10.0.0" (extended), would install "12.1.1").
                  Package "@ng-dynamic-forms/core" has an incompatible peer dependency to "@angular/forms" (requires "^10.0.0" (extended), would install "12.1.1").**

I'd like to know if will be released updates to make this wonderful library compatible with newer version of Angular.

Thanks in Advance

**Comment by udos86** [comment]
Hi! 

Please upgrade to latest `14.0.1` to be fully compatible with Angular 12
