### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by GreenAirplane** [udos86/ng-dynamic-forms#1152]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ X] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `14.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

The current version supports Angular 12. It would be really helpful to update it with the support of Angular 13. I'm not sure if you are already working on it or not..

Let me know if you would like me to submit a pull request.

**Comment by udos86** [comment]
Update to Angular 13 will be releases this week
