### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by Diaaz** [udos86/ng-dynamic-forms#1164]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

ng-dynamic-forms is incompatible with Angular 15 / Material 15. After installing with --force, I get this error with ng serve: ./node_modules/@ng-dynamic-forms/ui-material/fesm2020/ui-material.mjs:778:36-52 - Error: export 'MatChipList' (imported as 'i3$1') 
was not found in '@angular/material/chips'

Are there any plans to support Angular 15?

Kind regards, Jeroen.

**Comment by Diaaz** [comment]
Is anyone else having this problem? We cannot upgrade our codebase to Angular 15 because of this.

**Comment by DrEppen** [comment]
Yes i desperately need this

**Comment by Processfive** [comment]
We have this problem too and cannot upgrade to Angular 15.

**Comment by udos86** [comment]
`16.0.0` has just been released  with support for Angular 15

**Comment by Diaaz** [comment]
Thanks, it works perfectly!
