### ISSUE TITLE
Dynamic forms version 16.0.0 renders Input incorrectly

### ISSUE THREAD

**Issue by Diaaz** [udos86/ng-dynamic-forms#1166]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `16.0.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Input controls are not rendered correctly in Angular Material 15.0.1. An input is rendered, but it is not a Material input and when typing the placeholder is not removed and the entered text is shown on top it.

Typescript: 
 this.testModel = [
      new DynamicInputModel({
        id: "sampleInput",
        label: "Sample Input",
        maxLength: 42,
        placeholder: "Sample input"
      }),
    ];
    this.testFormGroup = this.formService.createFormGroup(this.testModel);
Html: 
```
<form [formGroup]="testFormGroup">
  <dynamic-material-form [group]="testFormGroup" [model]="testModel"></dynamic-material-form>
</form>```

**Comment by Diaaz** [comment]
@udos86 I think the problem is the line: 

import { MatLegacyInput as MatInput } from "@angular/material/legacy-input";

in file ng-dynamic-forms/ui-material/src/lib/input/dynamic-material-input.component.ts.

Material 15 changed many class-names. E.g: mat-input-element to mat-mdc-input-element. It seems MatLegacyInput uses the old class-names, which are not available in the build.

**Comment by DrEppen** [comment]
Really need this too! Is there any progress?

**Comment by danjor** [comment]
I also really need this to be released.

**Comment by udos86** [comment]
Just released `17.0.0` which includes #1168 and a couple of fixes to that.

If there are any bugs left, please open a pull request.

**Comment by Diaaz** [comment]
Thank you!

**Comment by danjor** [comment]
Thank you!
