### ISSUE TITLE
Feature Request: relation between DynamicFormArrayModel initialCount and field value

### ISSUE THREAD

**Issue by GuyShaanan** [udos86/ng-dynamic-forms#149]
Is it possible to create a relation between DynamicFormArrayModel size, when the size is set from another field's value?

i.e. `input type="number"` (or select or radio buttons), and on change to value `x`, the DynamicFormArray will shrink/grow to that size `x`?

And I think my feature/question is broader: can we listen to onChange events of the auto generated components?

Thanks a lot for your hard work!

**Comment by udos86** [comment]
@GuyShaanan Thanks for your contribution! So far it's not possible to set the size of a form array from another field. You would have to do this manually. But that feature would definitely be a nice addition. I'll try to add this in one of the next versions. 

Currently you cannot listen to the native `change` event from the outside. But this will probably be added in the next version. Nevertheless you can obtain subscribe to `valuesChanges` observable of the `control` property of any `DynamicFormControlComponent`

**Comment by Karamuto** [comment]
@udos86 ,

was this feature implemented? If no please reopen this.
