### ISSUE TITLE
Checkbox Model with Toggle Values instead of True/False

### ISSUE THREAD

**Issue by rahul-winner** [udos86/ng-dynamic-forms#297]
Team,

I am seeing that current checkbox model supports value as true/false only. And there is a good requirement of sending value as some string when checkbox is toggled. 
I've implemented such a model on my end and I am thinking it could be a good idea to contribute here. Could you please let me know if this has already being pursued by someone, or should I proceed and submit my code.

Thanks. Rahul

**Comment by udos86** [comment]
@rahul-winner Thanks for that proposal.

What`s your use case for applying string values to checkboxes? 

I'd like to hear some more opinions from the community about this. Is there really a need to allow other values than boolean for checkboxes.

**Comment by renatoaraujoc** [comment]
I support this proposal.

A use case for myself would be a set of states where when the user clicks on it, it sends the abbreviation of the state (string) or the id (number) back to me.

In the end, I guess that it should be generic like: new DynamicCheckboxModel<T> where T is the type value of the checkbox itself.

**Comment by renatoaraujoc** [comment]
I guess that, for some sort of inputs like: select options, checkboxes, radios, a set of generic classed could be created like:

DynamicGenericCheckboxModel<T>
DynamicGenericSelectModel<T>
DynamicGenericRadioModel<T>

This wouldn't break previous implementations.

Just an idea though.

**Comment by rahul-winner** [comment]
@udos86 I have checked-in a working code in forked branch. You may like to take a look once. #315 . Thanks.

**Comment by udos86** [comment]
@rahul-winner First of all, thank you for your contribution.

However, I would not want to introduce some extra model for this feature. 

In order to make this work with current model set a breaking change would have to be introduced:

* add `checked` property to `DynamicCheckControlModel`
* remove current mapping from `value` to `checked`

From what I've seen so far this should be possible but I'm still not completely sure if this would lead to unknown side effects since Angular's `CheckboxControlValueAccessor` delivers boolean values natively.

**Comment by rahul-winner** [comment]
I understand that native behavior of Angular or rather DOM is to return the true/false only as value for a checkbox. 
However, UI developers implemented controls using checkbox with toggle values other than true/false. I've seen implementation by using hidden fields for storing alternate toggle values. 

In such cases, what do you suggest? 

Thanks. Rahul

**Comment by udos86** [comment]
@rahul-winner Before introducing string values for checkboxes I'll have to verify the compatibility of all currently supported UI libraries. I'd only pursue this if all libs create clean and valid markup.
