### ISSUE TITLE
Removing "ng2" prefix from name. Using something like "ngx"

### ISSUE THREAD

**Issue by rahul-winner** [udos86/ng-dynamic-forms#324]
@udos86 

Are we considering removing/renaming "ng2-" prefix from module name? 
I believe Angular team suggesting to use some other names. I've seen many libraries adopted names starting with "ngx-".
Not sure if this has already been answered.

Regards, Rahul

**Comment by udos86** [comment]
@rahul-winner Hi! Thanks for the proposal!

I already considered changing the project and npm scope name after Angular removed it's version number. But then again I think the additional number doesn't really matter at the moment. 

> I believe Angular team suggesting to use some other names.

Maybe you have an official source on this?

All in all I think the "2" should ultimately be removed at some point in the nearer future.

**Comment by rahul-winner** [comment]
@udos86 yes, it does not matter at the moment, however may be a good idea. 
Although I could not find any official documentation for such recommendation, however Igor Minar had tweeted it couple of months back. 
Please check this blog [It’s just Angular](http://angularjs.blogspot.in/2016/12/ok-let-me-explain-its-going-to-be.html)

Also, you may like to read [this ](https://github.com/valor-software/ng2-charts/issues/702) conversation on ngx-charts lib..

**Comment by udos86** [comment]
@rahul-winner Thank you very much for that hint!

**Comment by udos86** [comment]
Done.
