### ISSUE TITLE
Question: how to update the validation property

### ISSUE THREAD

**Issue by sterling9** [udos86/ng-dynamic-forms#342]
I am trying to update the values in validators, but even though the values in formModel is updated, but the validation expression is still the one when it was created. If I have to update the required field outside of validators, it will cause Expression has changed after it was checked error. Is there a way to update validation rule? Thanks

For instance
new DynamicInputModel({
   ...
    required: false,
    validators: {
        required: null,
        minLength: 3,
        testValidator: null
    }
})

if(this.editInputModel.required){
inputControlModel.validators["required"]=null;
}
else{
delete inputControlModel.validators["required"];
}

**Comment by udos86** [comment]
@sterling9 

At the moment there's no possibility to update validators configuration object. I'm trying to deliver that feature in the next patch version.

**Comment by timmyrosen** [comment]
Is there any update on this?

**Comment by udos86** [comment]
@timmyrosen 

No updates so far but I it's still on the radar. I'd just like to wait for Angular 5 cause it unifies the setting of validator functions on form controls, form groups and form arrays.

**Comment by udos86** [comment]
@sterling9 @timmyrosen 

This feature will be available in `5.0.0` via `DynamicFormValidationService`.

**Comment by stevehoper** [comment]
@udos86 
Hi,
Could provide an example how to update and clear validators using dynamicFormValidatorService such like required validation and custom defined function validation?

Thanks
