### ISSUE TITLE
Ionic custom templates

### ISSUE THREAD

**Issue by abraxxas** [udos86/ng-dynamic-forms#360]
Hi, is there any way to achieve input elements like this https://ionicframework.com/docs/components/#floating-labels using this library? I have tried using the custom templates but it seems to me this is currently impossible to do?

Edit: I just checked the code and tried to see what would need to be changed to suppor this. Am i correct in thinking that i would have to change this file? https://github.com/udos86/ng2-dynamic-forms/blob/master/modules/ui-ionic/src/dynamic-form-ionic.component.html If yes i could try to create a pull request for this change but i am not very adept at angular2

**Comment by udos86** [comment]
@abraxxas You're right!

Floating labels are not available in the current template. Of course you can provide a pull request for this. I'll also have a look myself.

**Comment by abraxxas** [comment]
Hi, was thinking of adapting the dynamic-form-control-model to change the union type of label from string | null to string | object | null to allow the label to also be a object so i can define both text and type for it. This seems to be the most logical way to go about this for me.

I had a look at your contribution guidelines and forked the repo but i am kind of stuck now. I cant install the kendo dependencies since i dont have a telerik account and if i simply remove them the tests start to fail. I assume this should be trivial but since i am new to angular this is kind of confusing for me. Also, no matter what i am doing my editors (atom/vscode) always warn me that i have to enable the "experimentalDecorators" option which is clearly enabled in your tsconfig files. Do you have any suggestions for me? :(

**Comment by udos86** [comment]
@abraxxas I'd suggest that you locally just remove the Progress dependencies, the Kendo UI example component and ui-kendo module folder. After that you can implement your proposed code and make a pull request for the changed files. 

> Also, no matter what i am doing my editors (atom/vscode) always warn me that i have to enable the "experimentalDecorators" option which is clearly enabled in your tsconfig files. 

I can remember this being a problem in some early versions of VS Code which then was fixed. I'm working with Webstorm as well as VS Code and do not experience such errors anymore. However I'm not familiar with Atom.

**Comment by iamkarlson** [comment]
check pls PR #518 it solving my issue, maybe it solves your

**Comment by udos86** [comment]
Closed due to incompatibilities of `floating` directive.
