### ISSUE TITLE
filterable DynamicSelectModel needs a (filterChange) output event

### ISSUE THREAD

**Issue by SebLz** [udos86/ng-dynamic-forms#368]
Hello,

In order to be able to use filtering on a DynamicSelectModel with KendoUI, the parent component needs to be able to define how it will handle the filterChange event:
http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/filtering/
I suppose this should be implemented the same way as focus, blur and change (however I was unsuccessful at getting it working so far).

Br,
Sébastien.

**Comment by udos86** [comment]
@SebLz Yep, I was already thinking about this the way you described it. 

I'll give an update as soon as I can provide an implementation!

**Comment by SebLz** [comment]
@udos86 Great, thanks!

**Comment by udos86** [comment]
@SebLz Resolved in `1.4.34`
