### ISSUE TITLE
material form when i enter some data, navigate away, and come back

### ISSUE THREAD

**Issue by bkinsey808** [udos86/ng-dynamic-forms#380]
The placeholder doesn't move out of the way of the data:

![image](https://cloud.githubusercontent.com/assets/475211/26749531/bfcef6e2-47a8-11e7-8414-04cf66ffefb5.png)

As soon as I focus one of the inputs, the placeholders shift to the label position.

Love this project so far. Hope there is a solution for this.

**Comment by bkinsey808** [comment]
one workaround that seems to work:

```
  ngAfterViewInit() {
    const el = this.elementRef.nativeElement.querySelector('[mdInput]');
    el.focus();
  }

```

**Comment by udos86** [comment]
@bkinsey808 

> Love this project so far.

Thank you very much!

> The placeholder doesn't move out of the way of the data:

I'm sorry but I cannot reconstruct that behaviour. You can have a look at the [Material demo](http://ng2-dynamic-forms.udos86.de/example/index.aot.html#/example-material). It's working fine there.

Are you working with the latest version of `@angular/material`? Could you provide a plunker?

**Comment by bkinsey808** [comment]
Do you have a starter ng2-dynamic-forms material plunker by any chance?

**Comment by udos86** [comment]
@bkinsey808 Not a plunker but working [sample code](https://github.com/udos86/ng2-dynamic-forms/tree/master/example/app/material).

**Comment by bkinsey808** [comment]
Hmm. I have to figure out the best way to demo the bug. I got the example working by commenting out the kendo code (is there a better way? Are kendo accounts free?), but there is something different about  demo that does not manifest the bug because it doesn't save the values when you navigate away and come back. I'll dig into this more when I get a chance, and hopefully be able to point you to a demo repo, or figure out what I'm doing wrong.

**Comment by bkinsey808** [comment]
Ok, I can offer my own project which should be able to demo the bug if you are willing to check it out. 

Here's what you have to do:

1. clone this repo https://github.com/bkinsey808/angular-graphql-fullstack-seed
2. cd client
3. `npm i` or `yarn`
4. `ng serve`
5. go to the Register link
6. enter some data in the fields
7. navigate away to a link that works (e.g. Dashboard)
8. come back to the Register link
9. without the "focusFix" directive, the placeholder overlaps the field values

You will note that the bug does not initially manifest because I have the focusFix turned on. But if you remove the directive called "focusFix" then the bug manifests. This is the line of code where I add the "focusFix" directive. Without it, we see the bug:

https://github.com/bkinsey808/angular-graphql-fullstack-seed/blob/master/client/src/app/%2Bregister-module/components/register.component.html#L3

I apologize for how involved this is to set up, but this is all i have at the moment.

**Comment by udos86** [comment]
@bkinsey808 

> I got the example working by commenting out the kendo code (is there a better way? Are kendo accounts free?)

👍 -  Unfortunately there's no better way yet.

> I apologize for how involved this is to set up, but this is all i have at the moment.

No problem. Please give me a couple of days to check your project. Right now I assume that this is a bug in Material.

**Comment by udos86** [comment]
closed due to fixed in Material
