### ISSUE TITLE
Is there any way to use optgroup in select input

### ISSUE THREAD

**Issue by nomi-ramzan** [udos86/ng-dynamic-forms#384]
HI I wanted to ask that is there any way to define groups inside a select 
```
<select>
  <optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select>
```
I am using ui-ng-bootstrap and see [Line](https://github.com/udos86/ng2-dynamic-forms/blob/master/modules/ui-ng-bootstrap/src/dynamic-form-ng-bootstrap.component.html#L177) which is defining only `option` not `optgroup`

**Comment by udos86** [comment]
@nomi-ramzan Hi! Grouping of options is currently not supported.

**Comment by udos86** [comment]
Although Material meanwhile supports optgroups I finally decline due to an disproportionately effort of implementing.
