### ISSUE TITLE
Any possibility of customizing Quil Editor in Primeng UI ?

### ISSUE THREAD

**Issue by krishnapsms** [udos86/ng-dynamic-forms#385]
I want to change editor style in inline mode, where i have to configure this ?

**Comment by udos86** [comment]
@krishnapsms 

Sorry, at the moment this is not possible. But it'll make a nice feature in some future version.

**Comment by udos86** [comment]
@krishnapsms 

Good news! This will be available in `5.2.0` via `custom` config object on `DynamicFormValueControlModel`. Stay tuned.
