### ISSUE TITLE
Multiple calls of methods from html

### ISSUE THREAD

**Issue by garnikmkrtchyan** [udos86/ng-dynamic-forms#412]
Hi!
I noticed a very strange behavior in my code related with Dynamic Forms.

In my HTML file I have a code 
```
<div *ngFor="let controlModel of formModelStep_1" [ngClass]="{'display-none': isFieldInvisible(controlModel.id)}">
                        <dynamic-form-ng-bootstrap-control
                            [group]="formGroupStep_1"
                            [model]="controlModel"
                            [hasErrorMessaging]="controlModel.hasErrorMessages"
                            (change)="onChange($event)">
                        </dynamic-form-ng-bootstrap-control>
                       </div>
```

As you can see for each field I call method `isFieldInvisible(id)`. I thought that this method is called once for each field. Actually, for each field this was called 30 times.

In my .ts file I have a code
```
private num: number = 0;
hideField(id) {
      this.num++;
      console.log(this.num, id);
}
```

And I get this in console after load.
![screenpng](https://user-images.githubusercontent.com/13833124/27389351-28daeb04-56af-11e7-8031-bcac3c70147a.png)

In my model I have 11 fields. I try to understand is this normal behavior, or something is wrong.
Thanks!

**Comment by udos86** [comment]
@garnikmkrtchyan 

I'm not sure if this is related to the library. 

This could be caused by Angular's change detection mechanism itself. 

I'll take a deeper dive when there's some spare time.
