### ISSUE TITLE
how to handle ondropdownclick event in order to trigger server api call to get value of dropdown list options on the fly?

### ISSUE THREAD

**Issue by jaxiell** [udos86/ng-dynamic-forms#485]
I'm trying to start using ng2-dynamic-forms for my angular4 application. I found the dropdown list options are defined in ng2-dynamic-forms model before form being rendered.In primeng, there's ondropdownclick event being invoked when dropdown button is clicked. How do i implement this event while using ng2-dynamic-forms in order to trigger server api call to get value of dropdown list options, rather than from those predefined ones in model.Please help me understand. Thanks.

**Comment by udos86** [comment]
@jaxiell Hi!

> How do i implement this event

At the moment this event is not emitted by `DynamicPrimeNGFormControlComponent`.

However you can also assign an `Observable<DynamicFormOption<T>[]>` to `options` property.

**Comment by jaxiell** [comment]
@udos86 thank you reply. Assign would you please give me example how to do that? Thanks.
do you have plan to implement that? I'm wonderting if I could just add new @Output in DynamicPrimeNGFormControlComponent for onDropdownClick triggering event.

**Comment by udos86** [comment]
@jaxiell I'm planning to support bypassing custom UI widget events in a future release as soon as Prime NG provides a more coherent and mature API.

**Comment by udos86** [comment]
@jaxiell Good news! There'll be support for listening to custom events in one of the next releases.
