### ISSUE TITLE
Cannot change date format of manual input on DynamicDatePickerModel

### ISSUE THREAD

**Issue by cab-peax** [udos86/ng-dynamic-forms#498]
It seems that by default, the date format for the manual input on DynamicDatePickerModel (Manual input meaning that I select the field and then enter a date by keyboard) is "mm.dd.yyyy". I wanted to change that to the european format which is "dd.mm.yyyy", but I couldn't find a way to do it. I tried to set it on the format attribute:

`
new DynamicDatePickerModel({
                id: "dateOfPayment",
                placeholder: this.fieldNameDatumDerAuszahlung,
                min: new Date(new Date().getTime() + 24 * 60 * 60 * 1000), // Tomorrow
                format: "mm.dd.yyyy",
                validators: {
                    required: null
                }
            }
`

but that didn't work. I also tried to set format: null to implement my own date formatting validation, but it still validates with "mm.dd.yyyy".

Strangely enough, if I select the date by using the interactive date selector dialog, then I can choose the date and it will show in the european format and the field validates.

Is this a bug, or otherwise how would I achieve that?
Thanks for your help!

**Comment by udos86** [comment]
@cab-peax Hi!

> Is this a bug, or otherwise how would I achieve that?

Could you please tell me which UI package you're using? I'll have a look at it, then.

**Comment by cab-peax** [comment]
Hi @udos86 . First of all, thank you so much for creating ng2-dynamic-forms . I've been recently using it and find it very handy and efficient to use, and I will definitely be using it for future projects as well. However there are a few glitches which would still need menting to make this perfect. I'm using it with ui-material. The date format pattern on DynamicDatePickerModel was one thing that I couldn't get to work. I wanted to change it to the pattern "mm.dd.yyyy" (european format). Another issue I ran into (also with ui-material) was, that the hint and validation messages on the DynamicSelectModel and the DynamicDatePickerModel get rendered in the wrong dom location.

Thanks a lot for looking into it!
Cheers

**Comment by udos86** [comment]
@cab-peax 

> First of all, thank you so much for creating ng2-dynamic-forms . I've been recently using it and find it very handy and efficient to use, and I will definitely be using it for future projects as well.

Thank you, great to hear!

> The date format pattern on DynamicDatePickerModel was one thing that I couldn't get to work

The date format cannot be directly configured via input binding in Material so far. 

You need to set things like the locale code via value providers: https://material.angular.io/components/datepicker/overview#internationalization

> Another issue I ran into (also with ui-material) was, that the hint and validation messages on the DynamicSelectModel and the DynamicDatePickerModel get rendered in the wrong DOM location.

Material currently supports error messages officially only on `<md-form-field>`.

Please have a look at the [current sample](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form) and the[ component template](https://github.com/udos86/ng2-dynamic-forms/blob/master/packages/ui-material/src/dynamic-material-form-control.component.html). If there are any flaws in your opnion let me know.

**Comment by cab-peax** [comment]
I tried to apply a new date format using:
https://material.angular.io/components/datepicker/overview#internationalization

but it had no effect. Did you manage to change the date format?

**Comment by udos86** [comment]
@cab-peax 

> Did you manage to change the date format?

Yep, it's working fine. Just need to provide `LOCALE_ID`:

```
@NgModule({
  providers: [
    {provide: LOCALE_ID, useValue: 'de-DE'},
  ],
})
export class AppModule {}
```

**Comment by phgachoud** [comment]
For a complete list of locales, I found this source: https://github.com/angular/angular/tree/master/packages/common/locales
