### ISSUE TITLE
Question : Performance

### ISSUE THREAD

**Issue by stekontar** [udos86/ng-dynamic-forms#499]
Hi @udos86 

As I have mentioned in another post, I am trying to build dynamically a HUGE form (about 100 fields).
So far everything goes as expected until a known issue came up.... "Performance"
component dynamic-material-form.component is taking about 2sec in order to render the form.
(timestamp ngInit - ngAfterViewInit)

Do you know how I can handle this situation?
any guide-lines would be appreciated.

P.S
first level techniques has already took place (minimizing, tree-snake, prod, aot)  

Regards,
S

**Comment by udos86** [comment]
@stekontar Hi!

> component dynamic-material-form.component is taking about 2sec in order to render the form.

Wow, that's actually pretty good. I would have expected it to take about 2 hours to render it. 

Seriously, there's lots of heavy stuff going on there. Material itself needs a certain time to initialize as its components are pretty complex.

Lately I tried to to tweak performance by introducing a `trackBy`-Function to `DynamicFormComponent`.

I'm also planning to release an alternate `DynamicFormComponent` that relies on `ChangeDetectionStrategy.OnPush` - but that comes with the limitation of some APIs being disabled then.

I gotta admit that with 100 fields  embedded into a single component I'm finally lacking any good performance advise. You're really on your own now, out there.

**Comment by stekontar** [comment]
Hi there!

I hope  ChangeDetectionStrategy.OnPush make the difference (I just start reading about that) 

Thank you very much for your interest. 
I let you know about my progress (if there is any :P ) 

Regards,
S.

**Comment by udos86** [comment]
@stekontar Closing this for the moment.

I wish you good luck with your further work and I'd appreciate it  if you'd share your experience with heavy form performance here.

**Comment by stekontar** [comment]
Hi @udos86 

I figure out a way to make it faster, I am still testing it but I would like your opinion.
As you already know my forms are huge. All models have the following pattern.

`export const MY_FORM_MODEL: DynamicFormControlModel[] = [

        new DynamicFormGroupModel({
            id: "root-group",
            group: [

                new DynamicFormGroupModel({
                    id: "group-1",
                    group: [
                        new DynamicInputModel({
                            id: "exampleInput",
                            label: "Example Input",
                        })
                    ]
                }),
                new DynamicFormGroupModel({
                    id: "group-2",
                    group: [
                        new DynamicInputModel({
                            id: "exampleInput",
                            label: "Example Input",
                        })
                    ]
                })
                new DynamicFormGroupModel({
                    id: "group-3",
                    group: [
                        new DynamicInputModel({
                            id: "exampleInput",
                            label: "Example Input",
                        })
                    ]
                })
                new DynamicFormGroupModel({
                    id: "group-4",
                    group: [
                        new DynamicInputModel({
                            id: "exampleInput",
                            label: "Example Input",
                        })
                    ]
                })
            ]
        })
]`


* I keep it simple in order to be readable. Imagine that each group contains sub-groups in 3 level depth and arrays


so. 
At first I was following your example, which means that the recursion in html was starting from "root-group".
As the form is extremely big its not useful to show it at once, 
so firstly I am making a loop in order to collect the first level groups (formGroup or formArray),
based on that I create an html list on the side of the screen (like vertical tab) and then on click of each one I generate the html for each section when user request it.
(based on the technique of [dynamic-component-loader](https://angular.io/guide/dynamic-component-loader)).

`<form [formGroup]="formGroup">

  

                <div formGroupName="{{rootModel.id}}">

                  <ng-template #sectionContainer></ng-template>

                </div>

              </form>`



```
`<ul class="root-sections">
  <li *ngFor="let section of sections" [id]="side-+section.id "  (click)="onSelect(section)">
                 {{section.name }}
   </li>
   </ul>`
```





`
onSelect(section: Section): void {

 let currentGroup = this.rootGroup.get(section.id) as FormGroup | FormArray
        let m = this.rootModel.group.filter(item => item.id === section.id);

        let currentModel = (m as DynamicFormGroupModel[]);
        this.createComponent(this.rootGroup, currentModel, this.viewMode);
}
`

I Know that I render over and over the same things when user navigates around and visit again the same sections. 
I am trying to find out how to add dynamically containers (as many as the section are) at ngOnInit 
and read them with @ViewChildren but I am still haven't find out a solution. 

P.S I have a single component and I load the model dynamically, that's why I cannot add the containers manually




Regards,
S.

**Comment by udos86** [comment]
@stekontar Hi, thanks for giving insights to your work!

> As the form is extremely big its not useful to show it at once,
> so firstly I am making a loop in order to collect the first level groups (formGroup or formArray),
> based on that I create an html list on the side of the screen (like vertical tab) and then on click of each one I generate the html for each section when user request it.

Sounds like a good solution to your use case! Way to go!
