### ISSUE TITLE
text-mask-addons not working

### ISSUE THREAD

**Issue by renatoaraujoc** [udos86/ng-dynamic-forms#505]
Hello @udos86,

Been trying to apply the `createTextMask` function provided by [these text-mask addons](https://github.com/text-mask/text-mask/tree/master/addons/#readme) to an input field but its not working. Could you please check for a solution?

Much appreciated,

Renato

**Comment by dakipro** [comment]
Same problem, temporarily solved by adding 
` import` { TextMaskModule } from 'angular2-text-mask'; `
on the beginning of the @ng-dynamic-forms\ui-bootstrap\src\dynamic-bootstrap-form-ui.module.ts file
(and installing the angular2-text-mask module)

**Comment by udos86** [comment]
@renatoaraujoc 

> Been trying to apply the createTextMask function provided by these text-mask addons to an input field but its not working. Could you please check for a solution?

Just checked this and it seems to be working flawless.

Have you properly installed `angular2-text-mask` and `text-mask-addons`?

@dakipro 

> Same problem, temporarily solved by adding
> import { TextMaskModule } from 'angular2-text-mask'; `
> on the beginning of the @ng-dynamic-forms\ui-bootstrap\src\dynamic-bootstrap-form-ui.module.ts file
> (and installing the angular2-text-mask module)

I don't understand - this is already [there](https://github.com/udos86/ng-dynamic-forms/blob/master/packages/ui-bootstrap/src/dynamic-bootstrap-form-ui.module.ts).

**Comment by dakipro** [comment]
Looks like removing and adding packages again fixed the issue. Perhaps something was not properly downloaded or versions were mismatched, not sure. 

I have just removed these lines from packages.json 
    "@ng-dynamic-forms/core": "^1.4.31",
    "@ng-dynamic-forms/ui-bootstrap": "^1.4.31",
did an npm install and folders were deleted from node_modules folder.

Then I added those lines again, and did npm install, and now the mentioned file looks like the one you referred to, it has the missing line. 

Strange, but all seems to be fine now

**Comment by udos86** [comment]
@dakipro Alright, good to know :-)

**Comment by renatoaraujoc** [comment]
I can confirm that updating the library to the latest version fixes the issue (somehow). I'll close this.

**Comment by dakipro** [comment]
and it happened again on a completely new project, looks like not all dependencies (text-mask-addons) are resolved properly when using npm install @ng-dynamic-forms/ui-bootstrap -S
I had to manually "npm i angular2-text-mask --save" for dependency to work.
Can't text-mask be auto inported as a dependency for bootstrap ui module?

**Comment by udos86** [comment]
@dakipro 

> I had to manually "npm i angular2-text-mask --save" for dependency to work.

Yes, of course. It's a peer dependency.
