### ISSUE TITLE
How to use angular2-text-mask with ui-material

### ISSUE THREAD

**Issue by cab-peax** [udos86/ng-dynamic-forms#510]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi, I would like to use angular2-text-mask with ng-dynamic-forms. Is this easily possible and if yes, how should I approach it / is there some small example?

**Comment by udos86** [comment]
@cab-peax Hi!

> Hi, I would like to use angular2-text-mask with ng-dynamic-forms. Is this easily possible and if yes, how should I approach it / is there some small example?

Sorry, at the moment there's no text mask support for Material UI due to rendering issues.

This will be available as soon as `angular2-text-mask` resolves those flaws.

**Comment by ivarorn85** [comment]
@udos86 Hi, 

Could you check if the rendering flaws you mention have been resolved? I just tried using textMask with material input and I could not see any issues. 

  number = createNumberMask({
    thousandsSeparatorSymbol: '.',
    prefix: ''
  });

<mat-form-field>
        <input matInput
               [textMask]="{mask: number, guide: false}"
               placeholder="Favorite number">
</mat-form-field>

I'm thinking about using ng-dynamic-forms in a project that I'm working on and both using material and text masking is a requirement.

Thanks for creating this library 👍

**Comment by udos86** [comment]
@ivarorn85 Hi!

Thanks for giving some update on this!

I'll give it another try...

> Thanks for creating this library

You're welcome - thanks for trying it out!

**Comment by DanielLoop** [comment]
As the author said, this here works as intended:

```
<mat-form-field [textMask]="{mask: mask, showMask:true}">
  <input matInput type="text">
</mat-form-field>
```

I think its very important that the textmask property is placed on the form field element instead of the input.

Also from here: Great work! This library  is easy to use and enjoyable!

**Comment by udos86** [comment]
@Karamuto Thank you very much your feedback!
