### ISSUE TITLE
PrimeNG DatePicker UI events not being handled

### ISSUE THREAD

**Issue by desertdev** [udos86/ng-dynamic-forms#511]
## I'm submitting a...

<pre><code>
[x ] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
Angular 4.4.2
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ x] Prime NG
</code></pre>

## Description

I am using a DynamicDatePickerModel inside of the DynamicFormControlModel list to generate the PrimeNG p-calendar element.

It appears that the event handling for PrimeNG's p-calendar is being bypassed when it is inside a dynamic-primeng-form. If I create a p-calendar manually in the template, outside of the dynamic-primeng-form, everything works correctly.

The apparent bypassing of PrimeNG's event handling is evidenced by 2 main UI issues:

1. When typing a date manually into the input field, once the field loses focus, the value typed in disappears.

2. When using the calendar to select a date, each day in the calendar is an anchor tag with href="#". 
 We would expect an event handler to prevent the default click behavior of the anchor tag, but instead it causes a page load of the base url.

**Comment by udos86** [comment]
@desertdev Hi!

At first I must say that Prime NG still is a bit of a mess and is the least mature UI library supported by NG Dynamic Forms.

> When typing a date manually into the input field, once the field loses focus, the value typed in disappears.

> When using the calendar to select a date, each day in the calendar is an anchor tag with href="#".
> We would expect an event handler to prevent the default click behavior of the anchor tag, but instead it causes a page load of the base url.

Besides `blur`, `focus` and `change` there's currently no support for bypassing any custom widget events. This may likely be included in a future release.

However I cannot verify the bugs you described. 

Did you have a look at the [live demo](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/primeng-sample-form)? 

It properly allows entering or selecting a date via calendar.

**Comment by desertdev** [comment]
Thank you for the reply. The demo looks great.

Could you please tell me what versions of angular, ng-dynamic-forms, and especially primeng are being used in the demo?

I would really like to test my application with similar versions to see if that helps expose where my error is originating from.

**Comment by udos86** [comment]
@desertdev 

I'm always using and supporting all the latest versions.

Angular: `4.4.3`
NG Dynamic Forms: `1.4.31`
PrimeNG: `4.2.1`
