### ISSUE TITLE
Ionic floating input labels by default

### ISSUE THREAD

**Issue by iamkarlson** [udos86/ng-dynamic-forms#517]
## I'm submitting a...

<pre><code>
[ ] Bug
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Use floating input labels by default in ionic component

**Comment by udos86** [comment]
@iamkarlson Hi! Thanks for your feature / pull request!

Would this be the preferred way of displaying the form control label by the majority of Ionic developers?

**Comment by iamkarlson** [comment]
I can't answer for the majority,  but it's just the nicest option in the ionic in my humble opinion. Of course, the best option is to provide custom templates for input labels but I have not managed that yet.

**Comment by udos86** [comment]
@iamkarlson 

> Of course, the best option is to provide custom templates for input labels but I have not managed that yet.

At the moment Angular does not support conditional directives. So there's no straightforward way of supporting multiple label types by configuration. 

But let's do this. I'll add floating labels for Ionic in `1.4.34` .

**Comment by udos86** [comment]
@iamkarlson 

After some final tests I have to to decline this, I'm afraid.

`floating` can lead to unexpected behavior when being used with components different than input (namely ion-toggle).

As I already mentioned as long as this feature is configured via directive there's no way of applying conditionally. There's only either - or.

Sorry and thanks anyway.

**Comment by iamkarlson** [comment]
what do you think if I use ngswitch to use floating for all inputs except ion-toggle and regular one for toggles? Would it be possible to make it in this way?

**Comment by iamkarlson** [comment]
@udos86 please give me your feedback

**Comment by timmyrosen** [comment]
+1 on this. Floating labels is definitely the preferred way in Ionic

**Comment by bobingham** [comment]
+1 on this for me as well.
