### ISSUE TITLE
DynamicFormGroupModel legend not rendered in Material UI

### ISSUE THREAD

**Issue by mesemus** [udos86/ng-dynamic-forms#519]
## I'm submitting a...
<pre><code>
[ ] Bug
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...
<pre><code>
NG Dynamic Forms Version: master

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Please add legend rendering for groups, see the attached pull request.

**Comment by udos86** [comment]
@mesemus Hi! Thanks for your feature / pull request!

Since I deprecated `<fieldset>` due to it's lack of flexbox support I actually would not like to reintroduce `<legend>`.

What about using `label` property instead?

**Comment by mesemus** [comment]
@udos86 Thanks, I have not realized that label would work in this context - 
with a bit of styling the label looks great.

Btw, I'm using your library for automatic generation of dialogues
from Django's rest framework and so far it works perfectly.

Thanks for your good work,

ms.

**Comment by udos86** [comment]
@mesemus 

> Thanks, I have not realized that label would work in this context -
> with a bit of styling the label looks great.

Great to hear that worked out for you!

> Btw, I'm using your library for automatic generation of dialogues
> from Django's rest framework and so far it works perfectly.

Nice, thanks for giving some insight!

> Thanks for your good work

You're welcome, always good to hear!

**Comment by Karamuto** [comment]
Hello,

I would request to reopen this issue, with a suggestion.
It would still be nice to have the legend option inside ui-material.

Maybe we could use a MatCard instead of a <fieldset> as  this seems to be the modern version of a fieldset. Like this a form nesting would also _look_ great in Material.
