### ISSUE TITLE
ionic show errors

### ISSUE THREAD

**Issue by iamkarlson** [udos86/ng-dynamic-forms#524]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Right now ionic templates don't have any elements to show error. How can I add validation errors on the form?

**Comment by udos86** [comment]
@iamkarlson Hi again! Good point!

> Right now ionic templates don't have any elements to show error. How can I add validation errors on the form?

Good point! 

I was always hoping for Ionic to finally bring in some styles or component to support this. As of now this is likely not going to happen soon.

At the moment you would have to implement your own validation message component and like this:

    <ng-container *ngFor="let controlModel of formModel">
    
        <dynamic-bootstrap-form-control [group]="formGroup" 
                                        [model]="controlModel" #componentRef>                                           
        </dynamic-bootstrap-form-control>

        <validation-message [control]="componentRef.control"></validation-message>
        
    </ng-container>

**Comment by iamkarlson** [comment]
yep, I tried to use but it is not shown.

**Comment by iamkarlson** [comment]
Ok, I got it, I used dynamic-form, not control. How can I get access to errorMessages from validation-message component?

**Comment by udos86** [comment]
@iamkarlson 

Please wait till `1.4.34` where I'll reintroduce `<ng-content>`. This will make this more easy.

**Comment by udos86** [comment]
@iamkarlson 

Please install `1.4.34` and try it this way:
```
<dynamic-bootstrap-form-control *ngFor="let controlModel of formModel"
                                [group]="formGroup" 
                                [model]="controlModel" #componentRef>
        
            <validation-message [control]="componentRef.control"></validation-message>
                                    
</dynamic-bootstrap-form-control>
```

**Comment by matthew-valenti** [comment]
Is there additional information available on how to render dynamic validation messages for Ionic? For example, if we have multiple validators and errorMessages defined on a control, how do we dynamically display them in the custom validation component?

We're currently passing both the controlComponent and control objects to the validation component.
```
<ng-container *ngFor="let controlModel of formModel">
    <dynamic-ionic-form-control [group]="formGroup" [model]="controlModel" #componentRef></dynamic-ionic-form-control>
    <dynamic-forms-validation [controlComponent]="componentRef" [control]="componentRef.control"></dynamic-forms-validation>
</ng-container>
```
 
The template can render errors and errorMessages (if hard coded). However, I'm unable to dynamically loop through errors and display the matching errorMessage.
```
<ion-item *ngIf="control && !control.valid && control.touched" class="validation-message">
    {{this.control.errors.required}}
    {{controlComponent.model.errorMessages['required']}}
</ion-item>
```

The form displays successfully and shows this validation message:
true This field is required.

**Comment by udos86** [comment]
@matthew-valenti Hi!

`The template can render errors and errorMessages (if hard coded). However, I'm unable to dynamically loop through errors and display the matching errorMessage.`

Could you please post a code sample for what you're trying to achieve?

**Comment by matthew-valenti** [comment]
Thanks! I was able to display validation successfully with the following custom component approach. What tripped me up initially was an *NgFor on control.errors collection in the template caused something to break. Yet the same approach works just fine in typescript. If there's a better approach than this I'd love to know! 

form html
```
<form>
    <ng-container *ngFor="let controlModel of formModel">
        <dynamic-ionic-form-control [group]="formGroup" [model]="controlModel" #componentRef></dynamic-ionic-form-control>
        <my-form-validation [controlComponent]="componentRef" [control]="componentRef.control"></my-form-validation>
    </ng-container>
</form>
```

validation component html
```
<ion-item *ngIf="control && !control.valid && control.touched" class="validation-message">
    <p>{{controlComponent.model.errorMessages[getValidatorName()]}}</p>
</ion-item>
```

validation component ts
```
import { Component, Input } from '@angular/core';
import { DynamicIonicFormControlComponent } from '@ng-dynamic-forms/ui-ionic';
import { FormControl } from "@angular/forms";

@Component({
    selector: 'my-form-validation',
    templateUrl: 'my-form-validation.html'
})
export class MyFormValidationComponent {

    @Input('controlComponent') controlComponent: DynamicIonicFormControlComponent;
    @Input('control') control: FormControl;

    /**
     * Each control may have one or more validation errors.
     * Do not display all errors for a control. Display the first error only.
     * Loop thru control errors and return name of first validation error.
     * Note that *NgFor on control.errors collection breaks UI.
     */
    private getValidatorName(): string {
        for (let error in this.control.errors) {
            return error;
        }
    }
}

```
