### ISSUE TITLE
 Unexpected value 'TextMaskModule' imported by the module 'DynamicFormsBootstrapUIModule'. Please add a @NgModule annotation

### ISSUE THREAD

**Issue by atarix83** [udos86/ng-dynamic-forms#527]
## I'm submitting a...

<pre><code>
[x ] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hi, after I've been upgraded my project to angular version 4.4.4, I get the following error : 
```
Unexpected value 'TextMaskModule' imported by the module 'DynamicFormsBootstrapUIModule'. Please add a @NgModule annotation
```

Same code worked with Angular version 4.3.1.

Do you have any idea about could cause the issue?

Thanks

**Comment by atarix83** [comment]
If it can be useful this happens only with JIT compilation, while with AOT compilation it works

**Comment by udos86** [comment]
@atarix83 Hi!

Could you please upgrade to `1.4.34` and tell me if this still exists?

**Comment by atarix83** [comment]
Yes I'm using latest version and the problem persists

**Comment by udos86** [comment]
> Yes I'm using latest version and the problem persists

Are you using Angular CLI or are you building on your own? 

Is `angular2-text-mask` properly installed?

Right now I'm not aware of any bugs here and all of my samples running fine.

**Comment by atarix83** [comment]
yes I have installed angular2-text-mask version 8.0.1, and no I'm not using angular CLI.

The odd thing is that this happens only with JIT compilation

**Comment by udos86** [comment]
@atarix83 

> The odd thing is that this happens only with JIT compilation

That's really odd...I can't really help at the moment.

You may check the configs again depending on your bundler:

* [Rollup](https://github.com/udos86/ng-dynamic-forms/blob/master/rollup.config.js)
* [Webpack](https://github.com/udos86/ng-dynamic-forms/blob/master/webpack.config.js)
* [SystemJS](https://github.com/udos86/ng-dynamic-forms/blob/master/sample/systemjs.config.js)

**Comment by atarix83** [comment]
Hi, I found that my real problem is with angular2-text-mask library. In some way my last update has some conflicts with this, but I can't find what is broke. 

I think you can close this issue.

Thanks

**Comment by atarix83** [comment]
@udos86 
I've resolved, it was a webpack configuration.

How ever now I have this error, that luckily doesn't block execution.
```
ERROR { TypeError: this.element.nativeElement.getElementsByTagName is not a function
    at MaskedInputDirective.exports.modules.443.MaskedInputDirective.setupMask (\dist\2.server.js:5994:64)
    at MaskedInputDirective.exports.modules.443.MaskedInputDirective.ngOnChanges (\dist\2.server.js:5953:14
)
    at checkAndUpdateDirectiveInline (\dist\server.js:11156:19)
    at checkAndUpdateNodeInline (\dist\server.js:12667:17)
    at checkAndUpdateNode (\dist\server.js:12606:16)
    at debugCheckAndUpdateNode (\dist\server.js:13470:59)
    at debugCheckDirectivesFn \dist\server.js:13411:13)
    at Object.View_DynamicNGBootstrapFormControlComponent_15._co [as updateDirectives] (ng:///DynamicFormsNGBootstrapUIModule/DynamicNGBootstrapFormControlComponent.ngfactory.js:758:5)
    at Object.debugUpdateDirectives [as updateDirectives] (\dist\server.js:13396:21)
    at checkAndUpdateView (\dist\server.js:12573:14)
```

Have you ever get this error?

**Comment by udos86** [comment]
@atarix83 

> Have you ever get this error?

Nope, sorry, never seen before.

**Comment by Creiger** [comment]
@udos86 Hi. Could you please share the webpack configuration that resolved your initial issue?

**Comment by pradeeprajr93** [comment]
For those who look forward to the webpack config mentioned by @atarix83 
Here you go:
https://github.com/atarix83/dspace-angular/tree/master/webpack
