### ISSUE TITLE
Bootstrap UI - Multiple Inputs on same row

### ISSUE THREAD

**Issue by AdamSWheatley** [udos86/ng-dynamic-forms#528]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[ X ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[X ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I am trying to implement a form where there are two inputs on each row but they seem to just continue to stack on top of each other. 

I am currently trying the following code:

        ,
        {
            element: {
                label: "control-label"
            },
            grid: {
                control: "col-md-4",
                label: "col-md-4"
            }
        }), 

but It doesnt seem to work. Any help would be appreciated.

**Comment by udos86** [comment]
@AdamSWheatley Hi!

You could achieve this by wrapping those inputs using a `DynamicFormGroupModel`.

This is shown in the [ng-bootstrap sample form model](https://github.com/udos86/ng-dynamic-forms/blob/master/sample/app/ui-ng-bootstrap/ng-bootstrap-sample-form.model.ts) (which is similar to Bootstrap).
