### ISSUE TITLE
Add templating for pre and post dynamic input or group

### ISSUE THREAD

**Issue by bdparrish** [udos86/ng-dynamic-forms#531]
## I'm submitting a...

<pre><code>
[ ] Bug
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.33

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Add a new feature to allow you to define a template before and after and dynamic input or group

**Comment by parawanada** [comment]
This
https://github.com/udos86/ng-dynamic-forms#custom-templates
doesn't fulfills your needs?

**Comment by bdparrish** [comment]
That only provides you a template before OR after for each id buy not both.

**Comment by parawanada** [comment]
Got it! Sorry for misunderstanding

**Comment by udos86** [comment]
@bdparrish Hi & Thanks for your contribution.

All in all this could be a nice enhancement.

However I would not like to introduce two new inputs `pre` and `post` to `DynamicTemplateDirective` as you did in your PR as this can be handled via a single property.

**Comment by bdparrish** [comment]
@udos86 you can also utilize what you already do for `START` and `END` with the `align` attribute.  Just really my style to be explicit with the attribute, but with Angular 2 you still need to put `pre="true">` instead of `pre>`.

Would you be more amenable to that?

**Comment by udos86** [comment]
@bdparrish 

I simply would like to avoid code bloat by reusing `align` property as it won't break backwards compatibility here.

We'd just have to introduce another internal template property to `DynamicFormControlComponent`.

**Comment by udos86** [comment]
Featured in `5.0.0`

**Comment by bdparrish** [comment]
For what it’s worth you stole the code merge.  Better would have been to help me through it and merge my code.

**Comment by udos86** [comment]
> For what it’s worth you stole the code merge. Better would have been to help me through it and merge my code.

Calling me a thief for fulfilling a feature request? Yeah, well, that's just, like, your opinion, man.

> Better would have been to help me through it and merge my code.

Better would have been if you had updated your pull request and removed `pre` and `post` inputs as I pointed out right above.

Your code just did not match the goal of making template files less verbose and bloated.

Considering how much of my spare time I do spent guiding people through all kind of issues here... whatever.

**Comment by bdparrish** [comment]
Either you're trolling or not.  Not sure.  The feature request came from the CONTRIBUTING guide that you required to have a feature request before a PR.  The other part is you never asked for an update so you could turn a new version, and your comments made it sound like you didn't really care for the feature anyway.  I could care less about your opinion.  If you care about your spare time, then make a product and charge money.  I wasted my time on a PR that you didn't care enough about either, so it is a two way street.  Why would anyone help someone who is going to take credit for everyone else's work?  Good luck, man.

![image](https://user-images.githubusercontent.com/720788/32303669-685beed2-bf40-11e7-8e7f-4d8fedfbfa3b.png)

**Comment by udos86** [comment]
> your comments made it sound like you didn't really care for the feature anyway

Actually I said that it would make a nice enhancement 

> I wasted my time on a PR

Actually you learned something reading the code.

> Why would anyone help someone who is going to take credit for everyone else's work?

Actually you're the first one complaining.


Now, since I'm not an expert on curing paranoia, I cannot help you any further. Good luck, man.
