### ISSUE TITLE
core.utils.ts wouldn't compile

### ISSUE THREAD

**Issue by bxlu** [udos86/ng-dynamic-forms#536]
## I'm submitting a...

<pre><code>
[X ] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[X ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

core.utils.ts line 31 
static isNonEmptyObject(value: object): boolean {

object should be Object, or it wouldn't compile.   

Thank you.

**Comment by bxlu** [comment]
I pulled version 1.4.31.

**Comment by udos86** [comment]
@bxlu 

You should update your TypeScript. This compiles without a flaw.
