### ISSUE TITLE
Input model with a dot inside id property get errors

### ISSUE THREAD

**Issue by atarix83** [udos86/ng-dynamic-forms#542]
## I'm submitting a...

<pre><code>
[ x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.33

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hi, if I use an input model with dot inside id, I get several errors  : 
`ERROR TypeError: Cannot read property 'valueChanges' of null`
`ERROR TypeError: Cannot read property 'touched' of null`

This is an example of a model that generates these errors : 
```
const MY_DYNAMIC_FORM_MODEL = [

  new DynamicInputModel(
    {
      id: "dc.identifier.issn",
      label: 'Identifiers',
      placeholder: 'Identifiers',
    }
  ),
];
```

Is It not allowed to use dot inside id for any reason?

Thanks

**Comment by udos86** [comment]
@atarix83 

> Is It not allowed to use dot inside id for any reason?

From a pure HTML point of view it's possible but the `id` is also used as the property name for the corresponding `FormControl` in a `FormGroup` object. 

That's probably causing the errors. All in all you better avoid this naming pattern.
