### ISSUE TITLE
Material DateTime picker

### ISSUE THREAD

**Issue by stekontar** [udos86/ng-dynamic-forms#543]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi there,

I am trying to find out a way to add time and datetime field on material forms.
Ideally I would like a single component which based on format would create the correct field
e.g 
format : yyyyDDmm => date picker
yyyyDDmm HH:mm => datetime picker
HH:mm => time picker.

Is there any plugin/something that could be add it in dynamic-from-material component?

any suggestions would be appreciated.

Regards,
S.

**Comment by udos86** [comment]
@stekontar Hi!

> Is there any plugin/something that could be add it in dynamic-from-material component?

Sorry, Material does not have a timepicker component so far and I won't introduce any arbitrary library to fill this gap. 

However you're always free to fork this project to implement your own template file for `DynamicMaterialFormControlComponent`.
