### ISSUE TITLE
Fieldset legend missing on packages other than Bootstrap UI for DynamicFormGroupModel

### ISSUE THREAD

**Issue by scott444** [udos86/ng-dynamic-forms#544]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.33

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[X] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Looking at the live demo, it appears only Boostrap UI supports legend labels on the fieldset.  Is there a reason it's not implemented on the other UI packages? Thanks.

**Comment by udos86** [comment]
@scott444 Hi!

> Is there a reason it's not implemented on the other UI packages?

Yes, there is indeed. 

Unfortunately `<fieldset>` does not support CSS Flexbox which limited the way form groups could be styled.  

That's why I had to remove from almost all template files and probably will erase out totally in a future release.

**Comment by dokithonon** [comment]
Is there a way to wrap a group in a square with a title (like fieldset and legend) I am using the PrimeNG. Thanks.
