### ISSUE TITLE
Required Checkbox not validating

### ISSUE THREAD

**Issue by maxf64** [udos86/ng-dynamic-forms#545]
## I'm submitting a...
[ x ] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...
NG Dynamic Forms Version: 1.4.30

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ x ] Prime NG

## Description
I'm having issues making a checkbox required with the PrimeNG UI
The required value of my control is set to true, and I have also a required validator, but no luck
I also tried adding my own custom validator to it, but it seems to never get called

I've got all those things working fine for input controls,  but the checkbox one doesn't seem to validate at all

Any suggestions ?

**Comment by parawanada** [comment]
Maybe you should try Validators.requiredTrue from default angular 4 validators list. I think this should solve your problem

**Comment by maxf64** [comment]
That worked, thanks a lot :)

**Comment by udos86** [comment]
@parawanada Thanks for helping out!

**Comment by isaacabdel** [comment]
I ran into the same issue but didn't know what `Validators.requiredTrue` was. I eventually found it, leaving it here for the next person.

> The required value of my control is set to true, and I have also a required validator,

The following is basically what maxf64 had
```
new DynamicCheckboxModel({
    id: "checkbox",
    label: "Do you agree?",
    validators: {
      required: null
    },
    required: true,
  }),
```

What parawanada proposed was the following:
```
new DynamicCheckboxModel({
    id: "checkbox",
    label: "Do you agree?",
    validators: {
      requiredTrue: null
    },
    required: true,
  }),
```
