### ISSUE TITLE
Working example with angular2-text-mask and material-ui library

### ISSUE THREAD

**Issue by cab-peax** [udos86/ng-dynamic-forms#546]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[ x ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Is there somewhere the code of a working example of: @ng2-dynamic-forms/ui-material  with the angular2-text-mask feature?

Thanks :)

**Comment by udos86** [comment]
@cab-peax Hi!

> Is there somewhere the code of a working example of: with the angular2-text-mask feature?

No, currently there's no support for text masks in Material UI package.
