### ISSUE TITLE
best approach for multiple forms on single page

### ISSUE THREAD

**Issue by dakipro** [udos86/ng-dynamic-forms#550]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.34
1.4.34

[ ] Basic UI
[x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi,
I am trying to achieve multiple forms (well multiple sections anyway, grouped by master group somehow)
F.eks. order form would have some configuration options, like:
Product 1:
  - color
  - length
  - ...
Product 2:
  - model
  - size
  - ...

All product configurations come from server. I was planning to parse each product and create form fields from it, but I would like to visually have individual header per product / group, thus it could be that several forms are the best approach.
However, total number of forms/products is also dynamic, so I would have to make a array of formGroups and dynamicFormModels, and then update each of them?
Also, not sure how to start about initializing one of the empty forms before data from server comes to the client?
Any thoughts (or even pseudo code perhaps? :) )?

Could a form be customized enough so that it looks like these are separate sections/forms?
This is visually what I am trying to achieve:

![screenshot 2017-10-11 14 16 07](https://user-images.githubusercontent.com/1586291/31440111-0880d732-ae8f-11e7-9ab9-ba23afe9d22e.png)

In quick demo it displays single form multiple times, how to approach multiple forms, or achieve similar layout with single form?
Thanks!

**Comment by parawanada** [comment]
In my opinion you should try to first create empty formModel and empty formGroup initialized with created formModel, and next for each product push proper FormGroup inside with id equals to product name. Then Each formGroup inside will represent each product. 

I think array of formGroups is not designed for this purpose. FormArray - if its that what you mean by array of FormGroups - should be used when you have some number of same formGroups and user can add and remove those formGroups - depends how much these formGroups they need
