### ISSUE TITLE
Custom template for specific input control [primeng]

### ISSUE THREAD

**Issue by marcio199226** [udos86/ng-dynamic-forms#554]
## I'm submitting a...
<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...
Angular: 4.4.4
NG Dynamic Forms Version: 1.4.34

<code><pre>
[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description
Hi i have a question, we have a possibility to add some BEFORE/AFTER content for each control but is there any feature that allow us to replace some specific component template?

I will try to explain it better with an example (my current trouble):

I'm using a datepicker from primeng but here: https://github.com/udos86/ng-dynamic-forms/blob/master/packages/ui-primeng/src/dynamic-primeng-form-control.component.html#L101 as we can notice yearNavigator & monthNavigator are set to false and there is no way to change it.

Can i change/replace only template for datepicker type?
if is possibile please show me an example or tell me how can i achieve it.
Otherwise which is the best way to extend/replace the current behaviour (of component which renders primeng controls) extending it ?

Thanks in advance for any advice ! I hope this may be useful for other devs too

**Comment by udos86** [comment]
@marcio199226 Hi! Thanks for your question!

> is there any feature that allow us to replace some specific component template?

I'm afraid, there's not and probably won't be as this would result in overly complex template files and you having to set all control bindings manually.

> as we can notice yearNavigator & monthNavigator are set to false and there is no way to change it.

I'm always trying to make all the controls more configureable. I'll have a look at this specific feature. 

> Otherwise which is the best way to extend/replace the current behaviour (of component which renders primeng controls) extending it ?

You'd have to implement your own UI template / package.
