### ISSUE TITLE
Upload file Bootstrap UI

### ISSUE THREAD

**Issue by NikeZakrevsky** [udos86/ng-dynamic-forms#555]
## I'm submitting a...
<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...
<pre><code>
NG Dynamic Forms Version: 1.4.34

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I tried to use inputType: 'file' in the DynamicInputModel control, but after uploading the file, value of the control is null. Is it possible to use file uploading in the Bootstrap UI? Also in sample project, file uploading using ng bootstrap doesn't work.

**Comment by udos86** [comment]
@NikeZakrevsky Hi & sorry for the late response!

When using file inputs you need to read file information from `file` property of `DynamicInputModel` as Angular does not provide a `ControlValueAccessor` for file inputs yet.
