### ISSUE TITLE
Cascading Selects

### ISSUE THREAD

**Issue by ticxx** [udos86/ng-dynamic-forms#557]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.33

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hey,
i need cascading selects. For example, first select will ask for the country and second for a city in the country.
I try to do this with a function for the options property of the first select, but I don't know how to determine the value of the first selection in the function. The FormModel is not finished when executing the function and so 
``
let countryModel = this.formService.findById("myCountry", this.formModel) as DynamicInputModel;
``
fails. Is there a possibility, or are the options only set during initialization and I have to change them via an event of the first select?

Thanks and best regards

**Comment by udos86** [comment]
@ticxx Hi!

> The FormModel is not finished when executing

Does it really have to be this way?

> Is there a possibility, or are the options only set during initialization and I have to change them via an event of the first select?

You can update the `options` at any point in time using the corresponding [accessor](http://ng2-dynamic-forms.udos86.de/docs/core/classes/_model_dynamic_option_control_model_.dynamicoptioncontrolmodel.html#options). You can either pass an `Array<DynamicFormOptionConfig<T>>` or a `Observable<Array<DynamicFormOptionConfig<T>>>`.

**Comment by ticxx** [comment]
@udos86 
Thanks for your help. I was able to solve my problem. 
Best regards
ticxx
