### ISSUE TITLE
how to create button using ng-dynamic-form??

### ISSUE THREAD

**Issue by sorb99** [udos86/ng-dynamic-forms#566]
##  submitting a...

<pre><code>
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Material  

## Description

How to create button using this lib?  I want to create it using  a selector so how to do it??

**Comment by udos86** [comment]
@sorb99 Hi!

Please use a [custom template](https://github.com/udos86/ng-dynamic-forms#custom-templates) in order to achieve this.
