### ISSUE TITLE
IE, Edge and Safari bug - Display blank value for select if no option is selected

### ISSUE THREAD

**Issue by iarroyo** [udos86/ng-dynamic-forms#568]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[x] Basic UI
[x] Bootstrap UI  
[x] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

There is a known issue for IE, Edge and Safari when you display a select without a selected option it display the first option instead of a blank value like the rest of browsers.

Reported Issue:
https://github.com/angular/angular/issues/14505#issuecomment-321486088

I have created a fork and fixed the issue for basic UI, bootstrap UI and Foundation UI.
https://github.com/iarroyo/ng-dynamic-forms/tree/display-blank-if-select-has-null-option

This branch was created from tag 1.4.34, i am wondering how i can do a PR against that, because right now master and development are being migrated to version 5.

Thanks.

**Comment by udos86** [comment]
@iarroyo Hi!

Thank you very much for reporting this!

> This branch was created from tag 1.4.34, i am wondering how i can do a PR against that, because right now master and development are being migrated to version 5.

Would you mind to provide your changes to the template files on another branch based on latest `udos86:development` (see [CONTRIBUTING.md](https://github.com/udos86/ng-dynamic-forms/blob/master/CONTRIBUTING.md)) ?

Always glad to welcome another contributer!

**Comment by udos86** [comment]
@iarroyo Are you still interested in providing a PR? I'd appreciate it!

**Comment by udos86** [comment]
closed as this is officially filed as a bug now in the Angular repo.
