### ISSUE TITLE
OnChange event no longer triggered while matevent called with undefined $event after moving to  5.0.0 of Angular , ng-dynamic-forms and ui-material

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#569]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 5.0.0

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

After upgrading to Angular 5.0.0 and @ng-dynamic_forms 5.0.0 with ui-material,  onchange event no longer gets called and matevent gets called with an undefined $event

**Comment by rernens** [comment]
@udos86 

sorry missed the name change of the events moving forward to 5.0.

Closing

**Comment by rernens** [comment]
@udos86 

After changing the name tof the standard event change to dfChange, the change event works perfectly.

Nevertheles, the matEvent gets called with an undefined $event object.

**Comment by udos86** [comment]
@rernens Hi!

> Forgot to say that I also upgraded Angular Material to 5.0.0-rc0

Thanks for that information.

I gave 5.0.0-rc0 a first try yesterday. 

I'll check this and will provide a patch version as soon as possible!

**Comment by udos86** [comment]
@rernens 

After some tests it seems that there are no breaking changes to cause Material 5.0.0-rc5 to fail with this library.

> Nevertheless, the matEvent gets called with an undefined $event object.

It's simply because Material does not pass any `$event` when certain events like `closed` or `opened`.  

This is perfectly fine and nothing to worry about!

Thanks anyway.
