### ISSUE TITLE
Date Picker not working properly for ng-bootstrap

### ISSUE THREAD

**Issue by Asraf-Uddin-Ahmed** [udos86/ng-dynamic-forms#570]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.34

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

At first I have downloaded the project and run it by following [this instruction](https://github.com/udos86/ng-dynamic-forms#running-the-sample). Then I made some changes:

**material-sample-form.model.ts**
<pre><code>
new DynamicDatePickerModel(
	{
		id: "arrivalDate",
		inline: false,
		value: new Date(), // newly added line
		placeholder: "Date of Arrival"
	}
)
</code></pre>

**ng-bootstrap-sample-form.model.ts**
<pre><code>
new DynamicDatePickerModel(
	{
		id: "arrivalDate",
		inline: false,
		label: "Arrival",
		value: new Date(), // newly added line
		placeholder: "Date of Arrival",
		toggleIcon: "./assets/calendar-icon.svg"
	},
	{
		element: {
			container: "p-0",
			label: "col-form-label"
		},
		grid: {
			host: "col-sm-4"
		}
	}
)
</code></pre>
The code is working perfectly for **material** but not for **ng-bootstrap**.

**focusedDate** and **format** are also not working for **ng-bootstrap**.

**Comment by eduDorus** [comment]
I have the same problem

**Comment by udos86** [comment]
@Asraf-Uddin-Ahmed @eduDorus Hi!

Thank you very much for reporting this!

Support for `focusedDate` will be provided in the next patch version.

However `format` is currently not supported by NG Bootstrap
