### ISSUE TITLE
Update Material UI to 5.0.0-rc0

### ISSUE THREAD

**Issue by eduDorus** [udos86/ng-dynamic-forms#574]
## I'm submitting a...

<pre><code>
[ ] Bug
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Material UI depends on 2.0.0-beta.12. There is a new release since yesterday which is the first RC of material angular. The Version is 5.0.0-rc0 and should be the first stable material build.

**Comment by eduDorus** [comment]
I saw it's in the 5.0.1-RC so i will close this issue :) thanks!

**Comment by udos86** [comment]
@eduDorus Alright, thanks!
