### ISSUE TITLE
ui-material 5.0.0 has still dependencies on @angular material 2.0.0 beta 12 while ng-dynamic-forms not

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#575]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 5.0.0 

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  5.0.0
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

while ng dynamic forms 5.0.0 dependencies have been updated to @angular/material 5.0.0 rc0, ui-material still has depencies on @angular/material 2.0.0 beta 12
should be updated for consitency

**Comment by udos86** [comment]
@rernens Hi!

This is not a bug. 

`5.0.0` was released before latest Material. 

That's why I published `5.0.1` a couple of minutes ago...
