### ISSUE TITLE
Add minDate (min) option in ng-bootstrap datepicker

### ISSUE THREAD

**Issue by cab-peax** [udos86/ng-dynamic-forms#576]
## I'm submitting a...

<pre><code>
[ ] Bug
[ x ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I would like to use the nbbDatepicker to enter the birth date but, currently the dialog defaults to years of 10 years before and 10 years after now (e.g. 2007 - 2027), which doesn't go far enough for birth date (e.g. I would need 1900 - 2017).

Could you please add the input:
[minDate]="model.min"
and
[maxDate]="model.max"

...into the file dynamic-ng-bootstrap-form-control.component.html of the
**ng-dynamic-forms/ui-ng-bootstrap**
project?

`<div *ngSwitchCase="5" class="input-group">

                <input ngbDatepicker class="form-control" #datepicker="ngbDatepicker"
                       [class.is-invalid]="showErrorMessages"
                       [dynamicId]="bindId && model.id"
                       [formControlName]="model.id"
                       [name]="model.name"
                       **[minDate]="model.min"**
                       **[maxDate]="model.max"**
                       [ngClass]="model.cls.element.control"
                       [placeholder]="model.placeholder">

                <div class="input-group-addon" (click)="datepicker.toggle()">
                    <img [src]="model.toggleIcon" style="cursor: pointer;"/>
                </div>

            </div>`

It's a very small change and I think not a breaking change.
Thanks a lot! :)

**Comment by udos86** [comment]
@cab-peax Hi! Thank you very much for bringing this up!

There'll be support for this in `5.0.2`.

**Comment by cab-peax** [comment]
cool. thanks a lot :)
