### ISSUE TITLE
Having the ability to specify angular material options in form model

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#581]
## I'm submitting a...

<pre><code>
[ ] Bug
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 5.0.2

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Many form element in UI-Material have options that it would be great to be able to set through ng-dynamic-forms, ie the startView input property of the datepicker form control.

Could you envisage to add an options property to Dynamic(Any)Model that could handle this requirement.

This would definitely make ng-dynamic-forms a must have for any angular project that heavily relies on forms.

**Comment by udos86** [comment]
@rernens Hi!

> Could you envisage to add an options property to Dynamic(Any)Model that could handle this requirement.

I was thinking about this already but I'm not sold on it as it would bring way more complexity into processing the form control model.

**Comment by rernens** [comment]
@udos86 

I understand your point but at the same time not doing so removes access to important options that would make ng-dynamic-options definitely a must.

To name a few :

- [mdAutocomplete]="any" on input that in conjunction with your templating would allow to solve the problem of autocomplete with selected value different from displayed value in autocomplete.
- mdPrefix and mdSuffix on input fields
- the datepicker options : startview, disabling the suffix, matDatepickerFilter, ...

Thanks for considering it

**Comment by udos86** [comment]
@rernens 

I do understand that you'd like to make use of all options.

So as were moving forward to `5.0.0` stable of Material I promise that I'll expose as many properties as possible.

> mdPrefix and mdSuffix on input fields

This is actually supported already.

For now I'm closing this. Thanks for your feedback!

**Comment by udos86** [comment]
@rernens 

I've got really good news! From `5.1.3` on you'll be able to define all kind of additional options on a `custom` property for any `DynamicFormValueControlModel`.

You can have a look at this already: 51ca7fe

**Comment by rernens** [comment]
@udos86 

I will try it and will keep you posted.

**Comment by udos86** [comment]
@rernens 

I'd be glad to hear your support.

**Comment by rernens** [comment]
@udos86 

so far the additional property meets my requirements.
Will do further tests.

**Comment by udos86** [comment]
@rernens Alright, good to hear!
