### ISSUE TITLE
CLI 5 sample project?

### ISSUE THREAD

**Issue by bischofb** [udos86/ng-dynamic-forms#582]
## I'm submitting a...

<pre><code>
[ ] Bug
[ x] Feature Request / Proposal
[ ] Question
</code></pre>

Would be fantastic to be able to download the sample project using the latest CLI so it's easier to see how to incorporate it into a current project.  :-)

**Comment by udos86** [comment]
@bischofb Hi!

There is really nothing special about using the lib in conjunction with CLI.

[Here's](https://github.com/udos86/ng-forms-workshop) my project for CLI testing. I'll upgrade it to Angular 5 as soon as possible.
