### ISSUE TITLE
Material slider options not available

### ISSUE THREAD

**Issue by patadv** [udos86/ng-dynamic-forms#585]
## I'm submitting a...

<pre><code>
[x ] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm building a form that will use a Material Slider and there are a couple options missing. I get this error: 

error TS2345: Argument of type '{ id: string; max: number; min: number; step: number; thumbLabel: string; value: number; vertical...' is not assignable to parameter of type 'DynamicSliderModelConfig'.
  Object literal may only specify known properties, and 'thumbLabel' does not exist in type 'DynamicSliderModelConfig'.

You can see I'm trying to set 'thumbLabel' here. By default, it's set in the dynamic-forms code to 'true' but it doesn't appear impossible to set this from what I can see. Looks like disabled, invert, step, and tickInterval are also missing. 

Possibly I'm not understanding how to set these properly. Thanks!

**Comment by udos86** [comment]
@patadv Hi!

> Possibly I'm not understanding how to set these properly. Thanks!

No, you're not misunderstanding anything here. At the same this is not bug either.

You're just facing a limitation of dynamic forms approach. Not every single property of every supported UI library is exposed by all `DynamicFormControlModel`s.

I'm always working on making everything more flexible until all external UI dependencies reach a stable major version.
