### ISSUE TITLE
Duplicating field values in form array

### ISSUE THREAD

**Issue by bevbomb** [udos86/ng-dynamic-forms#586]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...
<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

I’m creating a form which has two seperate form arrays, one with two fields per group and the other with 4. I’m using a service to fetch the fields from a remote source then mapping the models. When ever I type in any of the entries in either of the form arrays, the value is copied to the other fields within that array, when inserting a new group into the array it also has the value entered.

**Comment by udos86** [comment]
@bevbomb Hi!

I'm pretty sure, this is not a bug. 

You're probably referencing an outer model in your `groupFactory` function instead of defining it right there.

**Correct:**
```
new DynamicFormArrayModel({

    id: "myFormArray",
    groupFactory: () => {
        return [
            new DynamicInputModel({
                id: "myInput",
                label: "My Input"
            })
        ];
    }
})
```

**Incorrect:**
```
new DynamicFormArrayModel({

    id: "myFormArray",
    groupFactory: () => {
        return myOuterFormModel
    }
})
```

**Comment by bevbomb** [comment]
Ah i figured that would have been the cause.
There currently isn't any observable support for group factory is there? I might have to parse forward the json and build the models inside the group factory

**Comment by udos86** [comment]
@bevbomb 

> There currently isn't any observable support for group factory is there?

No sorry, currently not. Would make a nice enhancement in a future version.

> I might have to parse forward the json and build the models inside the group factory

Good luck!

**Comment by qodrinzo** [comment]
+1, requesting this feature

**Comment by bevbomb** [comment]
Hi @qodrinzo 
I have since built a pretty mean relations system off of this forms library, it handles a lot of copying of fields on conditions including running mathematical equations with two or more fields and setting it as the value. Unfortunately though I forked off of this project in November and ended up going down my own path for what I needed. I’ve rebuilt a lot of things including adding support for google address autocomplete as well as a heap of other custom controls
