### ISSUE TITLE
Relations: Copying values

### ISSUE THREAD

**Issue by bevbomb** [udos86/ng-dynamic-forms#587]
## I'm submitting a...

<pre><code>
[ ] Bug
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Great job with the relations system! 
So basically im imagining this would be used to allow the copying of other model values based on particular conditions. A common use case is having two address groups, one for billing and one for postal, if the user checks a checkbox which says “Postal address is the same as billing” and that field value is true, the postal address group could copy the values from the billing address group. Now I know this can cause issues like how do we copy values from one group to another without knowing what goes where, my first solution is to allow for a straight copy of child fields that have matching keys and ignoring any other child field that doesn’t exist in the source group. My second solution is to provide a function similar to the groupFactory to allow for transforming of data from one group to another, or from group to an array etc.

I’m really interested in this feature and I’m more then happy to help implement it.

**Comment by bevbomb** [comment]
After some more thinking around this, we could possibly provide an event which is trigger when the conditions are met which would pass the listed contexts for the conditions as well as the context which has the relation on it. This would allow any sort of custom functionality to be performed between relational fields

**Comment by udos86** [comment]
@bevbomb Hi!

> Great job with the relations system!

Thanks, man!

> I’m really interested in this feature and I’m more then happy to help implement it.

Great to hear. 

All in all I'm already planning a major refactoring of related form controls feature. 

I'd like to introduce a more solid and flexible rule engine to provide more different types of relations.

I'll open another Issue when I'm ready to start. Any help will be highly appreciated then.
