### ISSUE TITLE
Ability to create custom controls for certain inputs

### ISSUE THREAD

**Issue by bevbomb** [udos86/ng-dynamic-forms#588]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: X.Y.Z

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Is it possible to create/use custom form controls outside of the provided themes? I’ve looked through the source code for the NG Bootstrap theme is it looks like it’s just providing different form controls based on a switch case. Is it a matter of making my own custom template to use?
Also is it possible to provide more input options? As an example i want to create a custom control for addresses which uses a map and an input field to provide an address, I noticed you can provide an inputType for a standard input, is it just a matter of using that inputType as part of the referenced switch case above rather then creating an entirely new subclass of the DynamicInputModel?

**Comment by udos86** [comment]
@bevbomb  Hi!

> Is it possible to create/use custom form controls outside of the provided themes?

No, it is not possible and probably will never as this would result in overly complex template files and you having to set all control bindings manually. 

It's just beyond the scope of this project.

> Is it a matter of making my own custom template to use?

Yep, you would have to create your own custom template.

> is it just a matter of using that inputType as part of the referenced switch case above rather then creating an entirely new subclass of the DynamicInputModel?

No, sorry - `inputType` property simply defines the native HTML5 input type.
