### ISSUE TITLE
Bad links in README.md

### ISSUE THREAD

**Issue by seanforyou23** [udos86/ng-dynamic-forms#590]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Using this library for the first time and during the process came across some links which seem to be broken, just under the UI Modules section -

https://github.com/udos86/ng-dynamic-forms#ui-modules

Wanted to report in case there is some important information that should be showing.

Thank you for looking into this!
<img width="867" alt="screen shot 2017-11-14 at 5 55 34 pm" src="https://user-images.githubusercontent.com/5942899/32809512-0ff793e8-c965-11e7-9b96-ff03694f85bc.png">

**Comment by udos86** [comment]
@seanforyou23 Thank you very much for reporting this!

I'll correct it right away...

**Comment by seanforyou23** [comment]
Thank you!
