### ISSUE TITLE
Cannot run the default steps in the readme file

### ISSUE THREAD

**Issue by nicu-chiciuc** [udos86/ng-dynamic-forms#594]
## I'm submitting a...

<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## Description
I tried to copy the repository and go through the steps in the readme file. More specifically, everything installs correctly and when `npm start` is invoked the page starts loading and nothing happens afterwards.

One of the first error was that `:3000/node_modules/rxjs/operators/refCount.js` is blocked. Disabling the ad blocker solved it.

Yet afterwards I get the following error message:
<img width="547" alt="screen shot 2017-11-16 at 10 01 24 pm" src="https://user-images.githubusercontent.com/4076804/32913038-c87d55a0-cb19-11e7-9f9a-b0df56c1ffe5.png">

The most probably cause would be a package version mismatch yet I haven't delved to much into it. All that I found out was that the file `/node_modules/@angular/forms/bundles/forms.umd.js/src/model.js` cannot be found since `/node_modules/@angular/forms/bundles/forms.umd.js` is a file.

**Comment by udos86** [comment]
@nicu-chiciuc Hi!

Did you really execute all steps as describe in[ Running the sample](https://github.com/udos86/ng-dynamic-forms#running-the-sample)?

It seems that you forgot to transpile the sample code via `npm run watch:sample`...

I cannot verify any bugs here.

**Comment by nicu-chiciuc** [comment]
I tried the steps several times. I tried to execute `npm run watch:sample` in one terminal and `npm start` in another one. I also tried executing them sequentially by terminating the first command.

I guess the problem is in the `npm run build:packages`. The full, unaltered output can be found here https://gist.github.com/nicu-chiciuc/356acefc2a60a6bf33e218fbf38bd57f .

I think it will be easier for you to spot where the issue comes from.

**Comment by bobingham** [comment]
Same problem here.
Unhandled Promise rejection: Unexpected token <
  Evaluating http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js/src/model
  Evaluating http://localhost:3000/sample/app/app.module.js
  Evaluating http://localhost:3000/sample/main.jit.js
  Loading app ; Zone: <root> ; Task: Promise.then ; Value: Error: Unexpected token <
  Evaluating http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js/src/model
  Evaluating http://localhost:3000/sample/app/app.module.js
  Evaluating http://localhost:3000/sample/main.jit.js
  Loading app
    at eval (<anonymous>)
    at evaluate (evaluate.js:106)
    at instantiate.js:394
    at dynamicExecute (register-loader.js:665)
    at doEvaluate (register-loader.js:612)
    at ensureEvaluate (register-loader.js:520)
    at register-loader.js:538
    at doEvaluate (register-loader.js:610)
    at ensureEvaluate (register-loader.js:520)
    at register-loader.js:538 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:3000/node_modules/systemjs/dist/system.src.js:2818:16)
    at http://localhost:3000/node_modules/systemjs/dist/system.src.js:3621:21
    at dynamicExecute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:1142:26)
    at doEvaluate (http://localhost:3000/node_modules/systemjs/dist/system.src.js:1089:13)
    at ensureEvaluate (http://localhost:3000/node_modules/systemjs/dist/system.src.js:997:13)
    at http://localhost:3000/node_modules/systemjs/dist/system.src.js:1015:20
    at doEvaluate (http://localhost:3000/node_modules/systemjs/dist/system.src.js:1087:11)
    at ensureEvaluate (http://localhost:3000/node_modules/systemjs/dist/system.src.js:997:13)
    at http://localhost:3000/node_modules/systemjs/dist/system.src.js:1015:20
n.onUnhandledError @ zone.min.js:formatted:1478
r @ zone.min.js:formatted:1343
e @ zone.min.js:formatted:1491
n.microtaskDrainDone @ zone.min.js:formatted:1494
o @ zone.min.js:formatted:830
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
c @ zone.min.js:formatted:1386
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
c @ zone.min.js:formatted:1398
(anonymous) @ zone.min.js:formatted:1361
Promise resolved (async)
(anonymous) @ zone.min.js:formatted:1453
e @ zone.min.js:formatted:1528
e.then @ zone.min.js:formatted:1452
fetchFetch @ fetch.js:33
(anonymous) @ instantiate.js:167
e.invoke @ zone.min.js:formatted:1137
r.run @ zone.min.js:formatted:944
(anonymous) @ zone.min.js:formatted:1436
e.invokeTask @ zone.min.js:formatted:1161
r.runTask @ zone.min.js:formatted:987
o @ zone.min.js:formatted:823
Promise resolved (async)
r @ zone.min.js:formatted:812
e.scheduleTask @ zone.min.js:formatted:1155
r.scheduleTask @ zone.min.js:formatted:1014
r.scheduleMicroTask @ zone.min.js:formatted:1026
l @ zone.min.js:formatted:1434
e.then @ zone.min.js:formatted:1620
Loader.import @ loader-polyfill.js:64
SystemJSLoader$1.import @ systemjs-loader.js:126
(anonymous) @ index.jit.html:51

**Comment by udos86** [comment]
Closed as there are no bugs whatsoever
