### ISSUE TITLE
Tooltip style hints possible?

### ISSUE THREAD

**Issue by seanforyou23** [udos86/ng-dynamic-forms#595]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hello, I have a question about the display/styling/customizing of tooltip "hints" when users hover over a field in a generated form.

I have a simple DynamicFormGroupModel housing a few inputs. When I add a hint property to my DynamicInputModel, the resulting html is rendered to the DOM but it looks like some styling is missing (or maybe this is how its supposed to be?). This is the html structure that's added below my inputs.

`<span class="help-block" ng-reflect-klass="help-block" ng-reflect-ng-class="">Hint text...</span>`

See the screenshot below, the text is not hidden and always in full display.

<img width="371" alt="screen shot 2017-11-16 at 6 09 45 pm" src="https://user-images.githubusercontent.com/5942899/32921212-bb132530-cafa-11e7-86c4-97fb13ea953b.png">

1) Is this the expected behavior?
2) Can you point me to any related documentation for this that I may have missed?
3) Is there a way to control the markup that's rendered as a result of setting the hint property?
4) Is there a way to add the following attributes to the form elements themselves, using the hint property's value as the text? This is actually the ideal scenario.

`tooltip="Some tooltip hint" placement="bottom"`

Ultimately, to achieve having the hint property displayed to the user like this - https://valor-software.com/ngx-bootstrap/#/tooltip

Please let me know if there is a recommended approach, thank you!

**Comment by udos86** [comment]
@seanforyou23 Hi & Thank you for your detailed description!

> Is this the expected behavior?

Yes, it is.

> Can you point me to any related documentation for this that I may have missed?

You did not miss anything.

> Is there a way to control the markup that's rendered as a result of setting the hint property?

No sorry, hint markup can only be modified via CSS classes.

Therefore you should apply a cls config to your model:
```
{
    element: {
        hint: "my-hint-cls",
    },
    grid: {
        hint: "my-hint-grid-cls"
    }
}
```

> Is there a way to add the following attributes to the form elements themselves, using the hint property's value as the text? This is actually the ideal scenario.

No, sorry!

**Comment by seanforyou23** [comment]
No problem. Thanks for the information!
