### ISSUE TITLE
AoT Runtime errors with custom validators

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#596]
## I'm submitting a...

<pre><code>
[ ] Bug
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using...

<pre><code>
NG Dynamic Forms Version: 5.0.2 
angular 5.0.2 
angular-cli 1.5

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Despite carefully following the documentation regarding custom validators and  AoT, and so using the alternate validators notation ( as follow), 

```
validators: {
        required: null,
        isValidNic: {
          name: isValidNic.name,
          args: null
        }
      },
```
none of my custom validators are found at runtime. 

I am getting  the following runtime error :

```
ERROR Error: validator "isValidNic" is not provided via NG_VALIDATORS or NG_ASYNC_VALIDATORS
    at t.AqMF.t.getValidatorFn (main.222181029fe697d97972.bundle.js:1)
    at main.222181029fe697d97972.bundle.js:1
    at Array.map (<anonymous>)
    at t.AqMF.t.getValidatorFns (main.222181029fe697d97972.bundle.js:1)
    at t.AqMF.t.getValidators (main.222181029fe697d97972.bundle.js:1)
    at t.AqMF.t.createAbstractControlOptions (main.222181029fe697d97972.bundle.js:1)
    at main.222181029fe697d97972.bundle.js:1
    at Array.forEach (<anonymous>)
    at t.AqMF.t.createFormGroup (main.222181029fe697d97972.bundle.js:1)
    at l.ngOnInit (2.9e34f641e49439b1c7d7.chunk.js:1)

```

isValidNic is well provided via NG_VALIDATORS as all others in the relevant module

```
providers: [
    // myTalents custom validators
    { provide: NG_VALIDATORS, useValue: isValidNic, multi: true },
    { provide: NG_VALIDATORS, useValue: isValidSiret, multi: true },
    { provide: NG_ASYNC_VALIDATORS, useValue: registeredSiret, multi: true },
    { provide: NG_ASYNC_VALIDATORS, useValue: allowedSiret, multi: true }
  ]
```

what am I missing  or is it a bug related to angular 5.0 ?

**Comment by udos86** [comment]
@rernens Hi!

> what am I missing or is it a bug related to angular 5.0 ?

Are you providing the validators in your app module? 

Since the sample application seems to be working fine I assume there's currently no bug here.

**Comment by rernens** [comment]
@udos86 

Hi!
The app contains many modules that are lazyloaded.
I will try to define them in the app module and will keep you posted.

**Comment by rernens** [comment]
@udos86 
Hi again !

I did move the providers to the app module and tested it.
It works in dev mode but fails with the same error in AoT mode.
I has probably something to do with the fact that modules are lazy loaded.

**Comment by udos86** [comment]
@rernens Hi!

> I has probably something to do with the fact that modules are lazy loaded.

Mmh, my tests with the sample application are succeeding even when using lazy loaded modules.

Are you using CLI or `@ngtools/webpack` for AOT?

**Comment by rernens** [comment]
@udos86 

I am using angular-cli 1.5

**Comment by udos86** [comment]
@rernens 

I just created a new demo CLI project from scratch just for this issue but I still cannot verify any bugs concerning validators, lazy loaded modules and AOT.

**Comment by rernens** [comment]
@udos86 

I will do further test tomorrow to try to isolate where the problem comes from.

**Comment by rernens** [comment]
@udos86 

Hi !

I spent most of my night trying to figure out where the problem might come in looking how your code works when it comes to checking whether the Validators or the AsyncValidators are defined.

I did compile the app with AoT and sourcemap to allow some inner debugging.

First of all I can confirm that the getValidatorFn of DynamicFormValidationService has access to the relevant custom validators list NG_VALIDATORS in its validatorsToken arg whether the providers are defined in the app.module or in the lazy-loaded module.

the validatorsToken array contains two functions respectively named t and i, which well correspond to isValidNic for t and isValidSiret for i given what the sourcemap points to.

The code fails on 

```
else if (validatorsToken) { // Custom Validators
            validatorFn = validatorsToken.find(validatorFn => validatorFn.name === validatorName);
        }
```

because the validatorFn.name value ( t after AoT offuscation  ) does not match isValidNic ( the name of the custom validator function.

Carefully looking at the way the getValidatorFns was identifying the relation between the validator key and its name, I understood where the problem was lying.

I was overwriting the validator extended notation when at runtime I was binding the component context to the validator to allow access to this context from within the validator.

I did change the way I am making the binding to comply with the extended notation and everything works just fine.

Thanks for your help one more.

**Comment by udos86** [comment]
@rernens Congrats & thanks for your detailed explanation!

**Comment by rernens** [comment]
@udos86 

Hi Udo, 

still having a problem with async validators and trying to isolate the root cause.

I'll keep you posted.

**Comment by rernens** [comment]
@udos86 

I works now for both sync and async validators.

In order to make it work properly, with context binding for both sync and async validators with AoT these are de following requirements :

1, if the validators are used in a module that is lazy-loaded, add the providers to the lazy-loaded module

2. define the validator functionas follow,

for sync validator :

```
export function syncValidatorName( binding: any ): ValidatorFn {

  return ( control: AbstractControl): ValidationErrors | null => {

// your validation code here using 
// using binding.anyValue to get access to component this.anyValue

    return isValid ? null : { anything: false };

  };

}
```

for async Validator :

```
export function asyncValidatorName( binding: any ): AsyncValidatorFn {
  return ( control: AbstractControl ): Observable<ValidationErrors> | null => {
    return new Observable( observer => {
// your code here
// use binding to access services that are injected in the component using the validator ie log or myService below
      binding.myService.checkLoginExists(control.value)
        .subscribe(
          result => {
            binding.log.debug('asyncValidatorName validator function - login exists ' + result.exists);
            const response = result.exists === true ? { asyncValidatorName : false } : null;
            observer.next( response );
            observer.complete();
          },
          err => {
            binding.log.debug('asyncValidatorName validator function - error');
            const error = { asyncValidatorName : err };
            observer.next( error) ;
            observer.complete();
          }
        );
    });
  };
}
```

3; use the alternate notation in the model

4; in the component onInit, prior to building the form do the following

```
// bind this to model validator  to get access to context and/or injected dependencies
    this.inputModel = this.formService.findById('modelName', this.formModel) as DynamicInputModel;
    this.inputModel.validators['modelName'].args = this;
// for asyncValidators use 
//this.inputModel.asyncValidators['modelName'].args = this;
```

hope it helps
