### ISSUE TITLE
ui-material 5.0.3 has wrong dependency on angular material

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#601]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.0.3`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  5.0.3
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

current dependency is 5.0.0-rc1 but should be 5.0.0-rc.1

**Comment by udos86** [comment]
@rernens Merci beaucoup for reporting this!

**Comment by rernens** [comment]
@udos86 

you are welcome.
