### ISSUE TITLE
align="START" in ng-template for DynamicFormArrayModel modelid does render template before

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#609]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.0.3+`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  5.0.3+
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

assigning align="START" to a ng-template with a modelIId pointing to a DynamicFormArrayModel  will not render the template before the element but after it.

**Comment by udos86** [comment]
Now works in `6.0.0`
