### ISSUE TITLE
Upgrading to 5.1 no longer allow to assign custom layout to specific element in DynamicFormArrayModel

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#610]
## I'm submitting a

<pre><code>
[x] Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  5.1.0
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Up to 5.0.3 it was possible to programmatically customize the layout of a specific element of a given row belonging to a DynamicFormArrayModel.

In my case I was able to hide the first element of the first row of an advanced search form where the first element is an operator ( AND, OR, NOT ) which has no reasons to be specified for the first criteria of an advanced search as you can see in the screen shot below.

![capture d ecran 2017-11-27 a 11 26 59](https://user-images.githubusercontent.com/10088036/33262287-12e099f0-d366-11e7-9037-9414d4e4be61.png)

I was programmatically setting the cls.grid.container property of the first element of the first row of the array to an 'invisible' class.

With 5.1 I can disable it but no longer hide it.

If I apply my setting to the element layout ( ie grid.container ) it applies to all rows. 

While this works for programatically hiding or showing  a form element outside of form array, it is not suitable for a form element in a form array row, though.

I looked in your code to find a way to do it but could not figure out how.

Despite the cls attribute being still present in the model, programatically changing it does not affect the appearance of the element.

**Comment by udos86** [comment]
@rernens Hi again!

First of all let me say that this looks like a really nice, well designed form! Congrats!

All in all you're right, yet  it's not a bug or regression. 

Even when using `DynamicFormLayour` you're still free to mix it with `clsConfig` for certain models. 

Maybe I even reverse the deprecation of `clsConfig`.

**Comment by rernens** [comment]
@udos86 

Hi,

I will revert my changes for this and keep you posted.

**Comment by udos86** [comment]
> Once more thanks a lot for your help.

No problemo

**Comment by rernens** [comment]
@udos86 

Hi Udo,

First of all happy New Year to you. 

Due to some priority changes, I was working on something else for a while and now I am resuming my work on this project ...

It looks like you finally decided to completely remove the ability to use clsconfig .

As a result I am no longer able to hide a specific control such as the first control of the first row in a array of control as I was doing before ( see above).

I thought that the hidden property introduced in 5.4.1 would do the trick for me but unless I am missing the way this is supposed to work, I can't get it to hide my control.

This the way I am trying to accomplish this now with version 5.4.2

```
let selectorsModel = this.formService.findById('selectors', this.choiceFormModel) as DynamicFormArrayModel;

let operatorModel = this.formService.findById('operator', selectorsModel.groups[0].group);
operatorModel.disabled = true;
operatorModel.hidden = true;

this.choiceForm = this.formService.createFormGroup(this.choiceFormModel);

```

The control gets disabled but does not get hidden.

Thanks for your help.

**Comment by udos86** [comment]
@rernens Hi Robert, I wish you a happy new year, too! 

> It looks like you finally decided to completely remove the ability to use clsconfig

No, actually not. It just got renamed internally to `layout`. You're still free to pass a layout object to the model constructor.

> I thought that the hidden property introduced in 5.4.1 would do the trick for me but unless I am missing the way this is supposed to work, I can't get it to hide my control.

When you're directly using `DynamicFormControlComponent` in your template you need to add the built-in [hidden] binding yourself.

**Comment by rernens** [comment]
@udos86 

hi Udo

> It just got renamed internally to layout.

Thanks. I missed that. It works.

> When you're directly using DynamicFormControlComponent in your template you need to add the built-in [hidden] binding yourself.

I am not sure to understand what you mean, could you be more explicit ?

**Comment by udos86** [comment]
@rernens 

> I am not sure to understand what you mean, could you be more explicit ?

When you're using `DynamicFormComponent` in your template, `hidden` is already bound internally for you:
```
<dynamic-material-form [group]="formGroup"
                       [layout]="formLayout"
                       [model]="formModel"></dynamic-material-form> 
```

When using `DynamicFormControlComponent` you need to apply the binding yourself, however:
```
<dynamic-material-form-control *ngFor="let model of formModel; trackBy: trackByFn"
                               [group]="formGroup"
                               [hasErrorMessaging]="model.hasErrorMessages"
                               [hidden]="model.hidden"
                               [layout]="formLayout"
                               [model]="model"></dynamic-material-form-control>
```

When you

**Comment by rernens** [comment]
@udos86 

> When using DynamicFormControlComponent directly, you need to apply the binding yourself however:

Than I had well understood what to do ( and it is what I am doing )  

```
<dynamic-form-material-control *ngFor="let searchControlModel of searchFormModel"
                                       [group]="searchForm"
                                       [layout]="searchFormLayout"
                                       [model]="searchControlModel"
                                       [hidden]="searchControlModel.hidden"
                                       [hasErrorMessaging]="searchControlModel.hasErrorMessages"
                                       [showCharacterHint]="searchControlModel.type === 'input'"
                                       (dfChange)="onFormChange( $event )">
```

but as far as I can tell, setting the control hidden property to true as follow

```
const selectorsModel = this.formService.findById('selectors', this.searchFormModel) as DynamicFormArrayModel;
const operatorModel = this.formService.findById('operator', selectorsModel.groups[0].group);
operatorModel.disabled = true;
operatorModel.hidden = true;
// operatorModel.layout.grid.container = 'hidden';

this.searchForm = this.formService.createFormGroup(this.searchFormModel);
```

does not hide the control while being correctly disabled.

**Comment by udos86** [comment]
@rernens Ok, I'll need to check this if there's an unknown bug...

**Comment by begandroide** [comment]
hi! @udos86 im facing the same issue on my angular material app, i cant specify a custom class for a item in form array, in my case y use a matcher condition that modify the layout container of a control if is a match, but if the control is in formArray all the rows or formGroups of the formArray changes layout container class....

I was being debugging core.js (ng-dynamic-forms) when a condition matches, and i can see that if the match condition is in a formArray, so the model of groupPrototype changes, so if we detect changes, all the childrens formgroups of formArray changes, because the groupPrototype did it. So weird, please you have any workaround?

or if @rernens could share his solution, would be awesome

**Comment by begandroide** [comment]
note that i dont use hidden property to show/hide controls because make that other controls of group move his position accord to the grid system... so, how i hide controls? adding a class "visibilityHidden or visitibilityVisible" to the layout->element->container, and when i modify the layout of a control inside a formArray all other controls of the formArray changes (because the groupPrototype also changes)

**Comment by begandroide** [comment]
Hi @udos86 can you help me please? I can't put custom layout to specific element in `DynamicFormArrayModel`; in fact I can put a class to specific element in formArray by some related relation, but when I trigger `dynamicFormService.detectChanges()`, the classes has been removed from specific controls and all controls has class of prototype form array model.

As example I has a checkbox in formArray that has label "En curso", if this checkbox is selected so the date field "Fecha de término" is visibility hidden. This behavior is triggered by adding a class in specific layout element (where related control matches). At the moment if I don't trigger `detectChanges` from `dynamicFormService`, I can see all right, but if I trigger manually `detectChanges`, all classes has been reseted to prototype.
