### ISSUE TITLE
Ui-Material - file upload

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#611]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

File upload is not part of Angular Material 2 roadmap and won't be in the near future.

Il would be nice if for inputType = file in angular material you could implement something like this

http://plnkr.co/edit/VGCSprNVT1pobOxjWwmT?p=preview

or allow of a custom implementation where ng-template could be used to fill the content of the mat-form-field ( ie replacing the input tag in the inputType INPUT) with a custom component.

**Comment by udos86** [comment]
@rernens 

Wow, you're really trying to push Material UI package forward!

Before implementing this I'd like to wait for 5.0.0 stable.

BTW: Currently I'm working on chips support...

**Comment by rernens** [comment]
@udos86 

Thanks Udo, no problem.

Meanwhile I am working something out with the existing ui-material implementation.

I'll publish the outcome later today.

**Comment by mesemus** [comment]
@rernens, @udos86 

Hi Robert, just want to ask whether you have been successful in integrating merlosy's file implementation into ui-material. If not, I can do it as I need it for a project I'm working on.

Thanks,

Mirek Simek

**Comment by rernens** [comment]
@mesemus 

I have made a different implementation than this one. I can share de code with you if you want.

**Comment by mesemus** [comment]
@rernens

that would be great, thanks a lot. My email is miroslav.simek@vscht.cz.

**Comment by rernens** [comment]
@mesemus 

I will send you the code tomorrow when I get back at the office.

**Comment by Orrefors** [comment]
It would be great if you could make your changes public so i also could implement it. :) or send the same email to my address located at my bio.

**Comment by rernens** [comment]
@Orrefors @mesemus

It is a this stage a custom implementation specific to my project but I will create a repository and make it publicly available next week.

**Comment by udos86** [comment]
Starting with `6.0.0` major release you can now plugin your own custom form controls.
