### ISSUE TITLE
Attach any object to a checkbox value

### ISSUE THREAD

**Issue by damianorenfer** [udos86/ng-dynamic-forms#618]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hi,

I'm building some forms which include "relationships" between objects of my data model. For example, a User has many Role. So in the user form, I need to show a list of roles. I first thought that I could achieve this by using a select (with multiple selection) control, but you stated in #303 that using a checkbox group is a better option.

I tried to set the `value` property of a `CheckboxControlModel` to a Role object, and unfortunately we can only set it to a boolean which is obviously used to set the 'checked' state. It seems that `checked` and `value` properties achieve the same goal in `CheckboxControlModel`.

My proposal would be to have a `CheckboxControlModel<T>` like you did with `DynamicSelectModel<T>`. This would allow us to attach any object to the `value` property of a `CheckboxControlModel`.

**Comment by udos86** [comment]
@damianorenfer Hi!

> but you stated in #303 that using a checkbox group is a better option.

I did not mean this in general. 

I'd only avoid native HTML select `multiple` attribute. Even the [W3C docs](https://www.w3schools.com/tags/att_select_multiple.asp) discourage you from doing that.

However when you're using a UI library like Material it's perfectly fine making use of `multiple` for select controls.

**Comment by damianorenfer** [comment]
Ok thank you! I ended up using PrimeNG which has a lot of great components!
