### ISSUE TITLE
Dynamically creating form controls using DynamicFormService.fromJSON() only

### ISSUE THREAD

**Issue by kovax** [udos86/ng-dynamic-forms#619]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: 1.4.34

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description
I have a an application which dynamically creates forms from XML Schema. I started to develop UI based on PrimeNG, I made a REST Service which parses the required XML Schema, and the returned JSON is loaded by DynamicFormService.fromJSON(model). My testing shows that this is working, and I sure I will be able to generate the controls of my forms this way. So I would like to know if this is a legitimate use of this API, because the documentation is a bit wage on this.

**Comment by udos86** [comment]
@kovax Hi!

> So I would like to know if this is a legitimate use of this API

Yes, it's absolutely fine doing this. 

Lately I added some internal tweaks to make this even more comfortable.

I'll try to improve the documentation on this as soon as possible.
