### ISSUE TITLE
Building form and saving schema

### ISSUE THREAD

**Issue by z0m1x** [udos86/ng-dynamic-forms#623]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[X ] Prime NG
</code></pre>

## Description

I would like to know if it's possible to build a form and save the schema, the formModel.
The idea is to have an admin that can build the form and customers to use the form.
All working good with posting the form, add and remove items.

I'm using this:
```
    removeItem(context: DynamicFormArrayModel, index: number, id:string) {
        this.formArrayControl = this.formGroup.get(id) as FormArray; 
        this.formService.removeFormArrayGroup(index, this.formArrayControl, context);
    }
```

and markup:
```
                                    <ng-template *ngFor="let model of formModel" modelId="{{model.id}}" let-id="id" let-index="index" let-context="context">
                                        <button type="button" (click)="removeItem(context, index, model.id)">Remove {{model.name}}</button>
                                    </ng-template>
```
Then i have a button for updating the form, where i will send the new schema of the form to a database.
If i check "this.formGroup" the object is removed. But on "this.formModel" it still exist.

Is the only way to check if the deleted item does not exist in formGroup and then remove it from the model and save it to db. 

Any thoughts?

**Comment by udos86** [comment]
@z0m1x Hi!

> I would like to know if it's possible to build a form and save the schema, the formModel.?

Well, basic functionality for doing this is provided as described in chapter on [JSON export / import](https://github.com/udos86/ng-dynamic-forms#json-export--import).

I'll also deliver another documentation on how to model a form with JSON instead of constructors within the next days.
