### ISSUE TITLE
Controlling the order of form groups

### ISSUE THREAD

**Issue by seanforyou23** [udos86/ng-dynamic-forms#624]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `1.4.31`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hello,

I have this lovely form, generated using ng-dynamic-forms.

<img width="870" alt="screen shot 2017-12-14 at 5 02 54 pm" src="https://user-images.githubusercontent.com/5942899/34017087-4547c2f8-e0f2-11e7-8ae3-ee9aa221c9e0.png">

We also have many other forms using the same engine. Currently though, the order of all the inputs is seemingly random. For the attached image, what I really want is;

Broker URL input
User Name input
Password input
Client ID input
Skip Certificate checkbox
Broker Certificate textarea
client Certificate textarea

I similarly wish to control the order of the input groups for many of the forms, each in different ways. I see the mention of `this.formService.moveFormArrayGroup(...)` in the readme but I'm not clear about how to actually use it. I see the signature `moveFormArrayGroup(index: number, step: number, formArray: FormArray, model: DynamicFormArrayModel): void` but it's still not so clear what each of these parameters are used for. Any chance you could add an example or small text related to how this function can be used?

Is there another approach that's perhaps more easily configurable for lots of forms? Like can the ordering be controlled by a JSON property by chance? I think this would be ideal if it's possible. 

Apologies if I've overlooked part of the documentation, feel free to point me there if I have. Thank you!!!

**Comment by udos86** [comment]
@seanforyou23 Hi there! Nice form!

> Currently though, the order of all the inputs is seemingly random.

Actually, the order of the controls in the form should exactly represent the order of the models in your form model as long as you stick to the documentation.

> Like can the ordering be controlled by a JSON property by chance?

I have already considered introducing a new property `order` and still need to check the complexity of implementing this first.

> Apologies if I've overlooked part of the documentation, feel free to point me there if I have. Thank you!!!

No problemo!

**Comment by udos86** [comment]
@seanforyou23 

After some investigation I have to decline this feature proposal.

The main reasons for this are:

1. `sort()` function in JavaScript is not guaranteed to be stable by the ECMAScript standard. In Chrome QuickSort is used when there are more than 10 elements in an array which breaks the natural order in some cases when compare function returns 0.

The only reliable solution would be to implement one's own MergeSort.

2. heavy sort operation can lead to a performance bottleneck and should not be encouraged by default which would be the case if I introduce `order` property.

**Comment by seanforyou23** [comment]
Thank you for looking into this!
