### ISSUE TITLE
Add more multi fields base on input type="number" value.

### ISSUE THREAD

**Issue by malikfaizanhaider** [udos86/ng-dynamic-forms#625]
## I'm submitting a

<pre><code>
[ ] Question
</code></pre>
![ng dynamics forms sample app aot edition](https://user-images.githubusercontent.com/4697658/34071770-7ff88ce6-e29d-11e7-8351-4338c10e7de3.jpg)

## I'm using

<pre><code>
NG Dynamic Forms Version: `Latest`

[ ] Material  

</code></pre>

## Description

Hi Team,

It's possible to add multi-input fields base on input type="number".

**Comment by udos86** [comment]
@malikfaizanhaider Hi!

> It's possible to add multi-input fields base on input type="number".

What do you exactly mean by multi-input fields?
