### ISSUE TITLE
Unable to render in universal (TypeError: Reflect.defineMetadata is not a function)

### ISSUE THREAD

**Issue by chrisvfabio** [udos86/ng-dynamic-forms#629]
## I'm submitting a

<pre><code>
[X ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.2.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Unable to run in universal mode.

NodeInvocationException: Prerendering failed because of error: TypeError: Reflect.defineMetadata is not a function
at /Users/xxx/Code/ng-app/node_modules/@ng-dynamic-forms/core/bundles/core.umd.js:38:17

**Comment by udos86** [comment]
@chrisvfabio Hi!

I can't see this being a bug at the moment.

As I'm not familiar with Universal I'd guess you're [missing some dependency](https://github.com/angular/angular/issues/11720)...

**Comment by chrisvfabio** [comment]
@udos86 Seems like it's an issue with the .NET Core + Angular 5.0 template I'm using. I managed to get it working with the https://github.com/angular/universal-starter. 

I am importing the `reflect-metadata` into my main.server.ts, but still getting the error. I will investigate this further and perhaps open an issue with aspnet. 

Thanks! Closing this as it's not related to this project.
