### ISSUE TITLE
Populate Select options from an external source

### ISSUE THREAD

**Issue by underwoodarturo** [udos86/ng-dynamic-forms#634]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.1.2`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi! First of all, I want to congratulate you for this great library. 
I'm wondering if there's a way to populate the Select options from an external source (an API for example) from the form model and not from the controller?
I really appreciate any help you can provide!

**Comment by udos86** [comment]
@underwoodarturo Hi!

> First of all, I want to congratulate you for this great library.

Thank you very much 👍 

> I'm wondering if there's a way to populate the Select options from an external source

Yes, absolutely. 

You can assign an `Observable<DynamicFormOptionConfig<T>>` to the `options `property. 

This is shown in [Bootstrap sample model](https://github.com/udos86/ng-dynamic-forms/blob/master/sample/app/ui-bootstrap/bootstrap-sample-form.model.ts).

**Comment by underwoodarturo** [comment]
Thank you for your quick response! I've already reviewed the sample you mention. But I would like to create something like:
```javascript
new DynamicSelectModel<string>({
            id: "bootstrapSelect",
            label: "Select",
            mode: "fromtable",
            options: of(ChangeOptionsService("catalog_1")) //* Class to call the API
        }),
new DynamicSelectModel<string>({                            
            id: "bootstrapSelect2",
            label: "Select 2",
            mode: "fromtable",
            options: of(ChangeOptionsService("catalog_2")) //* Class to call the API
        })
```
is this possible?

**Comment by udos86** [comment]
> is this possible?

Yes, just assign the Observable that is directly delivered by Angular `HttpClient` or dispatched through your `ChangeOptionsService`:

`options: this.http.get<DynamicFormOptionConfig<string>[]>(url)`

**Comment by underwoodarturo** [comment]
In that case, do I need to create the model as a class instead of a "const"? to be able to inject the http client to it. By any chance, do you have a sample of this? Because I guess is similar to the Autocompletion Sample, but I don't know how to reference the class into the Controller when it's no longer a const :( . Thank you!

**Comment by udos86** [comment]
@underwoodarturo 

> In that case, do I need to create the model as a class instead of a "const"?

You could put the model directly into your component but **you don't have to**.

You can update your `options` Observable from anywhere as long as you're holding a reference to the corresponding `DynamicOptionControlModel` (see [API docs](http://ng2-dynamic-forms.udos86.de/docs/core/classes/_model_dynamic_option_control_model_.dynamicoptioncontrolmodel.html)).

**Comment by underwoodarturo** [comment]
Awesome, thank you very much 👍 !
