### ISSUE TITLE
Ionic Pattern Validation

### ISSUE THREAD

**Issue by ar27111994** [udos86/ng-dynamic-forms#645]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi @udos86 , I'm trying to use the `pattern` property of DynamicFormModel configuration to achieve the same effect as Angular/HTML 5 pattern attribute, but cannot get it to work: Here's my code:

```
controlConfig = { id: 'custom_field[' + field.location + '][' + field.custom_field_id + ']',
                       placeholder: field.name,
                       value: field.value,
                       inputType: "text",
                       pattern: "/[0-9]*/" //or "[0-9]*"
};
```
`this.formModel.push(new DynamicInputModel(controlConfig));`

Maybe I am doing something wrong. But I couldn't find any guideline/example in the docs. Please help!

**Comment by udos86** [comment]
@ar27111994 Hi!

Please give me some time to check this.

**Comment by ar27111994** [comment]
Ok, thanks. I just want to solve it as my app slightly depends on it.

**Comment by udos86** [comment]
@ar27111994 

Ok, so the reason `pattern` isn't working is simply because ionic input does not support it.

If you'd like to add pattern validation apply a validator function instead.

**Comment by ar27111994** [comment]
@udos86  sorry I disagree with your assumption. `ion-input` indeed supports pattern attribute if `type` attribute is used. For example you can try:

`<ion-input class="form-control" type="number" pattern="[0-9]*" formControlName="height" [(ngModel)]="height"></ion-input>`

to force a numeric keypad only feature on Android apps.

**Comment by ar27111994** [comment]
Hi @udos86 , please re-op this issue and examine/merge my PR. Thanks.

**Comment by udos86** [comment]
@ar27111994 Alright!

Can't find it in the [official docs](https://ionicframework.com/docs/api/components/input/Input/) however...
