### ISSUE TITLE
Example runs good but components are not grouped - all in one column

### ISSUE THREAD

**Issue by vdizdarevic** [udos86/ng-dynamic-forms#646]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I made a running example without any error, and no message in browser log, everything runs good but components are not grouped - all are positioned in one column (check-boxes are good). 

I check DOM, it contains div with role="group" and look like DOM is OK.
Did I miss any styling?
Any tip? Thanks.

**Comment by udos86** [comment]
@vdizdarevic Hi!

> Did I miss any styling?

Please have a look at the sample application on how to style dynamic forms.

**Comment by vdizdarevic** [comment]
Thank you, I miss to copy second part of the file
ng-dynamic-forms/sample/styles.css

I just copy first import line.

**Comment by udos86** [comment]
@vdizdarevic Great! 👍
