### ISSUE TITLE
minLength and maxLength error messages are not displayed

### ISSUE THREAD

**Issue by laurentboileau** [udos86/ng-dynamic-forms#647]
## I'm submitting a
<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `5.4.1`

[x] Basic UI
[x] Bootstrap UI  
[x] Foundation UI
[x] Ionic UI
[x] Kendo UI
[x] Material  
[x] NG Bootstrap
[x] Prime NG
</code></pre>

## Description
`minLength` and `maxLength` error messages are not displayed.

**Comment by udos86** [comment]
@laurentboileau 

Thank you very much for tracking this bug!

I'll merge your PR right away...
