### ISSUE TITLE
ERROR TypeError: this.validator is not a function

### ISSUE THREAD

**Issue by TheMagnificent11** [udos86/ng-dynamic-forms#649]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm trying to implement `ng-dynamic-forms` in my Angular 4 app, but I'm getting the following error.

I've created a pull request on the branch in my Github repository where I'm trying to do the implementation so that you can see the code changes (and my entire code): https://github.com/TheMagnificent11/LunchVoting/pull/15/files

Here's my error:
```
LoginComponent_Host.html:1 ERROR TypeError: this.validator is not a function
    at FormControl.AbstractControl._runValidator (vendor.js:37915)
    at FormControl.AbstractControl.updateValueAndValidity (vendor.js:37883)
    at FormControl.AbstractControl.enable (vendor.js:37826)
    at FormControl._applyFormState (vendor.js:38345)
    at new FormControl (vendor.js:38205)
    at vendor.js:84896
    at Array.forEach (<anonymous>)
    at DynamicFormService.createFormGroup (vendor.js:84880)
    at LoginComponent.ngOnInit (login.component.ts:33)
    at checkAndUpdateDirectiveInline (vendor.js:21963)
```

Do you know what I'm doing wrong?

**Comment by udos86** [comment]
@TheMagnificent11 Hi!

> I'm trying to implement ng-dynamic-forms in my Angular 4 app, but I'm getting the following error.

Could you please upgrade to Angular 5 and try again?

**Comment by TheMagnificent11** [comment]
Will do

**Comment by TheMagnificent11** [comment]
Thanks, that worked 👍  I really like what you've done with this project...so many awesome features!

I've got a couple of follow-up questions.

The first is the alignment (see image below)
![error alignment](https://user-images.githubusercontent.com/5241102/34922337-32d76690-f9da-11e7-8acd-1e43fd1b9b6d.png)

I tried to override it in my app.component.css .
```
ul.has-error {
    -webkit-padding-start: 0 !important;
}
```

Also, is there a better way to get the input values out of the form model.  My current code is:
```
    onSubmit(): void {
        let email = this.formService.findById('email', this.formModel) as DynamicInputModel;
        let password = this.formService.findById('password', this.formModel) as DynamicInputModel;

        this.authManager.login(email.value as string, password.value as string)
            .then(() => {
                this.router.navigate([PAGE_ROUTES[PAGE_NAMES.HOME].path]);
            })
            .catch(() => {
                // TODO
                alert("incorrect email or password");
            });
    }
```

**Comment by udos86** [comment]
@TheMagnificent11 

> I really like what you've done with this project...so many awesome features!

Thank you very much.

> I tried to override it in my app.component.css, but it didn't work.

Please have a look at the Angular [component styles docs](https://angular.io/guide/component-styles#style-scope)...

> Also, is there a better way to get the input values out of the form model?

No, but you could also use `valueUpdates` [observable](https://github.com/udos86/ng-dynamic-forms#updating-form-models).
