### ISSUE TITLE
Why configure the layout alone？

### ISSUE THREAD

**Issue by smile2014** [udos86/ng-dynamic-forms#652]
Layout alone configuration, dynamic form is not more troublesome yet

**Comment by smile2014** [comment]
new DynamicDatePickerModel({
                id: "departureDate",
                inline: false,
                placeholder: "Date of Departure",
                classname:'col3'
            }

**Comment by udos86** [comment]
@smile2014 

You're still completely free to add a layout into the model constructor...

There's no regression whatsoever...
