### ISSUE TITLE
can't import DYNAMIC_VALIDATORS

### ISSUE THREAD

**Issue by zimdero** [udos86/ng-dynamic-forms#653]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `^1.4.34`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hello, why i can't 
<code></pre>
import  { DYNAMIC_VALIDATORS }  from '@ng-dynamic-forms/core';
</code></pre>
There is not some class
Where is this class, because i can't find it.

**Comment by vdizdarevic** [comment]
Hi, I just made my example working, so I will try to help you.
It's suppose to be there, please try with:

npm install @ng-dynamic-forms/core -S

May be some problem with installed packages.

**Comment by zimdero** [comment]
There was problem in versions, in version ^1.4.34 isn't DYNAMIC_VALIDATORS class,  i remove package and after reinstall the version is ^5.4.2 and now everything works fine, thanks!

**Comment by udos86** [comment]
@vdizdarevic Thanks for helping out!
