### ISSUE TITLE
[ui-material] Email validation error appearing together with required error.

### ISSUE THREAD

**Issue by mdentinho** [udos86/ng-dynamic-forms#659]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

When an email field has both `email` and `required` validatiors, if you type something and then clean it, their respective error messages appear together.

**Reproduction:**
![email-validation-error](https://d2ffutrenqvap3.cloudfront.net/items/0H1U3N400o1j0x020M1V/Screen%20Recording%202018-01-24%20at%2001.30%20AM.gif?v=22840318)

**The `DynamicInputModel`s for the above form:**
```javascript
const credentialFields = [
  new DynamicInputModel({
    id: 'email',
    inputType: 'email',
    label: 'Email',
    placeholder: 'user@domain.com',
    validators: {
      email: null,
      required: null,
    },
    errorMessages: {
      email: 'The Email is not valid',
      required: 'The Email is required',
    },
  }),
  new DynamicInputModel({
    id: 'password',
    inputType: 'password',
    label: 'Password',
    placeholder: '********',
    minLength: 8,
    validators: {
      required: null
    },
    errorMessages: {
      minLength: 'The Password must have at least 8 characters',
      required: 'The Password is required',
    }
  }),
];
```

**Comment by udos86** [comment]
@mdentinho Hi!

I cannot classify this as a bug as the error messages correctly represent the  current validation state of the form.

Following my custom layout pattern "solid yet unobtrusive" I'd encourage you to add some small CSS rule to only show the required message when the field is empty.

**Comment by mdentinho** [comment]
@udos86 Thanks for your reply.

I have done the CSS solution, but it seems to me that the required message being alone when shown was supposed to be a feature of the email type field, as it already works like this with the other field types.

The reason I've opened this as a Bug is because of this lack of consistence, which made me think that it was something to be fixed.

If you're ok with fixing/implementing this, I can try to send a PR when I have some time.

Cheers!

**Comment by udos86** [comment]
@mdentinho 

> I have done the CSS solution, but it seems to me that the required message being alone when shown was supposed to be a feature of the email type field, as it already works like this with the other field types.

> The reason I've opened this as a Bug is because of this lack of consistence

Sorry, I'm a bit at a loss here. What exactly do you mean when talking about consistence?

**Comment by udos86** [comment]
Closed due to inactivity
