### ISSUE TITLE
[ui-material] Date placeholder appearing as null when not defined in Model

### ISSUE THREAD

**Issue by mdentinho** [udos86/ng-dynamic-forms#661]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

When no placeholder is defined in a `DynamicDatePickerModel` it appears as `null`.

**Reproduction:**
![null-placeholder](https://d2ffutrenqvap3.cloudfront.net/items/19051P3G2P3D1B1M352L/Screen%20Recording%202018-01-24%20at%2012.06%20PM.gif?v=8869a66c)

**The `DynamicInputModel` for the above date form field:**
```javascript
new DynamicDatePickerModel({
  id: 'date',
  label: 'Date',
})
```

**Comment by udos86** [comment]
@mdentinho Hi!

I'm not sure wether to classify this as a bug or not since it's working fine for other form field controls.

Also there is way to avoid this:

```javascript
new DynamicDatePickerModel({
  id: 'date',
  label: 'Date',
  additional: {
    floatLabel: 'never'
  }
})
```

**Comment by udos86** [comment]
closed due to no further replies
