### ISSUE TITLE
[ui-material] Draggable Slide Toggles

### ISSUE THREAD

**Issue by Sntax** [udos86/ng-dynamic-forms#664]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

The slide toggle in the `@ng-dynamic-forms/ui-material: 5.4.2` package is not currently _"click and drag"_ slidable. Right now it toggles just fine with a click - but a user is not able to "click and drag" the slider as is functionally displayed in the official angular-material guides: https://material.angular.io/components/slide-toggle/overview

**Comment by udos86** [comment]
@Sntax Hi!

Works perfectly fine for me. Just have a look at the [live demo](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form).

You're probably missing [HammerJS](https://material.angular.io/guide/getting-started#step-5-gesture-support)...

**Comment by Sntax** [comment]
Whoops! Thanks! Should have checked the demo first.
