### ISSUE TITLE
What could be the cause that Material Formgoup-Elements don't display next to each other?

### ISSUE THREAD

**Issue by Stanjs** [udos86/ng-dynamic-forms#665]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hello,
currently i try to rebuild the example project in my project but when i use the exact same FormGroup provided in your example Project it gets diplayed like this:
![image](https://user-images.githubusercontent.com/35807039/35393410-2c089bf0-01e5-11e8-8111-ee94077c7285.png)
instead of this:
![image](https://user-images.githubusercontent.com/35807039/35393427-3af3132a-01e5-11e8-993b-80d2b837024e.png)
I haven't wrapped any new classes around the router or any other HTML element that is wrapped around the "dynamic-material-form" i only use another preset from material (which shouldn't change things). What could be the problem here?

**Comment by udos86** [comment]
@Stanjs Hi there!

You need to provide some custom styling in order to achieve this.

Please have a look [here](https://github.com/udos86/ng-dynamic-forms/blob/master/sample/styles.css#L191)...
