### ISSUE TITLE
Error Message not shown for custom Validators

### ISSUE THREAD

**Issue by Karamuto** [udos86/ng-dynamic-forms#666]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.3`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

When using a custom validator, the corresponding error message is not shown.

I used the validator from your example ( the one with startsWith ) and the validor itself works. ( Input is colored red )

**Comment by udos86** [comment]
@Karamuto Hi!

> When using a custom validator, the corresponding error message is not shown.

Could you be a bit more specific? 

As you can see in the [sample material form ](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form)it actually should work fine...

**Comment by Karamuto** [comment]
Okay I found the 'mistake' in my concept.

I thought, that using the same naming pattern as in the original Angular Validators would work, but this doesn't seem to be the case.

Example:

This works:

```
export const startsWith = (start: string) => {
  return (control: AbstractControl) => {
    const hasError = control.value ? !(control.value as string).startsWith(start) : false;
    return hasError ? {startsWith: true} : null;
  };
};

validators: {
              startsWith: 'cheese'
            },
            errorMessages: {
              startsWith: 'Bacon!'
            }
```

This doesn't:

```
export const startsWith = (start: string) => {
  return (control: AbstractControl) => {
    const hasError = control.value ? !(control.value as string).startsWith(start) : false;
    return hasError ? {requiredStartsWith: true} : null;
  };
};

validators: {
              startsWith: 'cheese'
            },
            errorMessages: {
              startsWith: 'Bacon!'
            }
```

It still feels weird, that we use `requiredPattern` for the Angular validators instead of `pattern`

**Comment by udos86** [comment]
@Karamuto Alright!
