### ISSUE TITLE
Input group model

### ISSUE THREAD

**Issue by liliom55** [udos86/ng-dynamic-forms#672]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `5.4.3`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description
Thank you so much Udos86 for this perfect Library. In my form I need to implement input group. Could you please help me how to do that?

**Comment by liliom55** [comment]
![untitled](https://user-images.githubusercontent.com/16512043/35516831-ae35cbda-0504-11e8-8d3c-8c018eafe60d.png)

**Comment by Karamuto** [comment]
Did you try doing it by giving css-classes to the sorrounding containers?
For additional HTML you could use the <ng-template modelId="<inputId>"</ng-container>. Maybe you should try this and tell the author the result.

**Comment by liliom55** [comment]
@Karamuto 
Thanks for your response.I did it by hacking directly the css. I mean I added ::after Pseudo element. Actually it is Temporary  solution But it works fine.

**Comment by udos86** [comment]
@liliom55 Hi!

> Thank you so much Udos86 for this perfect Library. 

Thank you very much! Glad you like it.

> In my form I need to implement input group. Could you please help me how to do that?

Please use `prefix` and `suffix` properties:

```
new DynamicInputModel({
    
    id: "bootstrapInput",
    placeholder: "example input",
    prefix: "Prefix",
    suffix: "Suffix"
})
```

**Comment by liliom55** [comment]
@udos86 
Perfect! 
Got it. Thanks a lot.
