### ISSUE TITLE
How to add attribute to the components?

### ISSUE THREAD

**Issue by liliom55** [udos86/ng-dynamic-forms#673]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `5.4.3`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description
Could you please guide me how to add/set attribute to the components? for instance I want to set 

`<p-calendar  [monthNavigator]="true" [yearNavigator]="true" yearRange="2000:2030">`
or 
`<p-calendar  selectionMode="range" readonlyInput="true"></p-calendar>` but some attribute are not in model interface. How can I have them?

**Comment by udos86** [comment]
@liliom55 Hi!

Please use the `additional` property as described in the chapter on [Form Control Configuration](https://github.com/udos86/ng-dynamic-forms#form-control-configuration).

**Comment by liliom55** [comment]
@udos86 
Thank you so much for your support and your response.

**Comment by udos86** [comment]
@liliom55 No problemo
