### ISSUE TITLE
How to pass multiple custom validator parameters?

### ISSUE THREAD

**Issue by crhistianr** [udos86/ng-dynamic-forms#675]
## I'm submitting a
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.4`

[ ] Basic UI
[X] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'd like to create a custom validator that validates two field names and ensures their values match. I can see how to pass a single parameter https://github.com/udos86/ng-dynamic-forms/issues/321

but how would I pass in *multiple* parameters? Here is my validator function:

```
import { ValidatorFn, ValidationErrors, AbstractControl } from '@angular/forms';

// takes the name of two form controls and validates that values are the same
export function OcMatchFieldsValidator(firstFieldName: string, secondFieldName: string): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
        const firstField = control.get(firstFieldName);
        const secondField = control.get(secondFieldName);

        // only validate if both fields have been touched
        if (firstField.pristine || secondField.pristine) {
            return null;
        }
        if (firstField.value === secondField.value) {
            return null;
        }
        return { ocMatchFields: true };
    };
}
```

I know I could just modify my validator function to take in an array or something but I'm curious as well if ng-bootstrap has a way of doing this without resorting to that? 

Thanks!

**Comment by udos86** [comment]
@crhistianr Hi Crhistian!

> I know I could just modify my validator function to take in an array or something but I'm curious as well if ng-bootstrap has a way of doing this without resorting to that?

Yes, as of right now, your function would have to take an array...
