### ISSUE TITLE
README.md Form Layout section broken link

### ISSUE THREAD

**Issue by neil-coutinho** [udos86/ng-dynamic-forms#681]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[x] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
The link to [position identifiers ](http://ng2-dynamic-forms.udos86.de/docs/core/interfaces/_service_dynamic_form_layout_service_.dynamicformcontrollayoutconfig.html) in the [Form Layout](https://github.com/udos86/ng-dynamic-forms#form-layouts) section is broken (404)

**Comment by udos86** [comment]
@neil-coutinho Hi!

Thanks for reporting this broken link. I'll fix it!

**Comment by neil-coutinho** [comment]
Thank you :)
