### ISSUE TITLE
Grid Layout CSS not working in Angular CLI + NGX-Bootstrap

### ISSUE THREAD

**Issue by neil-coutinho** [udos86/ng-dynamic-forms#683]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.4`

[ ] Basic UI
[x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I am using the module in my Angular 5 project. I have constructed my FORM_MODEL and FORM_LAYOUT models respectively. However, the grid CSS does not seem to work. 

FORM_MODEL:

`MY_FORM_MODEL: DynamicFormControlModel[] = [

      new DynamicFormGroupModel({

        id: "addressLocation",
        group: [
            new DynamicInputModel({

                id: "zipCode",
                label: "Zip Code",
                placeholder: "ZIP"
            }),
            new DynamicInputModel({

                id: "state",
                label: "State",
                placeholder: "State"
            }),
            new DynamicInputModel({

                id: "city",
                label: "City",
                placeholder: "City"
            })
        ]
    }),`

FORM_LAYOUT:

`  MY_FORM_LAYOUT: DynamicFormLayout = {

      "addressLocation": {
          element: {
              control: "form-row"
          },

      },

      "zipCode": {
          element: {
              label: "col-form-label control-label",

          },
          grid: {
              host: "col-sm-2"
          }
      },

      "state": {
          element: {
              label: "col-form-label control-label",

          },
          grid: {
              host: "col-sm-4"
          }
      },

      "city": {
          element: {
              label: "col-form-label control-label",

          },
          grid: {
              host: "col-sm-6"
          }
      },

  }`

FORM HTML:
`<form [formGroup]="formGroup">
  <dynamic-bootstrap-form [group]="formGroup"
                          [model]="formModel"
                          [layout]="formLayout"></dynamic-bootstrap-form>
</form>`

The CSS classes are added correctly to the elements but the layout does not seem to render.

SCREENSHOTS:

![screen shot 2018-02-11 at 11 22 29 am](https://user-images.githubusercontent.com/33371261/36070385-4dac250a-0f1f-11e8-92ab-523a8d2d593d.png)
![screen shot 2018-02-11 at 11 22 45 am](https://user-images.githubusercontent.com/33371261/36070386-4dec114c-0f1f-11e8-9a9b-9100da652247.png)

Am I missing or doing something wrong? All 3 fields should be on the same line as be the grid classes @udos86

**Comment by neil-coutinho** [comment]
After much digging turns out a fieldset cannot have a display: flex property in chrome. Works in FF.
Any idea how I can change the fieldset to a div
[Why can't fieldset be flex containers?
](https://stackoverflow.com/questions/28078681/why-cant-fieldset-be-flex-containers)

**Comment by udos86** [comment]
@neil-coutinho Hi!

Yep, that's why I got rid of `fieldset` in other templates as there is no support for flexbox.

I'd recommend to make use of ng-bootstrap UI package.
