### ISSUE TITLE
Image Upload Control

### ISSUE THREAD

**Issue by asanchez128** [udos86/ng-dynamic-forms#684]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ X] Prime NG
</code></pre>

## Description
I would appreciate any guidance to create a control to upload images and to show them once the user has selected them. I know that 

> `<input type=file></input>`

 would do it. However, when it comes to displaying the selected image I am having issues to proceed. Also, I would like to control the amount of images that the user can upload. Any ideas? Thank you!

**Comment by udos86** [comment]
@asanchez128 Hi!

Starting with version `6.0.0` you can plugin custom form controls.
