### ISSUE TITLE
Form Control in tabular format

### ISSUE THREAD

**Issue by neil-coutinho** [udos86/ng-dynamic-forms#685]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm wanted to check if it is possible to display the input/drop-down boxes in table - cells. My json model is as follows:

`"nutrients": {
    "sugar": {
      "intake": null,
      "quantity": null
    },
    "fat": {
      "intake": null,
      "quantity": null
    },
    "energy": {
      "intake": null,
      "quantity": null
    }
  }`

Where Nutrients is the fieldset and we have each row for a nutrient with the intake and quantity as separate columns

Something like:

`<table>
      <tr>
           <td>Sugar</td>
           <td>intake input1</td>
           <td>quantity input</td>
      </tr>
      <tr>
           <td>Energy</td>
           <td>intake input1</td>
           <td>quantity input</td>
      </tr>
</table>`

Can this be done using custom templates?

**Comment by udos86** [comment]
@neil-coutinho Hi!

> Can this be done using custom templates?

I'm afraid, no.

There's no support for displaying form controls in a grid view using table markup.

**Comment by neil-coutinho** [comment]
Ok, Thank You

**Comment by AleksMeshkov** [comment]
Ah, what's a pity. But anyway you library is great!

**Comment by kovax** [comment]
@udos86 would it be possible to develop? I would be very motivated to do it. Actually we have implemented a similar functionality, but it is very messy code, need redesign. 

I think it is an alternative approach to Form Arrays, and it could work like the crud table demo of primeng:

https://primefaces.org/primeng/showcase/#/table/crud
