### ISSUE TITLE
Custom CSS-Style not rendered with Angular-Material

### ISSUE THREAD

**Issue by Flo12345** [udos86/ng-dynamic-forms#686]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I want to add a custom CSS-class to a form field, using the layout-option of <dynamic-material-form>. The problem is that the css-class gets inserted into the container-div correctly, but the desired style is not rendered (no background-color visible).

Model.ts:
<pre>
import {
  DynamicFormControlModel,
  DynamicFormGroupModel,
  DynamicInputModel,
  DynamicSelectModel
} from '@ng-dynamic-forms/core';

const usernameInput = new DynamicInputModel(
  {
    id: 'id_inputUsername',
    inputType: 'text',
    label: 'Username',
    minLength: 4,
    placeholder: 'Enter Username'
  });

const languageSelect = new DynamicSelectModel<string>({
  id: 'id_selectLanguage',
  label: 'Language',
  placeholder: '',
  hint: 'Enter preferred language',
  options: [
    {
      label: 'German',
      value: 'german'
    },
    {
      label: 'Hungarian',
      value: 'hungarian'
    },
    {
      label: 'English',
      value: 'english'
    },
    {
      label: 'Chinese',
      value: 'chinese'
    }
  ]
});

export const workplaceSetupFormModel: Array<DynamicFormControlModel> = [
  usernameInput,
  languageSelect
];
</pre>

Layout.ts:
<pre>
import {
  DynamicFormLayout
} from '@ng-dynamic-forms/core';

export const workplaceSetupFormLayout: DynamicFormLayout = {
  'id_inputUsername': {
    element: {
      container: 'inputUsername'
    }
  },
  "id_selectLanguage": {
    element: {
      container: "inputUsername"
    }
  }
}
</pre>

CSS-file:
<pre>
.inputUsername {
  background-color: rgba( 255, 255, 255, 0.7 );
}
</pre>

**Comment by udos86** [comment]
@Flo12345 Hi!

Are you providing your CSS class in a global or component-specific stylesheet?

Please remember [Shadow DOM styling rules](https://developers.google.com/web/fundamentals/web-components/shadowdom#styling).

**Comment by Flo12345** [comment]
Thank you udos86, I had it provided in a component-specific stylesheet. Providing it globally works.
