### ISSUE TITLE
[ui-bootstrap] [ui-ng-bootstrap] support bootstrap 4

### ISSUE THREAD

**Issue by paulsouche** [udos86/ng-dynamic-forms#687]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `latest`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[X] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

For example `input-group-addons` are no more in bootstrap 4. And I think there is more under the hood... I'm opening this issue because [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) supports it. By now, I have several workarounds to make it work.

Thanks anyway for the great job

**Comment by makkars** [comment]
Hi Paulsouche,

I am struggling to layout my formGroup using Material UI. 
It think you  have been using this library quite often, I wonder if you can help me here. 

I am creating a questionnaire set and always ending up with this alignment:
![screenshot from 2018-02-19 15-47-57](https://user-images.githubusercontent.com/18512943/36372836-4b1159c8-158c-11e8-824e-f745cc9eaf6c.png)

This is my simplest markup : 
![screenshot from 2018-02-19 15-49-24](https://user-images.githubusercontent.com/18512943/36372898-7eff182e-158c-11e8-82b0-667903a4eaab.png)

I am not sure who to use layout here. 
Please suggest.

**Comment by udos86** [comment]
@paulsouche Hi & sorry for the late reply!

I'm not really sure if fully understand the intention of your issue here. 

As of now I considered the NG Bootstrap UI package to be fully valid Bootstrap 4.

Of course, I'm always glad for suggestions on improvements.
