### ISSUE TITLE
Unable to place modelId in conditional expression inside ng-template

### ISSUE THREAD

**Issue by ryan1509** [udos86/ng-dynamic-forms#689]
`<dynamic-bootstrap-form-control *ngFor="let controlModel of formModel"
      [group]="loginForm"
      [model]="controlModel"
      [hasErrorMessaging]="controlModel.hasErrorMessages"
      #login
      >
      <ng-template modelId="{{controlModel.id}}" let-id="id" align="START">
        <span [style]="{'color':'red'}">{{id}}</span>
        <ng-container [ngSwitch]="contolModel.id">
            <span *ngSwitchCase="username" class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <span *ngSwitchCase="password" class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
        </ng-container>
      </ng-template>
      `</dynamic-bootstrap-form-control>``

**Comment by udos86** [comment]
closed as not library related
