### ISSUE TITLE
Can we define event specific to form elements in form model?

### ISSUE THREAD

**Issue by SudeshAK** [udos86/ng-dynamic-forms#692]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[X] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hi,
I have one question,is it possible to give events like change,blur while defining the form model.
Event specific to form elements?
like this:
<pre><code>
[
  {
    "type": "SELECT",
    "id": "degree",
    "label": "Degree",
    "event":[{
        "change":"custom_function()" //Like this
     }],
    "options": [
      {
        "label": "Bachelor of Arts (B.A.)",
        "value": "BA"
      }]
}
]
</code></pre>

**Comment by udos86** [comment]
@SudeshAK Hi!

There's a chapter on [Form Control Events](https://github.com/udos86/ng-dynamic-forms#form-control-events) covering all the details.

Events can only be be bound in the template.
