### ISSUE TITLE
Ionic - Module Parse Error

### ISSUE THREAD

**Issue by Scuttman** [udos86/ng-dynamic-forms#697]
## I'm submitting a

<pre><code>
[ X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[X] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I used the quickstart so I could quickly see the results. However, I get the following error:

Uncaught Error: Module parse failed: Unexpected token (8:26)
You may need an appropriate loader to handle this file type.
| } from "@ng-dynamic-forms/core";
| 
| export const MY_FORM_MODEL: DynamicFormControlModel[] = [
| 
|     new DynamicInputModel({...

I looked for an ionic example of the module implemented but can't find any or tutorials.
Please advise.

**Comment by udos86** [comment]
@Scuttman Hi!

I'll evaluate the latest Ionic versions and UI package for possible errors as soon as possible.

**Comment by udos86** [comment]
closed as of #907
