### ISSUE TITLE
Additional properties needed for describing labels independent from form controls

### ISSUE THREAD

**Issue by seanforyou23** [udos86/ng-dynamic-forms#700]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
[x] Custom UI template
</code></pre>

## Description

Hello, a common request that comes up when working with forms is the ability to hang helper text off of labels and form controls independently from one another. Explaining what a given label is/means can be very different from describing what types of values or format is expected for a given form control.

As a user of this library, the need for more granular control over how we can describe different aspects of our forms has come up. The request would be to add new properties to facilitate decorating forms with placeholder text, tooltip text for labels, tooltip text for form controls, in addition to the existing "description" property which displays text below a form control.

Having more than a single description property for helper text would allow for more flexibility in the presentation of the model driven forms. If I may, I'd like to recommend adding something like "labelTooltip" or "labelDescription" as well as "controlTooltip" or "controlDescription" in addition to the existing "description" property that already exist. So instead of only having a single option for providing helper text to various aspects of the form, users could take advantage of whichever property fits their needs/designs the best.

I've taken a stab at making this happen in [this PR](https://github.com/udos86/ng-dynamic-forms/pull/699/)

**Comment by kahboom** [comment]
@udos86 - Any chance we can have this reviewed? We're working on a demo for Red Hat Summit and want to know if we can get this merged in time for the end of the sprint mid-next week, as it will be demoed in front of 6k+ people.

We could just use @seanforyou23 's fork in the project and check in the whole thing, but since other people will be using it as well it would be awesome if we could use it directly from the upstream repo. Thanks and great lib, keep up the work! 👍

**Comment by udos86** [comment]
@seanforyou23 @kahboom Hi!

Thanks for this proposal!

There's a little issue with the PR itself 'cause it does not fully follow the CONTRIBUTING guide.

Could please branch off `development` and merge into `udos86:development`? I could also cherry-pick your commit but you would not appear as a contributor here then.

**Comment by seanforyou23** [comment]
Thank you!!
