### ISSUE TITLE
Form Security

### ISSUE THREAD

**Issue by stekontar** [udos86/ng-dynamic-forms#701]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hello @udos86 !

Does library supports DomSanitizer ?
(
https://angular.io/api/platform-browser/DomSanitizer,
https://angular.io/guide/security
)

Currently I am trying to "secure" my forms,
I would like to forbid user from typing/input any malicious code e.g javascript:: alert("I hacked you")

is there any way to apply sanitizer globally in order to check every field.

Regards,
Stekontar

**Comment by Karamuto** [comment]
As I remember angular 2+ applications are using the DOMSanitizer by default.

Have you tried inserting this kind of code?

**Comment by stekontar** [comment]
Hi again!,

I did some first level tests but seems that everything is passing through.
Maybe I am making something wrong as I don't have seen anything related.

Any guidance/information are welcome.

Attached you can see a screenshot with a sample form.
Regards, 
S.
![page](https://user-images.githubusercontent.com/8927706/37716645-a7f2034c-2d27-11e8-935c-55422b1f867f.png)

**Comment by Karamuto** [comment]
@stekontar 
Could you maybe provide the code from your example?
You example on Stackblitz or Plnkr would be event better.

**Comment by about-code** [comment]
@stekontar  Could it be that you mix up input *validation* with DOM *sanitization*. You might see from Angular's DomSanitizer API that sanitization measures vary depending upon where a value (e.g. a value read from a database) will be inserted into DOM (HTML body, HTML attribute, etc.). This is usually hard to guess at the time when you write a form value into a database. It can only be determined by the target application reading it.

So Angular by default sanitizes values before they are inserted into DOM. Though, it will not sanitize user-provided form data before its being written to a form model or sent to a server. It's the job of the server to handle form data properly and to apply input validation. The stricter it is about allowed characters, length etc. the better it is. Good server-side input validation is usually even more important than sanitization (though its clearly not about an either or).

Assume you have two applications accessing the same database and one of it doesn't properly sanitize. Then one of the systems may be vulnerable to persistent XSS attacks. With server-side input validation you introduce a higher level of security for *all* applications reading the database. 

You might still decide to sanitize form input values before sending them to the server. You might also apply sanitization manually as part of your form validation logic. If you find that the raw value differs from the sanitized value, then you may consider the raw value to be invalid. But such a strategy is in the application domain and might not be a good default for a general purpose form library.

**Comment by stekontar** [comment]
@about-code  
Thank you very much for your detail answer. 
As a standard operation server-side would sanittze the posted data. Thats the fact.
I was thinking that validating the form input and inform user with a validation message would provide an extra security. 
I would make a research about good-practice/performance of this and I would come back.

Regards,
S.

**Comment by about-code** [comment]
>  I would make a research about good-practice/performance of this and I would come back.

If you find anything which contradicts my ealier post, I'd be open to hear about it. Just can learn from it.

> I was thinking that validating the form input and inform user with a validation message would provide an extra security.

If you're doing servers-side validation/sanitization then I'd say you're doing things right and Angular cares for the rest (to the extent they guarantee within their official docs). Anything an attacker may be able to do by typing a <script>-Tag into a form is hacking him- or herself. Client-side sanitization may reduce the costs which untalented script kiddies make you pay by sending Bad Requests to your server. But you will likely stop them by good validation rules based on regular expressions for example. Normal users will send you the mass of harmless bad requests and client-side validation can effectively reduce server load for these kind of users.
