### ISSUE TITLE
Adjust control vertical space within ngtemplate

### ISSUE THREAD

**Issue by stevehoper** [udos86/ng-dynamic-forms#705]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi,
Is there a way to change space between controls within ng-template?

Thanks

**Comment by Karamuto** [comment]
What have you tried so far?

With CSS would be my first try.

**Comment by udos86** [comment]
@stevehoper 

Sorry for the very late reply - I was focusing on `6.0.0` major release.

As @Karamuto  pointed out, please use CSS for this.
