### ISSUE TITLE
Add support to control the 'required' property of a form control via 'relation'.

### ISSUE THREAD

**Issue by gashcrumb** [udos86/ng-dynamic-forms#708]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.x`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>
custom UI module

## Description

It'd be awesome if the `relation` property for a form input could also affect the `required` attribute for a form control, for example let's say I have a checkbox that enables/disables a text input, not only do I want to enable it but I want it to be required.

Or another option is, if I mark a field as required, but it's disabled because of the value of another control it'd be cool if the required property could be removed.

**Comment by udos86** [comment]
_will be finally available in `8.0.0`_
