### ISSUE TITLE
Fix config.value to allow 0 numeric value

### ISSUE THREAD

**Issue by AndreaPaciolla** [udos86/ng-dynamic-forms#710]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[X] Prime NG
</code></pre>

## Description

When `config.value` is equals to 0, condition `config.value || null` got evaluated as null so no 0 value can be passed.
The fix allows 0 to be evaluated correctly.

**Comment by udos86** [comment]
@AndreaPaciolla Thanks!

Your PR has been merged and will be released in `5.4.6`.
