### ISSUE TITLE
adding text-mask parameters

### ISSUE THREAD

**Issue by Berrchek** [udos86/ng-dynamic-forms#714]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

It would be helpful to be able to specify some additional text-mask parameters, like placeholderChar, guide,... are there any plans to support this in the future?

https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md

**Comment by Karamuto** [comment]
+1
Maybe the 'partial' object with logic could be replaced with a full control version.
But this would result in a breaking change...

As alternative we use another attribute whose name is 'textMask' which will have a higher priority then the 'mask' attribute.

**Comment by udos86** [comment]
@Berrchek Hi!

Sorry for the late reply - I was busy providing new major release `6.0.0`

Thanks for this proposal. I'll examine it and will take it under consideration.

**Comment by wdunn001** [comment]
I tried to make a quick fix for this it doesn't like the function I added to the textmask directive. 

`typeof model.mask === 'object' && !Array.isArray(model.mask) ? model.mask : {mask: (model.mask || false), showMask: model.mask && !(model.placeholder)}`

Parser Error: Unexpected token 'model' at column 8 in [typeof model.mask === 'object' && !Array.isArray(model.mask) ? model.mask : {mask: (model.mask || false), showMask: model.mask && !(model.placeholder)}] in ng:/test/ui-basic/src/input/dynamic-basic-input.component.html@22:11 ("
	           [spellcheck]="model.spellCheck"
	           [tabindex]="model.tabIndex"
	           [ERROR ->][textMask]="typeof model.mask === 'object' && !Array.isArray(model.mask) ? model.mask : {mask: (model"): ng:/test/ui-basic/src/input/dynamic-basic-input.component.html@22:11


I really do think this is a simple fix.

**Comment by udos86** [comment]
@wdunn001 Thanks for your contribution!

Please give some days to evaluate this.

**Comment by guilhermehtk** [comment]
Up, i really need this and a simple `guide: false` will help me a lot because the angular2-text-mask has appending an underline on my masked input values and disabling guide fix this.

**Comment by 003marek** [comment]
Hi. Any update on this one?

**Comment by udos86** [comment]
closed as of #1140
