### ISSUE TITLE
Custom Controls simple example

### ISSUE THREAD

**Issue by blowsie** [udos86/ng-dynamic-forms#716]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[X] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

The read me says the following

> Does NG Dynamic Forms support custom form controls?
> 
> No, not out of the box. You'd have to create your own UI template / package in order to achieve this.

---

Could you please provide a simple example to show how this would be done?

I've written dozens of formly custom controls in the past, I'm just not sure where to start here. Thanks.

**Comment by udos86** [comment]
@blowsie Hi!

To make a long story short: There'll be support for custom form controls in next major version.

see #660

**Comment by blowsie** [comment]
Thanks @udos86  I didn't see this open ticket.
