### ISSUE TITLE
No forms displayed in ionic 3

### ISSUE THREAD

**Issue by atrautner** [udos86/ng-dynamic-forms#718]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I just don't get it work and don't know why.

Im declaring the DynamicFormControlModel[] as it is in the quickstart and then use the createFormGroup of the DynamicFormService.
It seems to generate everything as it should be, but in the end there is nothing displayed.

current html:
<code>
    <form [formGroup]="form">
        <dynamic-ionic-form [group]="form" [model]="model"></dynamic-ionic-form>
    </form>
</code>
I've also tried with dynamic-ionic-form-control version, but didn't work either.

Result in elements view:
> `<form novalidate ng-reflect-form="[object Object]" class="ng-untouched ng-pristine ng-valid">`
>         `    <dynamic-ionic-form></dynamic-ionic-form>`
> `</form>`

While the console.log of the model shows:
> (3) [DynamicInputModel, DynamicRadioGroupModel, DynamicCheckboxModel]
> 0: DynamicInputModel {parent: null, asyncValidators: null, errorMessages: null, hidden: false, id: "sampleInput", …}
> 1: DynamicRadioGroupModel {parent: null, asyncValidators: null, errorMessages: null, hidden: false, id: "sampleRadioGroup", …}
> 2: DynamicCheckboxModel {parent: null, asyncValidators: null, errorMessages: null, hidden: false, id: "sampleCheckbox", …}
> length: 3
> __proto__: Array(0)

And the console.log of the formgroup shows:
> FormGroup {validator: null, asyncValidator: null, _onCollectionChange: ƒ, pristine: true, touched: false, …}
> asyncValidator: null
> controls: {sampleInput: FormControl, sampleRadioGroup: FormControl, sampleCheckbox: FormControl}
> dirty: (...)
> disabled: (...)
> enabled: (...)
> errors: null
> invalid: (...)
> parent: (...)
> pending: (...)
> pristine: true
> root: (...)
> status: "VALID"
> statusChanges: EventEmitter {_isScalar: false, observers: Array(0), closed: false, isStopped: false, hasError: false, …}
> touched: false
> untouched: (...)
> updateOn: (...)
> valid: (...)
> validator: null
> value: {sampleInput: null, sampleRadioGroup: "option-3", sampleCheckbox: false}
> valueChanges: EventEmitter {_isScalar: false, observers: Array(0), closed: false, isStopped: false, hasError: false, …}
> _onCollectionChange: ƒ ()
> _onDisabledChange: []
> __proto__: AbstractControl

I'm not sure if it's something to do with [#697](https://github.com/udos86/ng-dynamic-forms/issues/697)!?
Or maybe it's a dumb mistake that I made and which I can't see right now.

Help appreciated.

**Comment by atrautner** [comment]
solved by removing lazy loading

**Comment by blaforet** [comment]
Hi @atrautner 
I was having the same issue. Let just say it took me a while before founding the solutions. #728 
Hope it will help you
