### ISSUE TITLE
dynamic Json problem

### ISSUE THREAD

**Issue by bobingham** [udos86/ng-dynamic-forms#719]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
    "@ng-dynamic-forms/core": "^5.1.0",
    "@ng-dynamic-forms/ui-ionic": "^5.1.0"

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x ] Ionic UI - 3.9.2
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi,
Can I first say thanks for a great library.  I am using it with Ionic and have managed to get my solution working using dynamic models.  My app has a list of actions and each action may result in a different form.  The actions are supplied from the server and a hard-coded form name allows me to select the relevant dynamic model.  This is great but the next step of the project is for me to build the forms dynamically on the server and push the to the app as json.  To date I have been unable to do so.
My initialisation code is as follows:

```
ngOnInit() {
      this.formModel = this.formService.fromJSON(this.action.form.serializedJson);
      this.formGroup = this.formService.createFormGroup(this.formModel);
      this.isLoaded = true;
}
```

I have simplified my serializedJson as follows:
`[{"type":"INPUT","id":"sampleInput","label":"Sample Input","maxLength":42,"placeholder":"Sample input"}]`
The json is parsed at `DynamicFormService.prototype.fromJSON` but fails at `rawFormModel.forEach(function (model)` where `model` is undefined:
```
    DynamicFormService.prototype.fromJSON = /**
     * @param {?} json
     * @return {?}
     */
    function (json) {
        var _this = this;
        var /** @type {?} */ rawFormModel = typeof json === "string" ? JSON.parse(json, Utils.parseJSONReviver) : json, /** @type {?} */
        formModel = [];
        rawFormModel.forEach(function (model) {
```
Consequently no form is passed back and no form is rendered.
I'm at the early stage of implementing dynamic forms from json so it's not a show-stopper yet but eventually it will be.

> Do you have any pointers?

**Comment by udos86** [comment]
@bobingham Hi! Sorry for the late reply! 

Hints were already given to you [here](https://github.com/udos86/ng-dynamic-forms/issues/731)...
