### ISSUE TITLE
How to apply item styles (such as item-end) to ionic items?

### ISSUE THREAD

**Issue by scornflake** [udos86/ng-dynamic-forms#721]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Item placement in Ionic is done using attributes, e.g: <ion-item item-end>Foo</ion-item>.
It doesn't look like Layouts support this... am I right there or missing something obvious?

**Comment by udos86** [comment]
@scornflake Hi!

Please excuse the late reply. I was working on new major release `6.0.0`.

> It doesn't look like Layouts support this... am I right there or missing something obvious?

You're not missing anything here. Layouts can only be customized via CSS.
