### ISSUE TITLE
offlabel and onlabel not working on ionic UI

### ISSUE THREAD

**Issue by dasakigr** [udos86/ng-dynamic-forms#722]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[X] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

With <strong>DynamicSwitchModel</strong> i try to use <strong>onlabel</strong> and <strong>offlabel</strong> in Ionic UI but it doesn't work. 
I try this:
new DynamicSwitchModel(
        {
            // hint: "Just a hint",
            id: "switchSlopeHeight",
            offLabel : "Calc with min and max Height",
            onLabel:   "Calc with Slope",
            value : true
        },

I search in ui-ionic source code but nothing ....

**Comment by udos86** [comment]
@dasakigr Hi!

Sorry for the late reply - I was concentrating on new `6.0.0` major release.

I'm afraid, there's no support in Ionic for on and off labels. 

That's why these properties are simply ignored when using Ionic UI package

**Comment by dasakigr** [comment]
Thank's for your reply.
I have found a solution for my problem with Subscriptions. 
Have a nice day
