### ISSUE TITLE
PrimeNg Datepicker to include timepicker also

### ISSUE THREAD

**Issue by BalainGitHub** [udos86/ng-dynamic-forms#723]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ x] Prime NG
</code></pre>

## Description
Hi, Thanks a lot for providing such a wonderful package.  I am using ng-dynamic-forms in a couple of my projects and found it very useful. I have a requirement to display TIMEPICKER along with the DATEPICKER. While PrimeNg supports such a display in its p-calendar component with an input "showTime", this particular input is missing in ng-dynamic-forms' primeng component.
It would be really helpful if you can include this particular input in ng-dynamic-forms.

Thanks in advance.
Bala

**Comment by udos86** [comment]
@BalainGitHub Hi!

Sorry for the late reply - I was working hard on `6.0.0` major release.

I'll try to deliver this with the next patch version!

**Comment by BalainGitHub** [comment]
Hi , 

Thanks a lot for the update. Right now am able to use timepicker along with datepicker.
