### ISSUE TITLE
DynamicSelectModel not updating its UI in PrimeNG

### ISSUE THREAD

**Issue by FDN73** [udos86/ng-dynamic-forms#726]
## I'm submitting a

<pre><code>
[ X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.0` beta

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[X ] Prime NG
</code></pre>

## Description

I am trying to update programmatically a drop down:
let inputModel = this.formService.findById("userStatus", this.formModel) as DynamicSelectModel<UserStateDO>;
              inputModel.valueUpdates.next(rtp.userToUpdate.userStatus);
The value is updated but the UI shows the old value.

**Comment by FDN73** [comment]
Probably caused by https://github.com/primefaces/primeng/issues/877

**Comment by udos86** [comment]
@FDN73 Hi!

Thanks for reporting this. I'll need to have a look if this is related to this project or Prime NG itself.
