### ISSUE TITLE
Display issue on IONIC

### ISSUE THREAD

**Issue by blaforet** [udos86/ng-dynamic-forms#728]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.0-beta`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[X] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
When using the package in a project where there is ionic Lazy Loading the dynamic form does not display.
I've created 2 new ionic projects.
**1**: I created a blank project, I did the install and setup like mention in the documentation.
Run the project and the dynamic form does display 
**2**: I create a project "super", starting project with pre-built pages, did the same installation, ran the project. 
- The first issue, I need to add  schemas: [CUSTOM_ELEMENTS_SCHEMA]  or 
schemas: [NO_ERRORS_SCHEMA] in the module of the component pages otherwise the page does not load and create an error. 
- Now with that, the error is gone but does not display anything.
- The "formGroup" did get created correctly. 

There was another ticket whit the similar issue #718 the person removed the lazy loading.
But since I already have an ongoing project and want to also use it has PWA, I cannot do this. 

Any suggestion?
Thank you

**Comment by blaforet** [comment]
I even try with a previous version of ng-dynamic-forms 5.4.7, and getting the same issue.

**Comment by blaforet** [comment]
After many tryouts and frustration. I've read more about the **Ionic Lazy Loading.** 
Finally found the solution, of course, we need to import 
  ReactiveFormsModule,
  DynamicFormsCoreModule.forRoot(), 
  DynamicFormsBootstrapUIModule, 

but not in the app.module.ts  but in each NgModule of your components that will use the ng-dynamic-forms.
Example: let say your component is myComponent.ts  
Then you will need to add the import in the myComponent.module.ts

Ticket can be close

**Comment by udos86** [comment]
@blaforet Hi!

Thanks for giving some insight to this!

**Comment by vicebtx** [comment]
Hi @blaforet .
Can you share working template along with an example?
I have been strugling with this for a while.
Documentationn is not very helppful

**Comment by blaforet** [comment]
Hi @vicebtx 
The example provided by udo86, works great. It's just that if you are using Lazy Loading, you need to import ReactiveFormsModule,
DynamicFormsCoreModule.forRoot(),
DynamicFormsBootstrapUIModule,  in each modules where you will use dynamic forms

**Comment by vicebtx** [comment]
I did that already.

But i just get the form values to print. The ui is not being rendered.
here is what i have:

This is just a test componet.

```javascript
import { Component } from '@angular/core';
import { NavController, IonicPage } from 'ionic-angular';
import { FormGroup } from "@angular/forms";
import { DynamicFormService, DynamicFormControlModel, DynamicFormLayout } from "@ng-dynamic-forms/core";

import { FORM_MODEL } from "./login.model";


@IonicPage()
@Component({
  selector: 'page-login',
  templateUrl: 'login.html'
})
export class LoginPage {

  formModel: DynamicFormControlModel[] = FORM_MODEL;
  formGroup: FormGroup;


  constructor(
    public navCtrl: NavController,
    private formService: DynamicFormService
  ) {
    this.formGroup = this.formService.createFormGroup(this.formModel);
  }

} 
```
This is my data model (login.model.ts):

```javascript
import {
    DynamicCheckboxModel,
    DynamicDatePickerModel,
    DynamicFormGroupModel,
    DynamicInputModel,
    DynamicRadioGroupModel,
    DynamicSelectModel,
    DynamicSwitchModel,
    DynamicTextAreaModel
} from "@ng-dynamic-forms/core";

export const FORM_MODEL = [
  

    new DynamicFormGroupModel({

        id: "stay",
        group: [
            new DynamicDatePickerModel({

                id: "arrivalDate",
                inline: false,
                placeholder: "Date of Arrival"
            }),

            new DynamicDatePickerModel({
                id: "departureDate",
                inline: false,
                placeholder: "Date of Departure"
            })
        ]
    })
]
```

Here's the module

```typescript
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { DynamicFormsModule } from '../dynamic-forms/dynamicforms.module'
import { LoginPage } from './login';


@NgModule({
  declarations: [
    LoginPage,
  ],
  imports: [
    DynamicFormsModule,
    IonicPageModule.forChild(LoginPage)
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ]
})
export class LoginPageModule { }
```

Here's the  module i have created to share among components that will use dynamic forms:

```javascript
import { NgModule} from '@angular/core';

import { DynamicFormsCoreModule, DYNAMIC_VALIDATORS, Validator, ValidatorFactory } from "@ng-dynamic-forms/core";
import { DynamicFormsIonicUIModule } from "@ng-dynamic-forms/ui-ionic";
import { ReactiveFormsModule,  NG_VALIDATORS, NG_ASYNC_VALIDATORS } from '@angular/forms';
import {
    customValidator,
    customDateRangeValidator,
    customForbiddenValidator,
    customAsyncFormGroupValidator
} from "../../app/app.validators";

@NgModule({

  imports: [ 
    ReactiveFormsModule,
    DynamicFormsCoreModule.forRoot(), 
    DynamicFormsIonicUIModule
  ],
  providers:[
    {
        provide: NG_VALIDATORS,
        useValue: customValidator,
        multi: true
    },
    {
        provide: NG_VALIDATORS,
        useValue: customDateRangeValidator,
        multi: true
    },
    {
        provide: NG_ASYNC_VALIDATORS,
        useValue: customAsyncFormGroupValidator,
        multi: true
    },
    {
        provide: DYNAMIC_VALIDATORS,
        useValue: new Map<string, Validator | ValidatorFactory>([
            ["customValidator", customValidator],
            ["customDateRangeValidator", customDateRangeValidator],
            ["customForbiddenValidator", customForbiddenValidator],
            ["customAsyncFormGroupValidator", customAsyncFormGroupValidator]
        ])
    }
  ]
})
export class DynamicFormsModule { }
```

And finally my Template:

```html
<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>Home</ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <form [formGroup]="formGroup">

    <dynamic-ionic-form-control *ngFor="let controlModel of formModel"
                                [group]="formGroup"
                                [model]="controlModel"></dynamic-ionic-form-control>
</form>
  <pre>{{formGroup.value | json}}</pre>
</ion-content>
```

All i get to "Render" is the formGroup.value.

What am I missing or doing wrong?

**Comment by blaforet** [comment]
@vicebtx  i see that it's an Ionic Project.  Unfortunately for me it was an Angular 4 project with Material framework.  In the browser console i there any error when load the login page?

**Comment by vicebtx** [comment]
@blaforet 
I posted here because it was an Ionic issue.
I have no errors whatsoever.
Everything is compiling fine, it just that it doesn't render anything.

@udos86  do you know if i'm missing anything?

**Comment by blaforet** [comment]
Hi, Sorry yes you are right. At first i was using Ionic but got fed up with all the issues that i dump Ionic 3 and develop only with Angular and wait for Ionic 4.... but it seem that Ionic 4 still has cache issues.

I think yo have an error in your HTML template when looking at the tutorial if you use DynamicFormGroupModel, the html should be like this <form [formGroup]="formGroup">

    <dynamic-bootstrap-form [group]="formGroup"
                            [model]="formModel"></dynamic-bootstrap-form>
                            
</form>

If i'm not mistaking if you use *ngFor="let controlModel of formModel"  is if you don't imbed the controls in a  DynamicFormGroupModel,  [see here ](https://github.com/udos86/ng-dynamic-forms#form-groups)

**Comment by blaforet** [comment]
@vicebtx, Hi did my previous comment helped you?
https://github.com/udos86/ng-dynamic-forms/issues/728#issuecomment-416004085
