### ISSUE TITLE
Question about persistance and use of JSON

### ISSUE THREAD

**Issue by abnersouza** [udos86/ng-dynamic-forms#731]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `Lastest`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I'm trying to find a lib where i can use Json as the format to create the form, I like the way you guys created the ng-dynamic form to accept JSON format, but my question is in how complex can i make the Json. I want to know if the following is possible using JSON.
- Add masks // if yes how
- Add the bootstrap grid information grid   control: { "col-sm-9", label: "col-sm-3" } // if yes how
- How would i persist the data inside the control, and how can i set the data back after loading the form structure?

Thanks

**Comment by verynear2** [comment]
Following. I also need to generate a form dynamically from a JSON. I see how to import and export a FormsModel as JSON - but how to dynamically generate a form based on fields and values in a custom JSON ?

**Comment by bobingham** [comment]
I have asked exactly the same question with a code example over a month ago:
#https://github.com/udos86/ng-dynamic-forms/issues/719

**Comment by Karamuto** [comment]
Hello @abnersouza ,

- If you mean text-masks see here: https://github.com/udos86/ng-dynamic-forms#text-masks
- For bootstrap layout classes you can use the 'layout' attribute:
` 'controlId': { host: { control: 'col-5'}  } `
  should do the trick.
- The controls are always in sync with the 'FormGroup' you create, so to get all values with the corresponding id, you can just grab them here, the group also allows you to reset. If you need all the information used, then you can use the 'toJson' method on any of the formModels.

**Comment by udos86** [comment]
@abnersouza @bobingham 

Sorry for coming back to this so late but I was working hard on sixth major release.

@Karamuto already gave you the correct hints! 

I can't thank you enough for helping out here and supporting this project!

**Comment by abnersouza** [comment]
@udos86 No bother, @Karamuto tks a lot.
