### ISSUE TITLE
DynamicTextAreaModel scrolled to bottom

### ISSUE THREAD

**Issue by cedrickGuerin** [udos86/ng-dynamic-forms#732]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi udos86.

How can I check if a DynamicTextAreaModel is scrolled to bottom ?
I don't find the event and the attribute for this in the model after doing a findById.

Thank you 

Regards,

**Comment by udos86** [comment]
@cedrickGuerin Hi!

There's no support for binding to scroll events as this is out of scope of this library.

You'd need to do this [on your own](https://stackoverflow.com/questions/19626483/detect-when-textarea-is-scrolled-to-bottom?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)...
