### ISSUE TITLE
Binding to specific events on form elements

### ISSUE THREAD

**Issue by youssef-ghrib** [udos86/ng-dynamic-forms#734]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I wish to use event binding on mat-select to trigger a method upon selectionChange. How can I do that?

**Comment by udos86** [comment]
@youssef-ghrib Hi!

Just make use of the `matEvent` output to listen to any events specific to Material controls (see [docs](https://github.com/udos86/ng-dynamic-forms#form-control-events)).
