### ISSUE TITLE
How to populate an edit form with FormArray?

### ISSUE THREAD

**Issue by Sl1MBoy** [udos86/ng-dynamic-forms#741]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.7`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi!

I'm using the patchValue method of FormGroup to populate my edit form and it is working fine unless there is a FormArray on it. Only the first group of the array is displayed. The problem is that the DynamicFormArrayModel is not updated and have only one group while the FormArray have multiple. What is the proper way to populate an edit form to work with arrays as well?

Thanks

**Comment by Karamuto** [comment]
Hello @Sl1MBoy ,
in a 'DynamicFormArrayModel' you have an array of formControls for every index.,So to get this Array you need to use its 'get(index)' method to get the corresponding 'DynamicFormArrayGroupModel'. This also contains a 'get(index)' method to get the corresponding 'DynamicFormControlModel's.

To have the same functionality, I would suggest you wrap the inner form model into another formgroup.

**Comment by udos86** [comment]
@Karamuto Kudos for helping out!
