### ISSUE TITLE
Issue with DynamicCheckboxGroupModel's value 

### ISSUE THREAD

**Issue by atarix83** [udos86/ng-dynamic-forms#744]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi,
I'd report an issue when using a `DynamicCheckboxGroupModel` in a form.
Indeed the value of the `DynamicCheckboxModel` belonging to the group, doesn't reflect the state checked/unchecked of the form's control. While the formGroup's value is correct.

You can view the problem also in the [demo](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/ng-bootstrap-sample-form), selecting an option in the extras form's field and watching the events generated in the browser's console

**Comment by udos86** [comment]
@atarix83 Thank you very much for reporting this!

I'll deliver a patch as soon as possible.
