### ISSUE TITLE
Creating an empty form and adding different components type to it

### ISSUE THREAD

**Issue by guilhermefm7** [udos86/ng-dynamic-forms#747]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Is there a way to add different component types inside a form, which does not have a defined model? Just creating an empty form model and adding components to it. Because I have been trying to create a dynamic form, where users create questions (like Google Forms). But I am facing a problem creating a list with some components inside (When I have added a new component to the list, the olders got lost their reference).

Example creating an inputText:

 addItem() {
    this.i=this.i+1;
    this.array.push(this.createInput(this.i.toString()));
    this.formModel = this.array;
    this.formGroup = this.formService.createFormGroup(this.formModel);  
}

createInput(counter:string):DynamicInputModel{
    return  new DynamicInputModel({
        id: "myInput" + counter,
        label: "My Input"
    })
  }

If I create only one input, it looks fine, but at the time I create another one, the first one got lost its reference

**Comment by Karamuto** [comment]
Hello @guilhermefm7,
you should use the libraries 'DynamicFormService' to manipulate the form Model, as there the FormGroup is also kept in sync with the changes.

For your case maybe the 'insertFormGroupControl' is sufficient. For more information you could look at the source here: https://github.com/udos86/ng-dynamic-forms/blob/master/packages/core/src/service/dynamic-form.service.ts

**Comment by guilhermefm7** [comment]
Hello @Karamuto.

Ok, I got it.

Thank you
