### ISSUE TITLE
ui-boostrap input group addon classes use incorrect css class names

### ISSUE THREAD

**Issue by philrowan-mtb** [udos86/ng-dynamic-forms#748]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
```
"@ng-dynamic-forms/core": {
      "version": "6.0.2"
    },
    "@ng-dynamic-forms/ui-bootstrap": {
      "version": "6.0.2"
    }

// some text omitted for brevity
```
[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
bootstrap-ui appears to be using beta classes for input addons. 
`<div class="input-group-addon">My Addon</div>`
These should be updated to `input-group-prepend` for prefix and `input-group-append` for suffix.

http://getbootstrap.com/docs/4.1/components/input-group/

**Comment by udos86** [comment]
@philrowan-mtb Hi!

`ui-bootstrap` package only supports Bootstrap 3.

If you'd like to use Bootstrap 4 please switch to `ui-ng-bootstrap` package.
