### ISSUE TITLE
Form Arrays with JSON based model

### ISSUE THREAD

**Issue by verynear2** [udos86/ng-dynamic-forms#749]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
<code> import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { HttpClient, HttpResponse } from '@angular/common/http';
import { FormGroup } from '@angular/forms';
import { DynamicFormService, DynamicFormControlModel, DynamicFormLayout } from '@ng-dynamic-forms/core';
import { NG_BOOTSTRAP_SAMPLE_FORM_MODEL } from '../../leasing/sampleformcomponent/sampleform.model';
import { NG_BOOTSTRAP_SAMPLE_FORM_LAYOUT } from '../../leasing/sampleformcomponent/sampleform.layout';

@Component({
    moduleId: module.id,
    selector: 'app-dynamic-ng-bootstrap-sample-form',
    styleUrls: [],
    templateUrl: './sampleformcomponent.component.html',
    encapsulation: ViewEncapsulation.None
})
export class NGBootstrapSampleFormComponent implements OnInit {

    formModel: DynamicFormControlModel[];
    formGroup: FormGroup;
    formLayout: DynamicFormLayout = NG_BOOTSTRAP_SAMPLE_FORM_LAYOUT;

    constructor(private http: HttpClient, private formService: DynamicFormService) {}

    ngOnInit() {
        this.http.get<object[]>('./assets/my-dynamic-form.model.json').subscribe(formModelJson => {
                this.formModel = this.formService.fromJSON(formModelJson);
                this.formGroup = this.formService.createFormGroup(this.formModel);
            });
        // this.formGroup = this.formService.createFormGroup(this.formModel);
    }
</code>

I'm importing a JSON to generate my formModel. Works fine with just formGroups and the fields. Attempting to set up the formArray's like this:
[  
   {  
      "type":"ARRAY",
      "id":"Property_Information",
      "initialCount: 5,
      "group":[  
         {  
            "label":"Applicant",
            "id":"applicant",
            "type":"INPUT",
         },
         {  
            "label":"BirthDate",
            "id":"birth_date",
            "type":"INPUT",
         }]
     }
]

Nothing renders, not even the other fields. I get the error <code>TypeError: Cannot read property 'forEach' of undefined</code>

Do I need to add this to my component? - <code>this.formArrayControl = this.formGroup.get("myFormArray") as FormArray; 
    this.formArrayModel = this.formService.findById("myFormArray", this.formModel) as DynamicFormArrayModel;</code>

If so, how should the JSON be arranged to work with that setup?

Thank you!

**Comment by Karamuto** [comment]
Hello @verynear2 ,

FormArray has no property 'group' instead you have a property 'groups' which contains the already generated FormGroup's inside the FormArray, as well as a 'groupPrototype' property whcih results in the 'groupFactory' function.

So I think 'groupPrototype' should be the place for your group / template definition.
