### ISSUE TITLE
use of tabs

### ISSUE THREAD

**Issue by hvdl73** [udos86/ng-dynamic-forms#750]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hi, great work... what would be the best approach to use tabs. I like to group some fields of the form an put them in a tab... 

Thanks in advance.

Hans

**Comment by udos86** [comment]
@hvdl73 Hi Hans!

My advice would be to split your form into multiple ones (one for each tab). 

With this approach you should be compatible to any tab components out there you'd like to make use of.
