### ISSUE TITLE
Add UI Clarity Design System

### ISSUE THREAD

**Issue by KANekT** [udos86/ng-dynamic-forms#754]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## Description

Add https://github.com/vmware/clarity for UI

**Comment by udos86** [comment]
@KANekT Hi!

Nice proposal. I'll take it under consideration.

**Comment by RichardBosworth** [comment]
I was going to start working on this for a personal project. Happy to share.

**Comment by udos86** [comment]
@RichardBosworth Great! 

You're always welcome to contribute.

**Comment by udos86** [comment]
closed due to inactivity
