### ISSUE TITLE
Group validation in parent / grantparent

### ISSUE THREAD

**Issue by stekontar** [udos86/ng-dynamic-forms#755]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.3`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

`
export const EXAMPLE_MODEL = [

    new DynamicFormGroupModel({

        id: "grandparentFormGroup1",
        legend: "Grant Parent Form Group 1",
        group: [

            new DynamicFormGroupModel({

                id: "parentFormGroup1",
                legend: "Parent Form Group 1",
                validator: {
                    required: null
                },
                errorMessages: {
                    required: "error on {{ id }}"
                },
                group: [

                    new DynamicInputModel(
                        {
                            id: "testInput",
                            label: "testInput1",
                            validators: {
                                required: null,
                                maxLength: 5
                            },
                            errorMessages: {
                                required: "{{ label }} is required",
                                maxLength: "Max character count is 5"
                            }
                        }
                    )
                ]
            }),

            new DynamicFormGroupModel({

                id: "parentFormGroup2",
                legend: "Parent Form Group 2",
                group: [

                    new DynamicFormArrayModel(
                        {
                            id: "testFormArray",
                            label: "Form Array",
                            validator: {
                                required: null,
                                maxLength: 5
                            },
                            errorMessages: {
                                required: "error on {{ id }}"
                                maxLength: "Max character count is 5"
                            },
                            groupFactory: () => {
                                return [
                                    new DynamicInputModel(
                                        {
                                            id: "testInput",
                                            label: "testInput1",
                                            validators: {
                                                required: null,
                                                maxLength: 5
                                            },
                                            errorMessages: {
                                                required: "{{ label }} is required",
                                                maxLength: "Max character count is 5"
                                            }
                                        }
                                    )
                                ];
                            },
                        }
                    )
                ]
            });
        ]
    })
];
`

In previous question #490 i was referring to group validation which currently is working fine.
I am working with a deep nested objects so I am trying to bubble up the error to parent-grantparent etc while something goes wrong in some leaf. Is that possible? does this functionally could be supported?

As I have huge forms I have split the layout in tabs and nested expansion panels in case of objects or tabs in case of arrays. There is no full display of  the whole form and I would like to add an error icon in all the way up, in order to help user visually find the element that has the actual error.

Regards,
S.

**Comment by udos86** [comment]
@stekontar Hi!

> Is that possible? does this functionally could be supported?

No, I'm afraid, not as long as there is no native Angular support for this...
