### ISSUE TITLE
CSS customization 

### ISSUE THREAD

**Issue by medbenmakhlouf** [udos86/ng-dynamic-forms#756]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.3`

[ ] Basic UI
[X] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi All,

I am trying to add CSS class to my controls and I don't find way how to do that ? is there any solution to customize the CSS for input/select ? 

Thanks a lot,
Mohamed

**Comment by udos86** [comment]
@medbenmakhlouf 

Well, this is explained in the [docs ](https://github.com/udos86/ng-dynamic-forms#form-layouts)and show in the sample, too.
