### ISSUE TITLE
Customizing ui-primeng.js under esm5 folder.

### ISSUE THREAD

**Issue by ryan1509** [udos86/ng-dynamic-forms#757]
Hi , I have customized a bit in p-dropdown inside ui-primeng.js file under esm5 folder. 
Here is the below code customized : 
`<p-dropdown *ngSwitchCase=\"7\" #pDropdown [autoWidth]=\"getAdditional('autoWidth', true)\" [dropdownIcon]=\"getAdditional('dropdownIcon', 'fa fa-fw fa-caret-down')\" [dynamicId]=\"bindId && model.id\" [editable]=\"getAdditional('editable', false)\" [filter]=\"model.filterable\" [filterBy]=\"getAdditional('filterBy', null)\" [filterPlaceholder]=\"getAdditional('filterPlaceholder', null)\" [formControlName]=\"model.id\" [ngClass]=\"getClass('element', 'control')\" [options]=\"model.options\" [resetFilterOnHide]=\"getAdditional('resetFilterOnHide', false)\" [scrollHeight]=\"getAdditional('scrollHeight', '200px')\" [tabindex]=\"model.tabIndex\" (onBlur)=\"onBlur($event)\" (onChange)=\"onValueChange($event)\" (onFocus)=\"onFocus($event)\"></p-dropdown><label *ngSwitchCase=\"7\" class=\"lblpdropdown\" [for]=\"model.id\">{{model.label}}</label>` 

In the above code , i have just added one label tag after p-dropdown, it is working fine using ng serve but when using ng build --prod , the added label is not included.What could be the problem?

**Comment by udos86** [comment]
@ryan1509 

Try editing the fesm5, fesm2015 and esm2015 files, as well.

However doing such stuff is totally up to you and not an issue related to the library itself.
