### ISSUE TITLE
How to customize list item of select component?

### ISSUE THREAD

**Issue by NuruddinBadawi** [udos86/ng-dynamic-forms#761]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

1- How to change list content in a select component? for example, add an icon to the items
2- how to make a new type of field?

**Comment by udos86** [comment]
@NuruddinBadawi 

Customizing of components is only possible for libraries that support custom templating, e.g. Kendo.

Otherwise you'd have to provide your own own custom form control.
