### ISSUE TITLE
Primeng calendar control returns two date formats depending on user action

### ISSUE THREAD

**Issue by taurus227** [udos86/ng-dynamic-forms#767]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[X] Prime NG
</code></pre>

## Description

I have a form with a calendar (DATEPICKER) control defined as follows:
```
          {
            "asyncValidators": null,
            "errorMessages": null,
            "hidden": false,
            "id": "FromDate",
            "label": "Start *",
            "labelTooltip": null,
            "controlTooltip": null,
            "layout": {
              "grid": {
                "container": "ui-g-8",
                "control": "ui-g-6",
                "label": "ui-g-6"
              },
              "element": {
                "label": "ui-widget"
              }
            },
            "name": "FromDate",
            "relation": [],
            "updateOn": null,
            "disabled": false,
            "additional": {
              "showButtonBar": true,
              "yearRange": "1990:2050",
              "showTime": true,
              "yearNavigator": true,
              "monthNavigator": true
            },
            "hint": null,
            "tabIndex": null,
            "value": null,
            "format": "yy-mm-dd",
            "max": null,
            "min": null,
            "placeholder": "yyyy-mm-dd",
            "type": "DATEPICKER",
            "focusedDate": null,
            "inline": false,
            "toggleIcon": null,
            "toggleLabel": null,
            "validators": { "required": null }
          }
```
- If the user selects a date and submits the form, I get a date in the following format: `2018-05-31T08:00:00Z`.
- But if I want to set a default value for the field, it doesn't take a date in the same format! I have to specify `2018-05-31`. 
- However, this means that if the user submits the form without touching the field, I will get back the same date value in the same format: `2018-05-31`, while if the user changes the value, I will get the `2018-05-31T08:00:00Z` format.

I think the field should always return the same date format and it should also accept the same format as default value.
Or am I doing something wrong?

**Comment by udos86** [comment]
@taurus227 Hi!

> But if I want to set a default value for the field, it doesn't take a date in the same format! I have to specify 2018-05-31.

I actually don't see any issue here. This works totally fine:

```
new DynamicDatePickerModel({
  id: "departureDate",
  format: "mm/dd/yy",
  inline: false,
  label: "Departure",
  placeholder: "Date of Departure",
  value: new Date("2018-05-31T08:00:00Z")
})
```

**Comment by udos86** [comment]
@taurus227 

After investigating this I'm pretty sure what's going wrong here.

Since your defining your form model as JSON directly in code and not loading and passing a JSON string to `formService.fromJSON()` you need to define your `value` as `Date`:

```
export const PRIME_NG_SAMPLE_FORM_MODEL = [
    {
        "type": "DATEPICKER",
        "id": "arrivalDate",
        "format": "mm/dd/yy",
        "inline": false,
        "label": "Arrival",
        "placeholder": "Date of Arrival",
        "value": new Date("2011-10-05T14:48:00.000Z")
    }
];
```

**Comment by taurus227** [comment]
Yep, that was the problem, I was passing string instead of Date. Thank you!
