### ISSUE TITLE
NG Dynamic Form Control Component Decorator Modification

### ISSUE THREAD

**Issue by ryan1509** [udos86/ng-dynamic-forms#768]
I would like to (for now) extend and change decorators property for 'DynamicPrimeNGFormControlComponent' that is defined in "ui-primeng.es.js". How could i do that? I'm thinking on initialize of the app change the decorators and thereby the template.

**Comment by udos86** [comment]
@ryan1509 

This is not supported by the library. You need to provide your own [custom form control](https://github.com/udos86/ng-dynamic-forms#custom-form-controls).
