### ISSUE TITLE
Resetting a field

### ISSUE THREAD

**Issue by hakalb** [udos86/ng-dynamic-forms#773]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: 5.4.4

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Resetting the whole form is easy but I also would like to reset each field individually.
Is it possible to use e.g. suffix to add a clickable icon for resetting a field?

Regards Håkan

**Comment by udos86** [comment]
@hakalb Hi Håkan!

> Is it possible to use e.g. suffix to add a clickable icon for resetting a field?

I'd recommend that you use a [custom template](https://github.com/udos86/ng-dynamic-forms#custom-templates) if you'd like to provide a button for allowing the user to reset a certain field. 

Greetings to Sweden!

**Comment by hakalb** [comment]
Thanks @udos86  :)

I have used custom templates before to add text and buttons after/before the control. But now I want to add an icon inside the control input field, just list a suffix. Is that possible?
