### ISSUE TITLE
How to get "focus" event working on dynamic-material-form elements?

### ISSUE THREAD

**Issue by fbayanati** [udos86/ng-dynamic-forms#778]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Would you please take a look into the following [stalkblitz](https://stackblitz.com/edit/angular-m47ebl)?:
https://stackblitz.com/edit/angular-m47ebl 

- The focus event doesn't happen.
- The blur event happens on some form controls such as DynamicInputModel input text but not in many other ones.

Wonderful library and thanks again about it.

**Comment by udos86** [comment]
@fbayanati 

Thanks for reporting this bug! I'll deliver a quick fix!

**Comment by udos86** [comment]
Please note that according to the official docs not all Material UI components do support `focus` and `blur` events.

**Comment by fbayanati** [comment]
Yes, you are right, the (matEvent) on dynamic-material-form somehow helps, plus about change event it doesn't work for all UI components too which I ended up by getting changes currently through subscribing the .valueChanges in UI elements.
