### ISSUE TITLE
Material multiple input (Chips) issues

### ISSUE THREAD

**Issue by mdentinho** [udos86/ng-dynamic-forms#779]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.5`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Whenever a simple input is transformed into a multiple input, these features stop working:
1. The `label` is ignored and the placeholder is used instead (this is an old issue already solved in the simple input)
2. The `hint` is ignored and nothing related to it is rendered.

**Working simple input:**
```typescript
    new DynamicInputModel({
      id: 'simpleInput',
      inputType: 'text',
      label: 'Simple Input',
      placeholder: 'Simple Input Placeholder',
      hint: 'Simple Hint',
    }),
```
![Working Simple Input](https://cl.ly/2x1N1f0D0K3q/Screen%20Recording%202018-06-05%20at%2011.02%20AM.gif)

**Not working multiple input:**
```typescript
    new DynamicInputModel({
      id: 'multpleInput',
      inputType: 'text',
      label: 'Multiple Input',
      placeholder: 'Multiple Input Placeholder',
      hint: 'Multiple Hint',
      multiple: true,
    }),
```
![Not working multiple input](https://cl.ly/2L1S2H0v3w2t/Screen%20Recording%202018-06-05%20at%2011.06%20AM.gif)

Cheers!

**Comment by udos86** [comment]
@mdentinho Hi!

Thanks for the detailed report. I'll have a look at it as soon as possible!

**Comment by udos86** [comment]
@mdentinho 

After further investigation `<mat-hint>`  is not working properly with chips input.

Starting with next patch version the behavior of `label` and `placeholder` can be better controlled via `appearance` (see #799)
