### ISSUE TITLE
How to implement Angular Material Stepper

### ISSUE THREAD

**Issue by joebalan-eot** [udos86/ng-dynamic-forms#781]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

@udos86 First of all, thank you so much for providing such an awesome library.

I would like to implement this ng-dynamic-forms as part of angular material stepper. 
Kindly, provide me the possible ways of implement.

Thank You,
Joe

**Comment by udos86** [comment]
@joebalan-eot Hi Joe! 

> First of all, thank you so much for providing such an awesome library.

Thank you for your kind words!

> Kindly, provide me the possible ways of implement.

I'm sorry I didn't have the time so far to look deeper into Material stepper. 

I'll leave this issue open as long as I can come back to you with some advices. 

Maybe someone from the community can help out as well.

**Comment by udos86** [comment]
_closed due to inactivity_
