### ISSUE TITLE
Is having a Layout.ts file necessary for every component using a dynamic form?

### ISSUE THREAD

**Issue by rstor** [udos86/ng-dynamic-forms#787]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I am running an Angular 6 app and I get errors such as `Property 'formLayout' does not exist on type 'DataformDemoComponent'.` When I create a `layout.ts` file that has basically (on the surface) no correlation to the component with the dynamic form (i.e., the id is not referencing anything in that specific component) , the error goes away. I would like to know is the layout file absolutely necessary or is there another way? If I need a layout.ts file for every component I suppose I would just create a shared file that all components use?

**Comment by udos86** [comment]
@rstor Hi Ryan!

> I would like to know is the layout file absolutely necessary or is there another way?

Having a layout file is absolutely not mandatory and if you're using everything correctly there should be no errors as well.

There is also another way of applying layout information: when defining a dynamic form model in JSON you can make use of the `layout` property.
