### ISSUE TITLE
Can't load mask from json when it have a "/" separator

### ISSUE THREAD

**Issue by rodcoura** [udos86/ng-dynamic-forms#788]
## I'm submitting a

<pre><code>
[ X ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `Last`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ X ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I can't use "/" as mask separator when using "fromJson" method in DynamicFormService

<pre>
<code>
function (mask) {
  if (typeof mask === "string") {
      var /** @type {?} */ isRegExp = (/** @type {?} */ (mask)).startsWith("/") && (/** @type {?} */ (mask)).endsWith("/");
      return isRegExp ? new RegExp((/** @type {?} */ (mask)).slice(1, mask.length - 1)) : mask;
  }
  else if (Array.isArray(mask)) {
      return /** @type {?} */ ((/** @type {?} */ (mask)).map(function (value) { return JSONUtils.maskFromString(value); }));
  }
  return null;
};
</code>
</pre>

It happens because you check if the char starts and endswith "/", you should check the char length as well, you can only assure it starts with "/" and ends with "/" when you have a minimum of 2 characters

**Comment by udos86** [comment]
closed as of #1140
