### ISSUE TITLE
custom template not working if modelId embedded in DynamicFormGroup

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#790]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

when using 

`<ng-template modelId="xxx"></ng-template>`

if the DynamicFormControl whose id is used in modelId is embedded in a DynamicFormGroup, the custom template is not rendered.

**Comment by rernens** [comment]
@udos86 

Hi,

I have not heard from you on this issue, maybe because I did not put enough details in your opinion.

I thought this was self explanatory as this was working previously.

Let me further extend what is happening :

One of the nicest feature of ng-dynamic-form is its extensibility through ng-template, allowing to add a custom element to a form and associate it to a form element to present it before or after such element.

But while this still perfectly working if the form element for which you want attach a ng-template custom element is a direct child of the main form group, it no longer works if the element is the child of an embedded NgDynamicFormGroup.

Custom templates are no longer rendered !!!

if you need more let met know.

**Comment by udos86** [comment]
@rernens Hi!

Sorry for not responding earlier. Sometimes I need to take a step back of this because of other things going on in my life. Keeping everything up to date is really time-consuming with all these UI libs out there.

However, I did a quick test for this and I can't really discover any issues here.

I basically just took the Material sample and added a `<ng-template>` for `roomQuantity`.

This is the section of the sample form model:

```ts
    new DynamicFormGroupModel({

        id: "room",
        group: [
            new DynamicSelectModel<string>({

                id: "roomSize",
                placeholder: "Room Size",
                hint: "Choose a room type",
                options: [
                    {
                        label: "Single Room",
                        value: "single-room"
                    },
                    {
                        label: "Double Room",
                        value: "double-room"
                    },
                    {
                        label: "Business Suite",
                        value: "business-suite"
                    },
                    {
                        label: "Presidential Suite",
                        value: "presidential-suite"
                    },
                    {
                        label: "Storeroom",
                        value: "storeroom"
                    }
                ]
            }),

            new DynamicInputModel({

                id: "roomQuantity",
                inputType: "number",
                placeholder: "Room Quantity",
                hint: "Maximum: 5",
                max: 5,
                min: 0
            })
        ]
    }), 
```

And this is the component template:

```html
        <form [formGroup]="formGroup">

            <dynamic-material-form [group]="formGroup"
                                   [layout]="formLayout"
                                   [model]="formModel"
                                   (blur)="onBlur($event)"
                                   (change)="onChange($event)"
                                   (focus)="onFocus($event)"
                                   (matEvent)="onMatEvent($event)">

                <ng-template modelId="roomQuantity"><p>This is a test</p></ng-template>

            </dynamic-material-form>

        </form>
```

Everything seems to be working fine...

**Comment by rernens** [comment]
@udos86 

Hi Udo,

Don't worry, I was also on other issues and the problem is not critical to a point that it required immediate attention. It is now annoying as it prevents to build user friendly forms.

Here below the model and the html of a simple form where custom templates do not work for fields embedded in a DynamicFormGroupModel :

```
export const PSWD_FORM_MODEL = [
  new DynamicInputModel({
    id: 'oldPswd',
    inputType: 'password',
    autoComplete: AUTOCOMPLETE_OFF,
    placeholder: '?',
    validators: {
      required: null
    },
    asyncValidators: {
      pswdCheck: {
        name: 'pswdCheck',
        args: null
      }
    },
    errorMessages: {
      required: '?',
      pswdCheck: '?'
    }
  }),
  new DynamicFormGroupModel({
    id: 'pswdGroup',
    validators: {
      equalPswd: {
        name: 'equalPswd',
        args: null
      }
    },
    errorMessages: {
      equalPswd: '?'
    },
    group: [
        new DynamicInputModel({
          id: 'newPswd',
          inputType: 'password',
          autoComplete: AUTOCOMPLETE_OFF,
          placeholder: '?',
          validators: {
            required: null
          },
          errorMessages: {
            required: '?'
          }
        }),
        new DynamicInputModel({
          id: 'newPswdConfirm',
          inputType: 'password',
          autoComplete: AUTOCOMPLETE_OFF,
          placeholder: '?',
          validators: {
            required: null
          },
          errorMessages: {
            required: '?'
          }
        })
    ]}
  )
];
```

```
<form [formGroup]="formGroup" novalidate >
	<dynamic-material-form-control 	*ngFor="let controlModel of formModel"
									[group]="formGroup"
									[layout]="formLayout"
									[model]="controlModel"
	>
		<ng-template modelId="oldPswd" align="START">
			<mat-icon matPrefix>face</mat-icon>
		</ng-template>
		<ng-template modelId="newPswd" align="START">
			<mat-icon matPrefix>lock_outline</mat-icon>
		</ng-template>
			<ng-template modelId="newPswdConfirm" align="START">
				<mat-icon matPrefix>lock_outline</mat-icon>
			</ng-template>
	</dynamic-material-form-control>
	<div  class="text-center">
		<hr >
		<button class="btn stylish-color btn-lg waves-effect waves-light"
				mdbrippleradius
				(click)="cancel()">
			{{ 'PSWD.FORMS.PSWDFORM.BUTTONS.cancel' | translate }}
		</button>
		<button class="btn green custom btn-lg waves-effect waves-light"
				mdbrippleradius
				[disabled]="formGroup.invalid"
				(click)="accept()">
			{{ 'PSWD.FORMS.PSWDFORM.BUTTONS.submit' | translate }}
		</button>
	</div>
</form>
```

as you can see in the below screen capture, no icons show up in front of last two fields 

![image](https://user-images.githubusercontent.com/10088036/45504221-8ab01c00-b789-11e8-911a-8b9906105cf6.png)

Hope it helps.

**Comment by udos86** [comment]
@rernens 

Ok, I finally discovered what's going on here.

You're using `<dynamic-material-form-control>` without binding `[templates]`. Therefore no templates are passed to the `DynamicMaterialFormControlContainerComponent`. 

Is there any reason why you're not using `<dynamic-material-form>` instead? 

Would solve all your issues right away.

Closed due to this not being a bug and working as designed.

**Comment by rernens** [comment]
@udos86 

Hi Udo, 

I should have been diving deeper in your code to figure that out myself and not bothering you with that.

Thanks for this quick reply.
