### ISSUE TITLE
Show legend for a DynamicFormGroupModel with material-ui

### ISSUE THREAD

**Issue by abariatti** [udos86/ng-dynamic-forms#791]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.5`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Can you please show the legend when using material-ui library if it exists in the DynamicFormGroupModel. For now it appears that it only shows in the bootstrap-ui. That would be neat! Thanks

**Comment by Karamuto** [comment]
@abariatti 
I guess this is working as intended, as there is no 'legend' in the material library.
The closest thing to that would be a card.

**Comment by abariatti** [comment]
@Karamuto 
Exactly and that is why it should be implemented with what is available in the material library. I'm speaking of the ui-material module so this implementation should be tailored to angular material library.

**Comment by udos86** [comment]
@abariatti Hi!

What would be your suggestion for a proper equivalent to `<legend>` in Material?

**Comment by udos86** [comment]
closed due to inactivity
