### ISSUE TITLE
how to put controlls in one row

### ISSUE THREAD

**Issue by mmirzaeyan** [udos86/ng-dynamic-forms#794]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[* ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ *] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
i want to create form with 6 element and put each 3 element in one row how to do this with form layouts ?

**Comment by Karamuto** [comment]
Hello @mmirzaeyan,
as you are using bootstrap. You could add the row and column classes to the corresponding containsers.

Placing "row" on "grid": "container" for the FormGroup,
and "col-4" on "grid": "element" should do the trick.

Maybe you need to try some combinations: https://github.com/udos86/ng-dynamic-forms#form-layouts

**Comment by mmirzaeyan** [comment]
can you explaine some more about this,please  ?

**Comment by maroy1986** [comment]
I had a similar question for MaterialUI, but I decided to dig into the code and found my answer. So, if I can give you a good advise, don't be shy to dig into the code, you'll probably find what you are looking for and in bonus have a better understanding of what's going on behind the scene 😄

**Comment by udos86** [comment]
Please have a look at the samples on how to place controls via CSS classes.
