### ISSUE TITLE
DynamicInputArrayModel is Possible ?

### ISSUE THREAD

**Issue by KANekT** [udos86/ng-dynamic-forms#796]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[x] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
How i my create InputArrayModel?

i need Array for DynamicInputModel
for output in formGroup.value i need:

"inputGroupModel": ["1","2","3","4"]
"Choices": ["choice1", "choice2", "..."]

**Comment by udos86** [comment]
@KANekT 

Sorry, no plans on implementing a special model for this use case.
