### ISSUE TITLE
form action hidden or visible doesn't work

### ISSUE THREAD

**Issue by pedroraft** [udos86/ng-dynamic-forms#797]
## I'm submitting a

<pre><code>
[ x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
When you use a action to hide a form it doesn't work, if you change the example on bootstrap-sample-form.model.ts from action DISABLE to HIDDEN it does not hide, im  looking in to it myself right now as i need this asap but i could use some help, maybe i'm just missing something here.

edit: if you use hidden: true and change the action to visible does not work either
``` typescript
new DynamicTextAreaModel({
                id: "bootstrapTextArea",
                label: "Textarea",
                rows: 5,
                placeholder: "example Textarea",
                hidden: true,
                relation: [
                    {
                        action: "HIDDEN", // DISABLE WORKS, HIDDEN NOT
                        connective: "OR",
                        when: [
                            {
                                id: "bootstrapRadioGroup",
                                value: "option-2"
                            }, 
                            {
                                id: "bootstrapRadioGroup",
                                value: "option-4",
                            }
                        ]
                    }
                ],
            }),
```

**Comment by maxencehenneron** [comment]
Same issue, any progress?

**Comment by danimt** [comment]
Would also be awesome if `when` would also take a function for special cases.

**Comment by carlwang87** [comment]
Same issue, any progress?

**Comment by pedroraft** [comment]
guys #807 is the same thing, this bug exists for months, this library seems to be abandoned. I don't want to be that guy but react has formik, react has more users therefore more libraries and people involved in keeping them... my 2 cents on the matter.

**Comment by udos86** [comment]
_will be working in `8.0.0`_
