### ISSUE TITLE
Change value Using button click event in DynamicRadioGroupModel

### ISSUE THREAD

**Issue by charlig** [udos86/ng-dynamic-forms#803]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm trying to change the value in DynamicRadioGroupModel when button click event triggered, I'm using 
"setValue()" method as below. My problem is after setting value into FormController UI doesn't change. 
Help me to figure it out .

<pre>
new DynamicRadioGroupModel<string>({

        id: "payment",
        label: "Payment Method",
        options: [
            {
                label: "Credit Card",
                value: "cc"
            },
            {
                label: "PayPal",
                value: "paypal"
            },
            {
                label: "Cash",
                value: "cash"
            },
            {
                label: "Bitcoin",
                value: "bitcoin"
            }
        ],
        value: "cc"
    })
</pre>

<pre>
test(){

    this.formGroup.get("payment").setValue("cash");

  }
</pre>
<p>
<div class="overflow-hidden content-margin container-fluid" style="width: 50%;">

    <form class="form-horizontal" [formGroup]="formGroup">

        <dynamic-ng-bootstrap-form-control *ngFor="let formModelCtrl of formModel"
                                   [group]="formGroup"
                                   [layout]="formLayout"
                                   [model]="formModelCtrl"
                                   (blur)="onBlur($event)"
                                   (change)="onChange($event)"
                                   (focus)="onFocus($event)"
                                   (ngbEvent)="onNgbEvent($event)"></dynamic-ng-bootstrap-form-control>

    </form>

    <button (click)="test()" type="button">Test</button>

    <pre>{{formGroup.value | json}}</pre>

</div>
</p>

**Comment by Karamuto** [comment]
Hello @charlig ,

for updating values, you should use the 'valueUpdates' Subject from your DynamicFormsModel, in your case this here should work::

`
const radioGroup: DynamicRadioGroupModel<string> = this.dynamicFormService.findById('payment', this.formModel) as DynamicRadioGroupModel<string>;
    radioGroup.valueUpdates.next('cc');`

'dynamicFormService' is the one you used to create your form group from the model.

**Comment by charlig** [comment]
Hello @KSingh1980 

thank a lot for this solution because i 've done  using HTMLelement and change the value

**Comment by udos86** [comment]
@Karamuto Thanks for helping out again!
