### ISSUE TITLE
Validator messages for custom validators are always 'null'

### ISSUE THREAD

**Issue by Karamuto** [udos86/ng-dynamic-forms#805]
## I'm submitting a

<pre><code>
[ x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

When using a custom validator, the extraction of the message is broken. The pattern {{validator.property}} always results in 'null'.

Problem lies in this code part of dynamic-form-validation.service.ts :

<code>

createErrorMessages(control: AbstractControl, model: DynamicFormControlModel): string[] {

        let messages: string[] = [];

        if (typeof model.errorMessages === "object" && model.errorMessages !== null) {

            let messagesConfig = model.errorMessages as DynamicValidatorsConfig;

            Object.keys(control.errors || {}).forEach(validationErrorKey => {

                let messageKey = validationErrorKey;

                if (validationErrorKey === "minlength" || validationErrorKey === "maxlength") {
                    messageKey = messageKey.replace("length", "Length");
                }

                if (messagesConfig.hasOwnProperty(messageKey)) {

                    let validationError = control.getError(validationErrorKey),
                        messageTemplate = messagesConfig[messageKey] as string;

                    messages.push(this.parseErrorMessageConfig(messageTemplate, model, validationError));
                }
            });
        }

        return messages;
    }

</code>

at this part 'validationError' have to be 'controls.errors' instead of 'control.getError(validationErrorKey)'

`
messages.push(this.parseErrorMessageConfig(messageTemplate, model, validationError));
`

**Comment by udos86** [comment]
@Karamuto 

Are you sure this is a bug? 

There should be no difference here between a built-in validator and a custom validator.

Some validators just apply a complex error object, i.e `minLength`:

`{requiredLength: 6, actualLength: 1}`

**Comment by Karamuto** [comment]
I close this, it was an mistake from my side. I returned a bad error object.
