### ISSUE TITLE
Related form control HIDDEN and VISIBLE actions don't work :: Material UI :: linked a stackblitz sample

### ISSUE THREAD

**Issue by fbayanati** [udos86/ng-dynamic-forms#807]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Tried to make a control hidden according to the related form controls explanation as below and it just work to DISABLE the control:
https://github.com/udos86/ng-dynamic-forms#related-form-controls

In dynamic-form-control-relation.model.ts the following constant are defined:
export const DYNAMIC_FORM_CONTROL_ACTION_DISABLE = "DISABLE";
export const DYNAMIC_FORM_CONTROL_ACTION_ENABLE = "ENABLE";
export const DYNAMIC_FORM_CONTROL_ACTION_VISIBLE = "VISIBLE";
export const DYNAMIC_FORM_CONTROL_ACTION_HIDDEN = "HIDDEN";

Related form controls functionality can’t make HIDDEN or VISIBLE actions to work, please see the sample test in stackblitz:
https://stackblitz.com/edit/angular-ebc3gf

**Comment by pedroraft** [comment]
Related to #797

**Comment by kwoxford** [comment]
Me too

**Comment by deasek** [comment]
same problem here

**Comment by CAlex-Wilson** [comment]
Can confirm this is still an issue. Only DISABLE works currently for the latest version of Material.

**Comment by carlwang87** [comment]
I have encountered this problem. Even I config hidden in the model, it does not work.
`    new DynamicColorPickerModel({

        id: "roomColor",
        label: "Room Color",
        value: "#FFFFFF",
        hidden: true,
        disabled: true
    }),`

The DynamicColorPickerModel is still show on the page. Is there a way to hide a model?

Thanks!

**Comment by udos86** [comment]
_will be working in `8.0.0`_
