### ISSUE TITLE
Generating Dynamic Form Control Component from Custom Form Control Component

### ISSUE THREAD

**Issue by Sanjay10247** [udos86/ng-dynamic-forms#810]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hey @udos86 , I'm trying to create a DynamicFormControlComponent from custom form control & below are the problems i am facing.

1) What exactly do you mean by `/* corresponding DynamicFormControlModel */?` - should we create a new custom DynamicFormControlModel & embed the same.

2) Where does the below code reside ?

`providers: [
  {
    provide: DYNAMIC_FORM_CONTROL_MAP_FN,
    useValue: (model: DynamicFormControlModel): Type<DynamicFormControl> | null  => {
      switch (model.type) {
        case DynamicSelectModel:
          return MyDynamicCustomFormControlComponent;
        }
     }
  }
]`
In app.module?

3) With respect to the code mentioned in the 2nd point, `model.type` returns a string, how can that be compared with the `DynamicSelectModel`?

Moreover, it would be helpful if there is an example provided to achieve the dynamic form control component from custom form control.

If possible, could you please convert the custom angular form control which you have mentioned in the 2nd line of the [Custom Form Controls](https://github.com/udos86/ng-dynamic-forms#custom-form-controls) to dynamic form control component and how the use the same using json.

**Comment by bandman0226** [comment]
I have the exact same questions as @Sanjay10247. I thought I had it right but keep getting:

Error: unknown form control model type defined on JSON object with id "sampleSelectGrid"

**Comment by Karamuto** [comment]
Hello @Sanjay10247 ,

as I have already defined custom controls in my application I think I can provide some help here.

1. Every Form Control Type in this libaray has a corresponding constant, which holds the type used in the model class. For example: `DYNAMIC_FORM_CONTROL_TYPE_INPUT` is the name of the constant for the `DynamicInputModel`. In you case it should be `DYNAMIC_FORM_CONTROL_TYPE_SELECT`.

2. This code belongs in a module. If you provide it on `app.module` it should work just fine. ( But could also be provided on lower levels )

3 Should be answered with 1. if I see this correctly.

Any more querstions?

Greetings

**Comment by Sanjay10247** [comment]
Hello @Karamuto ,

Thanks for your reply. I am exactly trying to implement the upload in angular material with my own customizations.

As per your suggestion i have tried the below

1. I should be using the `DynamicInputModel` in place of the `/* corresponding DynamicFormControlModel */` in my custom dynamic form control component.

2. I have provided the below code in `app.module` - `providers`

`{
      provide: DYNAMIC_FORM_CONTROL_MAP_FN,
      useValue: (model: DynamicCustomUploadModel): Type<DynamicFormControl> | null  => {
        switch (model.type) {
          case DYNAMIC_FORM_CONTROL_TYPE_INPUT:
            return MyDynamicCustomFormControlComponent;
          }
        }
    }`

3. So here i would be using `DYNAMIC_FORM_CONTROL_TYPE_INPUT` as shown in the 2nd point.

But i get the following error as below

![error](https://user-images.githubusercontent.com/41230818/42796491-152eb78e-89a8-11e8-856e-aa7df6352219.PNG)

& my custom dynamic form control component is as below 

`import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, ViewChild } from '@angular/core';
import { FormGroup } from '@angular/forms';
import {
    DynamicFormControlComponent,
    DynamicFormControlCustomEvent,
    DynamicFormLayout,
    DynamicFormLayoutService,
    DynamicFormValidationService,
    DynamicInputModel
} from '@ng-dynamic-forms/core';
import { CustomUploadComponent } from '../custom-upload/custom-upload.component';


@Component({
    selector: 'app-dynamic-custom-form-control',
    templateUrl: './dynamic-form-component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class MyDynamicCustomFormControlComponent extends DynamicFormControlComponent {

    @Input() bindId = true;
    @Input() group: FormGroup;
    @Input() layout: DynamicFormLayout;
    @Input() model: DynamicInputModel; /* corresponding DynamicFormControlModel */

    @Output() blur: EventEmitter<any> = new EventEmitter();
    @Output() change: EventEmitter<any> = new EventEmitter();
    @Output() customEvent: EventEmitter<DynamicFormControlCustomEvent> = new EventEmitter();
    @Output() focus: EventEmitter<any> = new EventEmitter();
    @ViewChild(CustomUploadComponent) customUploadComponent: CustomUploadComponent;

    constructor(protected layoutService: DynamicFormLayoutService,
                protected validationService: DynamicFormValidationService) {

        super(layoutService, validationService);
    }
}`

If possible can I have a look on the custom dynamic form control component which you have defined? as an example would be an great help in understanding the implementation.

**Comment by Sanjay10247** [comment]
Hello @Karamuto ,

Thanks for your reply. I am exactly trying to implement the upload in angular material with my own customizations.

As per your suggestion i have tried the below

1. I should be using the DynamicInputModel in place of the /* corresponding DynamicFormControlModel */ in my custom dynamic form control component.

2. I have provided the below code in app.module - providers

{ provide: DYNAMIC_FORM_CONTROL_MAP_FN, useValue: (model: DynamicCustomUploadModel): Type<DynamicFormControl> | null => { switch (model.type) { case DYNAMIC_FORM_CONTROL_TYPE_INPUT: return MyDynamicCustomFormControlComponent; } } }

3. So here i would be using DYNAMIC_FORM_CONTROL_TYPE_INPUT as shown in the 2nd point.

But i get the following error

![error](https://user-images.githubusercontent.com/41230818/42797071-0d3dafbe-89ab-11e8-9ddd-0e263378e5d9.PNG)

& my custom dynamic form control component is as below

![code](https://user-images.githubusercontent.com/41230818/42797161-7043ea1a-89ab-11e8-96d2-f14e3b9b7e43.PNG)

I get the error at `[ngClass]="[getClass('element', 'host', _model), getClass('grid', 'host', _model)]"` even though when i tried with implementing the getClass in the component which return empty string.

If possible can I have a look on the custom dynamic form control component which you have defined? as an example would be an great help in understanding the implementation.

**Comment by Karamuto** [comment]
At first I would suggest that you use the 'DYNAMIC_FORM_CONTROL_TYPE_FILE_UPLOAD ' for this case, as there exists no file upload in material, you won't block anything.

But this has nothing to do with you error. Could you show your HTML and the FormModel Array in use for you case?

Sadly I can't show my code, as its made on my job and belongs to the company.

**Comment by bharath14** [comment]
how can i create 'DYNAMIC_FORM_CONTROL_TYPE_SAMPLE'? @Karamuto 
is there any Interface or class that i have to implement/extend?

**Comment by Karamuto** [comment]
Hello @bharathD29 ,

'DYNAMIC_FORM_CONTROL_TYPE_SAMPLE' is just a constant with string value. Just add it to any typescript file like this:

`export const DYNAMIC_FORM_CONTROL_TYPE_SAMPLE = 'SAMPLE';  `

**Comment by Karamuto** [comment]
As there seems to be no more question I will close down this issue.
