### ISSUE TITLE
Change DynamicFormControlModel dynamically, and SSR Support?

### ISSUE THREAD

**Issue by glikoz** [udos86/ng-dynamic-forms#812]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I'm using Asp.Net Core on server side, and I want to create not only forms but also whole page via your approach. I want to create all page model from api that I served from Asp.Net Core. All routes will be served from server side also. So when user click /user/2/edit link I will give Model and Data (Maybe with Custom Template), so as first step how can I change DynamicFormControlModel[] by js code.

Second Question is about SSR, do you have support for it.

I tried to explain the architecture that I thougt in this SO question https://stackoverflow.com/questions/51119224/dynamically-on-runtime-create-reactive-page-with-asp-net-core-c-angular-r

Thx.

**Comment by Karamuto** [comment]
Hello @glikoz ,

so you are trying to build a CMS like Drupal or Wordpress with this library? By now this library is only supporting Forms, and thats actually a good thing as forms are the most complex elements to be generated dynamically. You could use this project as inspiration to build your site rendering, forms could still be generated through this library.

For SSR, you need to try it out,, but I don't know if Angular Universal will be possible in your described situation.

Greetings

**Comment by udos86** [comment]
@Karamuto Thanks for the fine reply!
