### ISSUE TITLE
how to fill a select from an API?

### ISSUE THREAD

**Issue by mmirzaeyan** [udos86/ng-dynamic-forms#813]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[* ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ *] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
how can i fill options in a select from an API?

**Comment by Karamuto** [comment]
Hello @mmirzaeyan,

the `DynamicSelectModel` allows you to use an `Observable<Array<DynamicFormOptionConfig<T>>>` instead of an `Array<DynamicFormOptionConfig<T>>`. If this Observable is derivated from a `Subject` you could fill the select at runtime.

**Comment by mmirzaeyan** [comment]
can you give me a sample or link that do this ?

**Comment by Karamuto** [comment]
Here is minimal example for the upper statement:

```
@Component({
  selector: 'test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss']
})
export class TestComponent {

private optionsSource: BehaviorSubject<Array<DynamicFormOptionConfig<string>>> = new BehaviorSubject<Array<DynamicFormOptionConfig<string>>>([{
    label: '-',
    value: null,
    disabled: true
  }]);

testFormModel: Array<DynamicFormControlModel> = [
    
    new DynamicSelectModel(
      {
        id: 'testSelect',
        options: this.optionsSource.asObservable()
      }
    )
    
  ];

...

updateSelect(selectOptions: Array<DynamicFormOptionConfig<string>>): void {
    this.optionsSource.next(selectOptions);
  }

```

like this the options in the select are bound to the `Observable` from `optionsSource`, this can be updated with a call to `updateSelect`

**Comment by udos86** [comment]
@Karamuto Thanks for giving support on this.

**Comment by kanvishok** [comment]
Hi @mmirzaeyan, 

How can i achieve this? the form model is loaded from an external source and I would like to load the select box option from service. but the service is available on the class where we are load this model from json. I mean the foodservice is getting injected on this class where we load this model.

 {
        "asyncValidators": null,
        "errorMessages": {
            "required": "this field is required"
        },
        "hidden": false,
        "id": "foodType",
        "label": null,
        "labelTooltip": null,
        "controlTooltip": null,
        "layout": null,
        "name": "foodType",
        "relation": [],
        "updateOn": null,
        "validators": {
            "required": null
        },      
        "disabled": false,
        "additional": null,
        "hint": null,
        "required": false,
        "tabIndex": null,
        "value": null,
        "options": "this._foodService.getFoodTypes()",
        "type": "SELECT",
        "filterable": false,
        "multiple": false,
        "placeholder": "Leave Type",
        "prefix": null,
        "suffix": null
    }
