### ISSUE TITLE
update sample to version 6

### ISSUE THREAD

**Issue by m98** [udos86/ng-dynamic-forms#814]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
The sample you're providing isn't using the latest version of Angular, and the last commit in that directory seems to be very old!

Could you please update the sample using the latest version of Angular (v6 currently)

Also, I was trying to use the form builder utilizing the Material UI, it was showing me the form, but the Material logic and theme were not working!

**Comment by udos86** [comment]
Sample has been updated on the server and can be viewed under known [URL](http://ng2-dynamic-forms.udos86.de/sample/index.aot.html).
