### ISSUE TITLE
Ability to add custom attributes to element

### ISSUE THREAD

**Issue by m98** [udos86/ng-dynamic-forms#816]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I'm trying to make an element to do something special, but for this, I need to make it different from the rest of the form inputs to listen to its changes. For example, I have an input which I need to search in the list of world cities, and this input is an autocomplete which updates by issuing an HTTP request. So, I need to handle it using custom methods, and I might have this autocomplete more than one times in some forms.

It would be useful if we could append special `data-*` (or `class`) attributes to inputs so we could listen to it, and do appropriate action. Also, the service needs to support getting items by `class` and `data-*`

**Comment by udos86** [comment]
@m98 As this is a highly individual and confusing proposal it's unfortunately declined.
