### ISSUE TITLE
Grid is not working on DynamicFormArrayModel 

### ISSUE THREAD

**Issue by taimoor99** [udos86/ng-dynamic-forms#818]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm working on nested DynamicFormControlModel[] form structure like
<pre><code>
export const MY_FORM_MODEL: DynamicFormControlModel[] = [
    new DynamicFormGroupModel({
   id: 'myFormControlModelId',
      group: [
        new DynamicFormArrayModel({
          id: 'headerconfig',
          initialCount: 1,
          label: 'Header',
          groupFactory: () => {
            return [
              new DynamicInputModel({
                id: 'key',
                label: 'Header Key',
                placeholder: 'Header Key',
              }),
              new DynamicInputModel({
                id: 'value',
                label: 'Header Value',
                placeholder: 'Header Value'
              })
            ];
          }
        })
      ]
    })
  ];

and layout model is like 

export const MY_FORM_LAYOUT = {
    'headerconfig': {
        element: {
            control: 'form-row'
        },
    },
    'key': {
        element: {
            label: 'col-form-label control-label',
        },
        grid: {
            host: 'col-sm-2'
        }
    },
    'value': {
        element: {
            label: 'col-form-label control-label',
        },
        grid: {
            host: 'col-sm-4'
        }
    }
};
</pre></code>
can any one help me to solve this i want key and value input in single line. Thanks

**Comment by Karamuto** [comment]
Hello @taimoor99 ,

looking at the source code [here](https://github.com/udos86/ng-dynamic-forms/blob/master/packages/ui-ng-bootstrap/src/form-array/dynamic-ng-bootstrap-form-array.component.html), it seems you need to use `group` as selector for 'headerconfig' instaed of `control`.

Greetings

**Comment by taimoor99** [comment]
Thanks @Karamuto problem solved

**Comment by Karamuto** [comment]
No problem I has similiar issues in the past to use the right selector.
