### ISSUE TITLE
Textarea autosize support

### ISSUE THREAD

**Issue by mpschaeuble** [udos86/ng-dynamic-forms#819]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Angular material supports the "mat-autosize" directive (https://github.com/angular/material2/blob/master/src/lib/input/autosize.ts) on textareas, which is very useful in some cases. It would be very nice to have support for this feature (e.g. material specific using the "additional" property).

**Comment by Karamuto** [comment]
Hello @mpschaeuble,

I agree as this is a missing feature. But instead of `mat-autosize`, it should be `cdkAutosize`, cause `mat-autosize` is marked as deprecated for the next major version.

**Comment by udos86** [comment]
@mpschaeuble @Karamuto 

Alright, let's do this!
