### ISSUE TITLE
Layout - Possibility to apply class to childrens without specific IDs

### ISSUE THREAD

**Issue by maroy1986** [udos86/ng-dynamic-forms#821]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hey there,

I'm trying to apply some layout to my forms using the FormLayout approach of your library. My issue is that it seems to be mandatory to have an ID on a control on which you want to apply some CSS classes. In my case, I have forms with over 50 controls so it doesn't make sense to add an entry for each of them in the layout file. Right now I have this which I've done to test if it was working : 
![image](https://user-images.githubusercontent.com/2490360/43222989-9cc45eec-901f-11e8-927f-6a4582a22fce.png)

So I think you understand me want I say I don't want to generate or add an entry for each of the controls on the form, which furthermore, can change based on some security restriction per user.

**So here's the question :** Is there a way to apply a class to all childrens of a group, without needing to specify each IDs in the layout file. I'm thinking of something like this :
![image](https://user-images.githubusercontent.com/2490360/43223203-5af19ede-9020-11e8-94f9-1fec8bb65428.png)
This would give me the ability to set something for the group itself and then set kind of a "default" style to apply to childs if nothing specific is defined.

Is that something your library already support? If not, I would be glad to help adding that kind of capability if you feel this could be a feature the project can benefit from and is align with your vision on the product.

Thanks!
Marc.

**Comment by rodcoura** [comment]
If you apply it directly to the Model you don't need to specify the ID

**Comment by dcorriveau-omniscient** [comment]
I think what he's wondering is if it's possible to set a default class for the elements, so that you don't have to specify it for each of them.
For example you could set the bootstrap `row` class on all groups of the model, and then `col-sm-4 col-lg-2` for each control (without having to specify that "manually" for each group and each control in the model).

**Comment by rodcoura** [comment]
Got it, anyway he can't do it automatically trough API. 
He'll have to implement his own layout logic then send it to API.

**Comment by maroy1986** [comment]
What I ended up for now is to loop each control model and override the layout that gets automatically set. I don't find this optimal although it works.

I'm still looking for a better solution if any available, or any given cue that such feature could be added to the lib while respecting the vision of the author.

**Comment by Karamuto** [comment]
Hello @maroy1986,

at the given time your solution is the only way to accomplish this, and as this would only be a feature for `FormGroups` and `FormArrays` it shouldn't be too bothersome to implemente.

But I would prefer to define it like this: 

```
'consumer-detail-form-group': {
   grid: {
      control: 'row',
      children: 'col-sm-3 col-lg-4'
   }
```

This way we don't have to change the current layout model ( and have no breaking change ). We could place it in the html markup now at the same position as the `host` selector.

**Comment by maroy1986** [comment]
@Karamuto Love that, I'll make a PR for it today :)
