### ISSUE TITLE
How to provide the default values to the control for editing/update use-case?

### ISSUE THREAD

**Issue by KSingh1980** [udos86/ng-dynamic-forms#827]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[x ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

How to provide the default values/load the values to the form for editing/update use-case? Any example would be great .

Thanks
KS

**Comment by Karamuto** [comment]
Hello @KSingh1980 ,

I got problems unterstanding your problem, could you provide an example ( not in code ) for this?

**Comment by KSingh1980** [comment]
My question is - To create a new FORM using the JSON file download from the server, it works great. But How do fill in the values in the FORM Controls for edit purpose ?

Example:- I have  **UserProfile.Json** which is a dynamic form but I want to fill in the values in the control for a specific user for edit purpose.

ngOnInit() {

 let userProfile = {
firstName="Ksingh",
lastName="MSingh"
}
    this.http.get<object[]>('./app/user-profile.json').subscribe(formModelJson => {

        this.formModel = this.formService.fromJSON(formModelJson);
        this.formGroup = this.formService.createFormGroup(this.formModel);
    });
}
Example JSON

JSON file :==> 

[
    {
        "type": "INPUT",
        "id": "fname",
        "label": "First Name",
        "maxLength": 42,
        "placeholder": "First Name"
    },
{
        "type": "INPUT",
        "id": "fname",
        "label": "Last Name",
        "maxLength": 42,
        "placeholder": "Last Name"
    } 
]

**Comment by Karamuto** [comment]
So if I understand correctly, you got a Form loaded from a JSON, which you get by a HTTP request, which is rendered for a user A.

Now user A fills out the form and wants to send the update to the server.

At this point you have 2 possible ways.

1. Use the `JSON.stringify(...)` like mentioned here: https://github.com/udos86/ng-dynamic-forms#json-export--import
2. Iterate through the `FormGroup` and grab all the `id: value`  pairs.

The result can be send back to the server and be used for updates.

**Comment by KSingh1980** [comment]
@Karamuto  - You are right so far but my question is if I have to update the values after saving for the second time- How do I map those values to the control to JSON form controls which renders at run-time. First time saving value, I am able to handle. I appreciate your response.

**Comment by udos86** [comment]
Closed due to inactivity

@Karamuto Thanks for your support
