### ISSUE TITLE
Adding functionality to DynamicFormService to get/set the control values.

### ISSUE THREAD

**Issue by KSingh1980** [udos86/ng-dynamic-forms#830]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: latest

[x] Core 
[x] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

It would be great if there is two more method/function in the DynamicFormService which can set the values of the controls from the JSON object or TypeScript object and other to get it .
For example 
**DynamiFormService.getCurrentFormValues(); returns the jsonObject
DynamicFormService.setCurrentFormValues(jsonObject); pass the jsonObject**

This jsonObject should map exactly same as form model.  Once user gets the object, he can do the rest of the processing as per requirement. Every use-case needs such functionality and setting individual controls values is kinda duplicating the effort  in each case. It will cover 80% of use-cases where it can be used without any hassle ,for other complex scenarios, developers can still use as they are using it by iterating and setting values/reading values from them.

**Comment by Karamuto** [comment]
Hello @KSingh1980 ,

I am not sure what your proposel would mean. A set/get for the values in the DynamicFormService doen't make any sense, as they are not bound to the used `FormModel` its more like a utility Service.

Also there is no way around iterating over the `FormControl`'s to get their values. The service would do the same for a function:  `DynamiFormService.getFormValues(formModel); Array<ControlValue>`

**Comment by sarora2073** [comment]
(was asked to comment) and I agree with the previous comment. As i understand this library, the dynamic form service doesn't have knowledge of the instantiated form's data, so asking the service for the data isn't possible. 

You might be able to write your own shared method (e.g. in a shared utils.ts file) if you're writing the same code over and over, and you can pass the instance data to that shared method. 

I'm not sure if such a method will be of general interest, and therefore worth adding to the library, but if you think it will please share the code.

**Comment by udos86** [comment]
@KSingh1980 

@Karamuto @sarora2073 

Thank you both for pointing out that `DynamicFormService` is not coupled to form model itself.

This has been designed intentionally and should be no subjcet to change.
