### ISSUE TITLE
UI package change should not require changes in markup

### ISSUE THREAD

**Issue by ntziolis** [udos86/ng-dynamic-forms#832]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[x] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[x] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
UI package selection should not be manifested in markup as it makes the code significantly less reusable and error prone as every dev on the project always needs to remember to use the correct component name addition.

Instead it should be configurable on project level. Optimally it doesn't need to be configured at all and just my adding the UI module the core library gets informed of the specific UI package to use see implementation of `formly` and its UI extensions.

**Comment by Karamuto** [comment]
Hello @ntziolis ,
I think what you mean is that the component tags have a UI specififc name? This isn't really that bad a markup change as this normally only applies to one line of markup. Also with this you would lose the abillity to use multiple UI libararies in you application ( if anyone does this )

**Comment by udos86** [comment]
@ntziolis Thanks for this proposal.

However, as @Karamuto already pointed out, at the moment there are no strong reasons for this to be a must-have feature.
