### ISSUE TITLE
UI-MATERIAL - missing 'angular-2-text-mask' peer dependency

### ISSUE THREAD

**Issue by sgabb** [udos86/ng-dynamic-forms#834]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.9`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi!
While building the app this error occurred:
_ERROR in ./node_modules/@ng-dynamic-forms/ui-material/fesm5/ui-material.js
Module not found: Error: Can't resolve 'angular2-text-mask' in 'D:\Development\Projects\sdm\sdm-app\node_modules\@ng-dynamic-forms\ui-material\fesm5'_

Seems like the 'angluar-2-text-mask' dependency is not listed in the ui-material package (same problem present in another issue already fixed with the bootstrap-ui):
"peerDependencies": {
    "@angular/common": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/material": "^6.0.0",
    "@ng-dynamic-forms/core": "^6.0.9",
    "rxjs": "^6.0.0"
  },

Temporary solution is, of course, to install the package manually:
_npm i angular2-text-mask --save_

Bests,

Gabrio

**Comment by udos86** [comment]
@sgabb

> Temporary solution is, of course, to install the package manually:
> npm i angular2-text-mask --save 

Works as designed. Please get familiar with the concept of [peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/).

**Comment by sgabb** [comment]
@udos86 
I'm sorry, I forgot that the peer dependency should be installed "manually". However the "problem" remains and it seems the same one of this other issue: #398 but related to the Material UI.
Indeed, after installing **_@ng-dynamic-forms/ui-bootstrap_** I get a "_npm WARN @ng-dynamic-forms/ui-bootstrap@6.0.9 requires a peer of angular2-text-mask@^9.0.0 but none is installed. You must install peer dependencies yourself._", while after installing the **_@ng-dynamic-forms/ui-material_** no npm warning is displayed.
Is this correct?

**Comment by Amirroracle** [comment]
Having the same issue where yes installing the dependency solved the issue but it was never listed as a peer dependency at all.

**Comment by jcianci12** [comment]
I had the same issue. Might just be my noob level of experience with angular. Found the fix from googling the error.
