### ISSUE TITLE
Relation Field Result operation 

### ISSUE THREAD

**Issue by stekontar** [udos86/ng-dynamic-forms#839]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[Χ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.10`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[Χ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hello,
is it possible to add more functionality in a relation field?
As requirement I have to create a field that its value is the result of the math OR logical operator of two (or more)  fields. 
Its value should be changing at run time.

e.g
lets say we have 3 fields with values
in case of number
A=5, B=7, C=null
field C value would be completed with 
A + B => 5 + 7 = 12
A - B => 5 - 7 = -2
A * B => 5 *7 =35
A / B => 5/ 7 = 0.71

in case of stirng 
A="foo" B="bar" C=null
A + B => foo + bar = foo bar"

in case of boolean 
A=true, B=false, C=null
A && B => true && false = false
A || B => true || false = true

As a model patern the following one could support it
```
relation: [
                    {
                        action: "RESULT",
                        type: "MATH" or "LOGICAL"
                        connective: "+" , "-" , "*" , "/" , "OR" , "AND",
                        when: [
                            {
                                id: "inputField1"
                            }, 
                            {
                                id: "inputField2"
                            }
                        ]
                    }
                ],
```

My thoughts are going farther by supporting custom operation between fields like
 
```
relation: [
                    {
                        action: "RESULT",
                        type: "LOGICAL"
                        when: [
                         AND: [{
                            AND: [
                                  { id: "inputField1" }, 
                                 {  id: "inputField2" }
                            ],
                            OR: [
                                  { id: "inputField3" }, 
                                 {  id: "inputField4" }
                            ]
                         }]
                    }
                ],

```

```
relation: [
                    {
                        action: "RESULT",
                        type: "MATH" 
                        when: [
                         "*": [{
                            "+" : [
                                  { id: "inputField1" }, 
                                 {  id: "inputField2" }
                            ],
                            "-" : [
                                  { id: "inputField3" }, 
                                 {  id: "inputField4" }
                            ]
                         }]
                    }
                ],


```

Thank you,
S.

**Comment by udos86** [comment]
_starting with `8.0.0` you'll be able to implement your custom action to achieve this_
