### ISSUE TITLE
UI-PrimeNg: Use prime-icons instead of fontAwesome-icons

### ISSUE THREAD

**Issue by jasperbosch** [udos86/ng-dynamic-forms#845]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description
Since PrimeNg V6 FontAwesome is no longer used. The alternative is primeicons.
These primeicons have a prefix of 'pi' instead of 'fa'.
Now no icons are shown.
This problem is detected in the calendar.

**Comment by udos86** [comment]
@jasperbosch 

Thanks for reporting this. I'll deliver a patch as quick as possible.
