### ISSUE TITLE
ng-templates for modelType ARRAY are not rendered when using dynamic-primeng-form-control

### ISSUE THREAD

**Issue by Silentscripter** [udos86/ng-dynamic-forms#846]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.10`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[X] Prime NG
</code></pre>

## Description
When using dynamic-primeng-form-control directly instead of dynamic-primeng-form the ng-templates with modelType="ARRAY" are not rendered.

**Comment by udos86** [comment]
@Silentscripter 

This is no bug and works as designed as `dynamic-primeng-form-control` expects you to manually bind `templates`.

Has already been discussed #790
