### ISSUE TITLE
Unable to use a directive for dynamic forms

### ISSUE THREAD

**Issue by regstar** [udos86/ng-dynamic-forms#852]
## I'm submitting a

<pre><code>
[X ] Bug / Regression
[ ] Feature Request / Proposal
[X ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[X] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I'm unable to access a directive with a dynamic formula. Reactive form components or html written inputs will work correctly. 

Small example:
```javascript
import {Directive, ElementRef, Input, AfterViewInit} from "@angular/core";

@Directive({
  selector: "[formControlName]"
})
export class TestDirective implements AfterViewInit {

  constructor(private elementRef: ElementRef) {
    console.log("TestDir: constructor");
  }

  ngAfterViewInit() {
    console.log("TestDir: ngAfterViewInit");
  }
}
```

Other selectors like id or own classes don't work too. I want to access the nativeElement of a dynamic formula input field e.g. to set the focus on a element.

**Comment by udos86** [comment]
@regstar 

Thank you for reporting this. 

Please give me some time to take a closer look at what is is possibly going wrong here.

**Comment by regstar** [comment]
I don't want to use directives only for this reason. We have a lot more to do with directives and not only set the focus.

@udos86 Is there any new status for this issue? 

Thanks a lot for any informations!

**Comment by regstar** [comment]
Hello @Karamuto 

Thx for your help. This merge will not fix my directive problem. I cannot access via directive to a dynamic form element. 

Thx for the help.

**Comment by Karamuto** [comment]
Hello @regstar ,

this may be true, but you could do the same things to the form control element as a directive would. What exactly do you try to accomplish?

**Comment by udos86** [comment]
closed due to no longer being active
