### ISSUE TITLE
Custom template does not work for ARRAY type in NG boostrap

### ISSUE THREAD

**Issue by neil-coutinho** [udos86/ng-dynamic-forms#857]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.2.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm trying to add a remove item link for my DynamicFormArrayModel form controls. In my template

```
  <dynamic-ng-bootstrap-form-control 
      [group]="formGroup"
      [model]="formModel">

    <ng-template modelId="myFormArray">
        <button type="button" (click)="onClick()">Label</button>
  </ng-template>


</dynamic-ng-bootstrap-form-control>
```

My formModel is as follows

```
const formModel: DynamicFormControlModel[] = [

    new DynamicFormArrayModel({

    id: "myFormArray",
    initialCount: 5,
    groupFactory: () => {
        return [
            new DynamicInputModel({
                id: "myInput",
                label: "My Input"
            })
        ];
    }
 })
];

```

The remove item link does not show up beside each form - control.

**Comment by neil-coutinho** [comment]
@udos86 Sorry, resolved this using <dynamic-ng-bootstrap-form> instead. 
QUESTION: Could I do the same with dynamic-ng-bootstrap-form-control?, If so how?

**Comment by udos86** [comment]
@neil-coutinho 

This has been discussed already in #790 and #846

**Comment by neil-coutinho** [comment]
@udos86 @Karamuto discovered a bug when using  dynamic-ng-bootstrap-form with ng-template for an array.
If the initialCount of the array is set to 0 the ng-template does not render. Works only if initial count is 1

```
<form [formGroup]="formGroup">
      <dynamic-ng-bootstrap-form [group]="formGroup" [model]="formModel">
         <ng-template modelType="ARRAY" let-index="index" let-context="context">CONTENT DOES NOT SHOW IF ARRAY INITIAL COUNT  == 0</ng-template>
   </dynamic-ng-bootstrap-form>
</form>

```

Any help?

**Comment by rockeshub** [comment]
I think you need to keep initial count as 1 for array type to work.

**Comment by neil-coutinho** [comment]
@rockeshub right, but then when you submit the form, NULL values are submitted for input models within a DynamicFormArrayModel

**Comment by rockeshub** [comment]
Ya your right. I have written a filter that would check for null and only
then add my form fields to my request body.
