### ISSUE TITLE
[Doc] Remove reference to ng eject

### ISSUE THREAD

**Issue by maroy1986** [udos86/ng-dynamic-forms#860]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.2.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I'm proposing a modification to the documentation to remove any reference of `ng eject` from the documentation in the custom validators. I got confused by this and miss the part following it talking about providing the `NG_VALIDATORS`. While it's entirely my fault, I found this was confusing and that it might confuse more peoples.

`ng eject ` has been removed from the CLI starting from version 6 following the changes made to the way the CLI use web pack. It is intended to come back in the future but for now, it's not there. Hence, I think the documentation shouldn't mention it. Furthermore, you clearly say that this is a bad practice. Although it's good to highlight that fact, I think we shouldn't even mention it since you provide a way better alternative to it that is way more clean to my opinion.

**Comment by udos86** [comment]
@maroy1986 Thanks for the exemplary contribution.

closed by #867
