### ISSUE TITLE
Can't disable DynamicInputModel

### ISSUE THREAD

**Issue by gibranshah** [udos86/ng-dynamic-forms#862]
## I'm submitting a

<pre><code>
[ X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
[x] Core
</code></pre>

## Description
Hello,

I’m using angular’s DynamicInputModel (from node_modules/@ng-dynamic-forms/core/src/model/input/dynamic-input.model.d.ts).

I’ve got this code which is supposed to disable all my DynamicInputModel controls on the form:

frmScrn.FormElements.forEach(element => {
     element.disabled = true;
});

But this doesn’t always works.

Is anyone aware of any cases where disabling a DynamicInputModel doesn’t work?

**Comment by udos86** [comment]
@gibranshah 

Please follow the docs: https://github.com/udos86/ng-dynamic-forms#disabling-form-controls

**Comment by gibranshah** [comment]
Thanks udos86, but unfortunately that didn't work.
