### ISSUE TITLE
fxFlex support?

### ISSUE THREAD

**Issue by calchuchesta** [udos86/ng-dynamic-forms#863]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ X ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.2.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ X ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I need to use [fxFlex](https://github.com/angular/flex-layout/wiki/fxFlex-API) on my inputs. I've tried adding the `fxFlex` attributes through the `additional` configuration object but it doesn't seem to be doing anything. My goal is to use `ng-dynamic-forms` to let the user design their own form layouts and `fxFlex` is being used everywhere in my application, so I'd love to be able to use it with `ng-dynamic-forms` as well.

**Comment by udos86** [comment]
@calchuchesta Hi!

I'm afraid there's no chance of supporting this since there are no dynamic directives in Angular so far.

You would have to create your own UI package in order to make use of this.
