### ISSUE TITLE
[ui-ng-bootstrap] update @ng-bootstrap/ng-bootstrap to v4

### ISSUE THREAD

**Issue by paulsouche** [udos86/ng-dynamic-forms#872]
## I'm submitting a

<pre><code>
[X] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[X] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Since `angular@7` is out, `@ng-bootstrap/ng-bootstrap` released a v4. As `@ng-dynamic-forms/ui-ng-bootstrap` [requires a v2](https://github.com/udos86/ng-dynamic-forms/blob/master/packages/ui-ng-bootstrap/package.json#L36), there is a peer conflict

**Comment by udos86** [comment]
@paulsouche 

Thanks, Paul, for reporting this!
