### ISSUE TITLE
ui builder for dynamic forms

### ISSUE THREAD

**Issue by bobingham** [udos86/ng-dynamic-forms#874]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.0`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description

Excellent library, I have been using it for some time in my solution.  I have now got the stage where I want to build my forms dynamically using the UI (as per google forms, form.io etc).  Has anyone in the community carried out such a task?  If so would they be willing to share?  If there are no such extensions available is anyone interested in building one?

**Comment by seshukumar291** [comment]
well I'm interested to build one

**Comment by bobingham** [comment]
I have sent a private email to Udo to ask whether he is interested in taking the project further privately, offering the solution as open-source.  Once I have a reply I will keep you updated.  I am offering someone a paid project here with a fairly precise specification once a basis of understanding has been reached.
Udo????

**Comment by Robinyo** [comment]
@bobingham 

See: [Angular for Designers initiative](https://blog.angular.io/moving-design-beyond-pictures-1509c315f94e)

![1_zj3oy19h-spfiddvpfu3uq](https://user-images.githubusercontent.com/12203540/48461014-bef59680-e825-11e8-9c41-4badd33d987e.gif)
