### ISSUE TITLE
README.md typos

### ISSUE THREAD

**Issue by Robinyo** [udos86/ng-dynamic-forms#877]
## I'm submitting a
<pre><code>
[x] Bug / Regression
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `7.0.0`
[x] Material  
</code></pre>

## Description
There are a couple of typos in the project's  README.md.

Basic Usage -> 2. Define your form model:

```
// export const MY_FORM_MODEL: DynamicFormModel = [
export const MY_FORM_MODEL: DynamicFormControlModel[] = [

```

Basic Usage -> 3. Create a FormGroup via DynamicFormService:

```
// formModel: DynamicFormModel = MY_FORM_MODEL;
formModel: DynamicFormControlModel[] = MY_FORM_MODEL;
```

**Comment by udos86** [comment]
@Robinyo 

Can't see any typos here? 

`DynamicFormModel` is a type alias for `DynamicFormControlModel[]`;

**Comment by Robinyo** [comment]
OK, then won't you need to import it (in steps 2 and 3) in order to use it?

```
import {
    DynamicFormModel,
    // DynamicFormControlModel,
    DynamicCheckboxModel,
    DynamicInputModel,
    DynamicRadioGroupModel
} from "@ng-dynamic-forms/core";
```

**Comment by udos86** [comment]
@Robinyo Yes, you're right. I'll correct it.
