### ISSUE TITLE
material autocomplete does not filter

### ISSUE THREAD

**Issue by rattkin** [udos86/ng-dynamic-forms#878]
<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: sample version
http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
The material autocomplete does not filter. I think You already fixed this? #829

**Comment by udos86** [comment]
@rattkin 

Before filing a bug please provide some insight in how you're trying to achieve this.

Are you filtering via `list` Observable?

**Comment by rattkin** [comment]
I'm going to Your example: http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form
Autocomplete doesn't work. When I download the tutorial source, it does not work as well.

Now when you mention it, there is no filtering function. Do you please have an example how to add filtering?

**Comment by udos86** [comment]
@rattkin 

As of now Autocomplete does not provide a default filtering mechanism. It's up to you to implement it based on your requirements.

Simply make use of `valueChanges` Observable of your autocomplete form control and update the `list` property of your `DynamicInputModel` based on the user input.
