### ISSUE TITLE
TypeError: "path.split is not a function" (using API)

### ISSUE THREAD

**Issue by PiotrFerenc** [udos86/ng-dynamic-forms#881]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `^7.0.1`

[ ] Basic UI
[x] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
getting dynamic form from api i have many errors and when i click input (pic1) show form (pic2). I don't know why and plz  help me :) 

ts:
<code><pre>formModel: DynamicFormControlModel[] ;
  formGroup: FormGroup;

//constructor
  this.http.get<any>('http://localhost:5000/api/form?TableName=cities&Name=cities').subscribe(formModelJson => {
      this.formModel = this.formService.fromJSON(formModelJson.data);
      this.formGroup = this.formService.createFormGroup(this.formModel);
    });</code></pre>
html:
<code><pre>
```
<form [formGroup]="formGroup">
  <dynamic-bootstrap-form [group]="formGroup" [model]="formModel"></dynamic-bootstrap-form>
</form>
```
</code></pre>
errors:<code><pre>
ERROR Error: "formGroup expects a FormGroup instance. Please pass one in.

       Example:

       
    <div [formGroup]="myGroup">
      <input formControlName="firstName">
    </div>

    In your class:

    this.myGroup = new FormGroup({
       firstName: new FormControl()
    });"
	missingFormException http://localhost:4200/vendor.js:57088:15
	_checkFormPresent http://localhost:4200/vendor.js:60592:13
	ngOnChanges http://localhost:4200/vendor.js:60502:9
	checkAndUpdateDirectiveInline http://localhost:4200/vendor.js:53165:9
	checkAndUpdateNodeInline http://localhost:4200/vendor.js:54433:20
	checkAndUpdateNode http://localhost:4200/vendor.js:54395:16
	debugCheckAndUpdateNode http://localhost:4200/vendor.js:55029:19
	debugCheckDirectivesFn http://localhost:4200/vendor.js:54989:13
	View_PanelComponent_0 ng:///AppModule/PanelComponent.ngfactory.js:35:5
	debugUpdateDirectives http://localhost:4200/vendor.js:54981:12
	checkAndUpdateView http://localhost:4200/vendor.js:54377:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execComponentViewsAction http://localhost:4200/vendor.js:54560:13
	checkAndUpdateView http://localhost:4200/vendor.js:54383:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execEmbeddedViewsAction http://localhost:4200/vendor.js:54581:17
	checkAndUpdateView http://localhost:4200/vendor.js:54378:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execComponentViewsAction http://localhost:4200/vendor.js:54560:13
	checkAndUpdateView http://localhost:4200/vendor.js:54383:5
	callWithDebugContext http://localhost:4200/vendor.js:55271:22
	debugCheckAndUpdateView http://localhost:4200/vendor.js:54949:12
	detectChanges http://localhost:4200/vendor.js:52758:13
	tick http://localhost:4200/vendor.js:49420:58
	tick http://localhost:4200/vendor.js:49420:13
	next http://localhost:4200/vendor.js:49311:99
	invoke http://localhost:4200/polyfills.js:2733:17
	onInvoke http://localhost:4200/vendor.js:48692:24
	invoke http://localhost:4200/polyfills.js:2732:17
	run http://localhost:4200/polyfills.js:2483:24
	run http://localhost:4200/vendor.js:48606:16
	next http://localhost:4200/vendor.js:49311:69
	schedulerFn http://localhost:4200/vendor.js:44787:36
	__tryOrUnsub http://localhost:4200/vendor.js:120210:13
	next http://localhost:4200/vendor.js:120148:17
	_next http://localhost:4200/vendor.js:120091:9
	next http://localhost:4200/vendor.js:120068:13
	next http://localhost:4200/vendor.js:119833:25
	emit http://localhost:4200/vendor.js:44771:54
	checkStable http://localhost:4200/vendor.js:48661:13
	onHasTask http://localhost:4200/vendor.js:48705:21
	hasTask http://localhost:4200/polyfills.js:2786:21
	_updateTaskCount http://localhost:4200/polyfills.js:2806:17
	_updateTaskCount http://localhost:4200/polyfills.js:2630:34
	runTask http://localhost:4200/polyfills.js:2550:25
	drainMicroTaskQueue http://localhost:4200/polyfills.js:2940:25
PanelComponent.html:5
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 4, nodeDef: {…}, elDef: {…}, elView: {…} }
PanelComponent.html:5
View_PanelComponent_0
PanelComponent.html:5
proxyClass
compiler.js:17129
./node_modules/@angular/core/fesm5/core.js/DebugContext_.prototype.logError
core.js:20684
./node_modules/@angular/core/fesm5/core.js/ErrorHandler.prototype.handleError
core.js:12637
./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.tick/<
core.js:14878:54
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke
zone.js:388
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run
zone.js:138
./node_modules/@angular/core/fesm5/core.js/NgZone.prototype.runOutsideAngular
core.js:14102
./node_modules/@angular/core/fesm5/core.js/ApplicationRef.prototype.tick
core.js:14878
next/<
core.js:14762:97
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke
zone.js:388
onInvoke
core.js:14143
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke
zone.js:387
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run
zone.js:138
./node_modules/@angular/core/fesm5/core.js/NgZone.prototype.run
core.js:14057
next
core.js:14762:67
./node_modules/@angular/core/fesm5/core.js/EventEmitter.prototype.subscribe/schedulerFn<
core.js:10238:34
./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub
Subscriber.js:196
./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.next
Subscriber.js:134
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype._next
Subscriber.js:77
./node_modules/rxjs/_esm5/internal/Subscriber.js/Subscriber.prototype.next
Subscriber.js:54
./node_modules/rxjs/_esm5/internal/Subject.js/Subject.prototype.next
Subject.js:47
./node_modules/@angular/core/fesm5/core.js/EventEmitter.prototype.emit
core.js:10222:52
checkStable
core.js:14112
onHasTask
core.js:14156
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.hasTask
zone.js:441
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype._updateTaskCount
zone.js:461
./node_modules/zone.js/dist/zone.js/</Zone.prototype._updateTaskCount
zone.js:285
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask
zone.js:205
drainMicroTaskQueue
zone.js:595
ERROR TypeError: "path.split is not a function"
	_find http://localhost:4200/vendor.js:58023:16
	get http://localhost:4200/vendor.js:58496:62
	ngOnChanges http://localhost:4200/vendor.js:88979:55
	checkAndUpdateDirectiveInline http://localhost:4200/vendor.js:53165:9
	checkAndUpdateNodeInline http://localhost:4200/vendor.js:54433:20
	checkAndUpdateNode http://localhost:4200/vendor.js:54395:16
	debugCheckAndUpdateNode http://localhost:4200/vendor.js:55029:19
	debugCheckDirectivesFn http://localhost:4200/vendor.js:54989:13
	View_DynamicBootstrapFormComponent_1 ng:///DynamicFormsBootstrapUIModule/DynamicBootstrapFormComponent.ngfactory.js:45:5
	debugUpdateDirectives http://localhost:4200/vendor.js:54981:12
	checkAndUpdateView http://localhost:4200/vendor.js:54377:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execEmbeddedViewsAction http://localhost:4200/vendor.js:54581:17
	checkAndUpdateView http://localhost:4200/vendor.js:54378:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execComponentViewsAction http://localhost:4200/vendor.js:54560:13
	checkAndUpdateView http://localhost:4200/vendor.js:54383:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execComponentViewsAction http://localhost:4200/vendor.js:54560:13
	checkAndUpdateView http://localhost:4200/vendor.js:54383:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execEmbeddedViewsAction http://localhost:4200/vendor.js:54581:17
	checkAndUpdateView http://localhost:4200/vendor.js:54378:5
	callViewAction http://localhost:4200/vendor.js:54618:21
	execComponentViewsAction http://localhost:4200/vendor.js:54560:13
	checkAndUpdateView http://localhost:4200/vendor.js:54383:5
	callWithDebugContext http://localhost:4200/vendor.js:55271:22
	debugCheckAndUpdateView http://localhost:4200/vendor.js:54949:12
	detectChanges http://localhost:4200/vendor.js:52758:13
	tick http://localhost:4200/vendor.js:49420:58
	tick http://localhost:4200/vendor.js:49420:13
	next http://localhost:4200/vendor.js:49311:99
	invoke http://localhost:4200/polyfills.js:2733:17
	onInvoke http://localhost:4200/vendor.js:48692:24
	invoke http://localhost:4200/polyfills.js:2732:17
	run http://localhost:4200/polyfills.js:2483:24
	run http://localhost:4200/vendor.js:48606:16
	next http://localhost:4200/vendor.js:49311:69
	schedulerFn http://localhost:4200/vendor.js:44787:36
	__tryOrUnsub http://localhost:4200/vendor.js:120210:13
	next http://localhost:4200/vendor.js:120148:17
	_next http://localhost:4200/vendor.js:120091:9
	next http://localhost:4200/vendor.js:120068:13
	next http://localhost:4200/vendor.js:119833:25
	emit http://localhost:4200/vendor.js:44771:54
	checkStable http://localhost:4200/vendor.js:48661:13
	onLeave http://localhost:4200/vendor.js:48728:5
	onInvokeTask http://localhost:4200/vendor.js:48686:17
	invokeTask http://localhost:4200/polyfills.js:2765:17
	runTask http://localhost:4200/polyfills.js:2533:28
	invokeTask http://localhost:4200/polyfills.js:2841:24
	invokeTask http://localhost:4200/polyfills.js:3885:9
	globalZoneAwareCallback http://localhost:4200/polyfills.js:3911:17
DynamicBootstrapFormComponent.html:1
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…} }
</code></pre>

response from API:
<code><pre>
 {"errors":[],"data":[{"id":0,"name":"CityId","label":"CityId","type":"INPUT","inputType":"number"},{"id":1,"name":"Name","label":"Name","type":"INPUT"},{"id":2,"name":"StateId","label":"StateId","type":"INPUT","inputType":"number"}],"success":true}
</code></pre>

 view on start (pic1)
![obraz](https://user-images.githubusercontent.com/30370747/48258916-a5fc7800-e416-11e8-9d66-acfe457dcd9e.png)

view on click (pic2)
![obraz](https://user-images.githubusercontent.com/30370747/48258947-bdd3fc00-e416-11e8-820a-1d689a466c7e.png)

**Comment by Karamuto** [comment]
Hello @PiotrFerenc ,

the TypeError is just an inherited error. The real problem here is this one:

`ERROR Error: "formGroup expects a FormGroup instance. Please pass one in.`

From this I can suspect a timing problem ( remeber that a http request is asynchronus )

My solution, try this in your html: 

<code>
<form *ngIf="formGroup" [formGroup]="formGroup">
  <dynamic-bootstrap-form [group]="formGroup" [model]="formModel"></dynamic-bootstrap-form>
</form>
<code>

This will only try to render you form, when the data / form has succesfully been requested

**Comment by Karamuto** [comment]
I guess the problem is solved as you didn't ask anymore.
