### ISSUE TITLE
Custom component not registered, provider function not called

### ISSUE THREAD

**Issue by StefanKoenigMUC** [udos86/ng-dynamic-forms#882]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hi all,

i tried to setup a custom component for use with ng-dynamic-forms. So far it's "working". I think my problem is not really located within dynamic-forms, it's more or less a problem with angular.

Adding the component to the app.module,: 

`  providers: [
    {
      provide: DYNAMIC_FORM_CONTROL_MAP_FN, useValue: (model: DynamicFormControlModel): Type<DynamicFormControl> | null => {
        console.log('MODEL.TYPE' + model.type);
        switch (model.type) {
          case 'SELECT_ENTITY': // DynamicSelectEntityFormControlModel.type /* corresponding DynamicFormControlModel */:
            return DynamicSelectEntityFormControlComponent;
        }
      }
    }, ...]`

does not work, as the code is never called (Breakpoint not reached, Output not shown).

Is there anything additional to do for getting this to work?

thanks in advance for your help,
stefan

**Comment by StefanKoenigMUC** [comment]
According to this problem i had a further look into the code:

I recognized the "fromJSON" function within the DynamicFormService. As i understood correct, there is actual no way to initiate custom form components via JSON documents? As the document is only checkde for built in data types?

**Comment by Karamuto** [comment]
Hello @StefanKoenigMUC ,
indeed thats right, I also needed to add additional types, but for my case I have extended the 'DynamicFormsService' and redefined the 'fromJSON' method to accept my types.

Lastly I provided the service with: { provide: DynamicFormsService, useClass: <myExtension>}

**Comment by Karamuto** [comment]
@StefanKoenigMUC ,

could my suggestion resolve your problem?

**Comment by StefanKoenigMUC** [comment]
@Karamuto 
oh sorry, i have not seen your reply :-( I'll give it a try within the next few days (loaded with appointments until 2019..)
Thanks for your help!

**Comment by Karamuto** [comment]
Will close this as you havn't posted your results here for a while.
