### ISSUE TITLE
Error from DynamicBootstrapFormArrayComponent in prod build 

### ISSUE THREAD

**Issue by mmirzaeyan** [udos86/ng-dynamic-forms#884]
## I'm submitting a

<pre><code>
[* ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ * ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
when i try build my project in prod mode take this error : 
ERROR in node_modules\@ng-dynamic-forms\ui-bootstrap\ui-bootstrap.d.ts.DynamicBootstrapFormArrayComponent.html(12,45): : Property 'at' does not exist on type 'FormControl'.
node_modules\@ng-dynamic-forms\ui-bootstrap\ui-bootstrap.d.ts.DynamicBootstrapFormControlContainerComponent.html(17,50): : Property 'hint' does not exist on type 'DynamicFormControlModel'

 as i discuss the problem in Gitter i think then problem is : 
I would suspect the library is indeed at fault here. Since there is no casting in dynamic-bootstrap-form-array.component.html, and the type FormControlindeed doesn't have a function at.

**Comment by udos86** [comment]
I cannot verify any bug here related to the library itself.

**Comment by plathub** [comment]
@udos86 I have the same problem with PrimeNG:
```
dynamic-primeng-form-array.component.html(14,47): : Property 'at' does not exist on type 'FormControl'.
```
the respective line 14 is 
```
[group]="control.at(idx)"
```

Where should `at()` point to? Can't see why or how this expressions should work?

**Comment by udos86** [comment]
@plathub You're right!

ng-packagr uses `fullTemplateTypeCheck: true` property under the hood which causes the build to break.
