### ISSUE TITLE
How to use functions with text-mask

### ISSUE THREAD

**Issue by rodrigopoi** [udos86/ng-dynamic-forms#885]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.1`

[X] Basic UI
[X] Bootstrap UI  
[X] Foundation UI
[X] Ionic UI
[X] Kendo UI
[X] Material  
[X] NG Bootstrap
[X] Prime NG
</code></pre>

## Description

How to use functions with text-mask?

Example:
https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#mask

**Comment by Karamuto** [comment]
Should be resolved when #891 is merged into master and new version is out.
