### ISSUE TITLE
Checkboxes are broken when there are multiple forms with same form model

### ISSUE THREAD

**Issue by josduj** [udos86/ng-dynamic-forms#887]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: 7.0.1

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Checkboxes are broken when there are multiple forms with same form model.

**Demo**: https://stackblitz.com/edit/angular-5d4h5k  
**Steps to reproduce**: Toggle the checkbox on second card. Checkbox from first card is updated, while the second one remains unchanged.

---

I can understand why this shouldn't be working, since both checkboxes have same id (which isn't valid HTML), but other controls seem to work well. Maybe I'm just doing this the wrong way, but is there a way multiple forms can use same form model?

**Comment by Karamuto** [comment]
Hello @josduj ,

I am actually kinda surprised that the inputs are working. As you kinda mentioned they share the same FormControlModel, which means they have the same object which stores the value. This will result in unexpected behavior.

So there are 2 options to solve this:

1. Create another model, or write a function which creates your model and returns it.
2. Use a FormArray,

**Comment by josduj** [comment]
@Karamuto

They actually don't use the same instance since it's cloned once components are initialized.

```javascript
const jsonModel = JSON.stringify(FORM_MODEL);
this.formModel = this.formService.fromJSON(jsonModel);
```
If I were to create another model, I would still need to use the same ids so I guess to problem would still be present with the checkboxes?

A dirty solution would be to replace the control ids with unique ones once the model is cloned, and revert them before value is submitted.

**Comment by udos86** [comment]
@josduj @Karamuto 

I'm having a hard time classifying this as a bug cause you're intentionally creating invalid HTML which ultimately leads to described misbehavior.

As @Karamuto pointed out you better should make use of a `DynamicFormArrayModel` here.
