### ISSUE TITLE
Error during production build / asynch could not be found

### ISSUE THREAD

**Issue by StefanKoenigMUC** [udos86/ng-dynamic-forms#892]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
When with 
`ng build --prod`

i'm getting the follwing error:

`ERROR in : Template parse errors:
The pipe 'async' could not be found ("
    <datalist *ngIf="model.hasList" [id]="model.listId">

        <option *ngFor="let op[ERROR ->]tion of model.list$ | async" [value]="option">

    </datalist>
"): ....@ng-dynamic-forms/ui-ng-bootstrap/ui-ng-bootstrap.d.ts.DynamicNGBootstrapInputComponent.html@41:30`

**Comment by udos86** [comment]
Closed as not related to any bug in the library itself.
