### ISSUE TITLE
valueUpdates.next() on Select models

### ISSUE THREAD

**Issue by dkzeb** [udos86/ng-dynamic-forms#893]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi, im doing a project using ng-dynamic-forms, with a bunch of DynamicSelectModel based controls

When i use valueUpdates.next() the form control is not updated visually if i use a value (i can see that the model actually updates but the control does not (i have seen other issues on here - but they don't fit what im seeing)

If i use 'null' as a value (all my form controls have a null value to show a "please select ..." message in the form) - both control and model is updated - but if i use a string only the model updates, not the control

Any ideas? It kind of seems like that the control doesnt recognize the value (the control is just blank) however, if i click the control i can see the correct value highlighted

valueUpdates.next works on regular DynamicInputModels (and their controls) but not on selects...

Regards
Sebastian

**Comment by Karamuto** [comment]
Hello @dkzeb ,

this sounds like this problem [here](https://stackoverflow.com/questions/45555533/angular4-ngvalue-does-not-show-selected-value)

Please try providing a 'compareWithFn' for the select.

**Comment by dkzeb** [comment]
Hellp @Karamuto 
I'll try that out - i still think its wierd behavior though :)
I will update this issue with whatever i find out ;) 

Again thx for the reply
