### ISSUE TITLE
using Observable for Options in DynamicSelectModel

### ISSUE THREAD

**Issue by milaad-gh** [udos86/ng-dynamic-forms#895]
## I'm submitting a
[] Bug / Regression
[*] Feature Request / Proposal
[ ] Question

## I'm using
NG Dynamic Forms Version: `7.0.1`

[*] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[*] Prime NG
</code></pre>

## Description
Hi 
i'm have problem with use observable for options and then reading this isso  #763
after that i'm saw your source code in "dynamic-option-control-model.ts" and i'm think if you are subscribe "options$" in project, The problem is fixed
thanks
![capture](https://user-images.githubusercontent.com/45592557/49436512-8fa3cb00-f7ce-11e8-98be-ffc958366400.PNG)

**Comment by Karamuto** [comment]
Hello @milaad-gh,

is this for prime-ng? Its not completly clear wich options you have checked.

In this case I can agree that the prime-ng implementation currently uses the options instead of the observable.

**Comment by milaad-gh** [comment]
@Karamuto 
Thank you for your attention.
yse it is for primeng.
i cant use observable for options in primeng and actually i need to a realted options in dropdown.
"options$" definition as a observable in project (dynamic-option-control-model.ts)  but nowhere is not subscribe.
so when we difinition form model with Observable like this:
![33](https://user-images.githubusercontent.com/45592557/49717464-68d11300-fc6c-11e8-9da3-7140fd254378.PNG)
options of selectModel is empty

**Comment by udos86** [comment]
closed as of #907
