### ISSUE TITLE
Related options in DynamicSelectModel

### ISSUE THREAD

**Issue by milaad-gh** [udos86/ng-dynamic-forms#896]
## I'm submitting a

[ ] Bug / Regression
[*] Feature Request / Proposal
[ ] Question

## I'm using

NG Dynamic Forms Version: `7.0.1`

[*] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[*] Prime NG
</code></pre>

## Description
i'm want to create dependent drop-down (province and city.when user select a option in province,Cities of that province show in the options of city)
in your project we can only use enable or disable in drop-down and if this feture add to "getRelatedFormControls" in "dynamic-form-control-container.component" we can create dependent drop-down
thanks
![capture2](https://user-images.githubusercontent.com/45592557/49438177-cda2ee00-f7d2-11e8-9d15-54b99f728f8b.PNG)

**Comment by Karamuto** [comment]
Is related to #895 ,

when having an Observable you could control the dropdown options with an filter/map operator.

**Comment by milaad-gh** [comment]
hi @Karamuto 
Is this issue fixed in the new version?

**Comment by Karamuto** [comment]
Hello @milaad-gh ,

it should be. Did you try using an Observable for the filter action?

**Comment by milaad-gh** [comment]
Yes, I tried, but the result was not correct and it was empty dropdown
this is my form model :
![Capture](https://user-images.githubusercontent.com/45592557/54978011-a14af180-4fbc-11e9-87aa-5023ffc01096.PNG)
Meanwhile, I have the final version

**Comment by Karamuto** [comment]
Hello @milaad-gh ,

here is a stackblitz which provides an example how this can be realized.

Its far from perfect but I think you will be able to work it out with this ;)

https://stackblitz.com/edit/angular-zw8qp8

**Comment by milaad-gh** [comment]
@Karamuto thanks
