### ISSUE TITLE
JSON "relation" Control Capabilities

### ISSUE THREAD

**Issue by elisahq7** [udos86/ng-dynamic-forms#897]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[x] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Thank you for this amazing library! I am building some robust forms using JSON data ng-dynamic-forms and its is working correctly except when I add a "relation" key to my input object where the "id" is referencing an input with type CHECKBOX. The form builds and there are no errors, but "relation" does not work when it's referencing a checkbox. Also, is there a list of possible "actions" that will work with this capability? I find there is very limited documentation on how to use JSON. Below is an example of my object in my JSON:
{
        "type": "CHECKBOX",
        "id": "ShowAll",
        "label": "Show All Fields",
        "value": false
},{
              "type": "INPUT",
               "id": "Amount",
               "label": "Amount",
               "maxLength": 51,
               "placeholder": "",
               "mask": ["$", "\/[1-9]\/", "\/\\d\/", "\/\\d\/", "\/\\d\/", ".", "\/\\d\/", "\/\\d\/"],
               "relation": [
                   {
                       "action": "DISABLE",
                       "when": [
                           {
                               "id": "ShowAll",
                               "value": true
                           }
                       ]
                   }
               ]
}

Thanks much!

**Comment by elisahq7** [comment]
It would be very helpful to add a **"HIDDEN"** action.

**Comment by obieq** [comment]
@elisahq7 

I just copied your JSON verbatim to my app and it worked just fine.  Given that, the only discernible difference is you're using Basic UI and I'm using Material UI, so that may be the culprit.

**Comment by udos86** [comment]
_major improvements to this will finally be available in `8.0.0`_
