### ISSUE TITLE
Adding a CSS class to all controls within a FormGroup

### ISSUE THREAD

**Issue by CAlex-Wilson** [udos86/ng-dynamic-forms#898]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I recently started using layouts with my forms to remedy breaking CSS for other controls in my application not related to the forms. This CSS breaks my paginator for mat-tables, even though it applies the style I want to my dynamic forms:

```
.mat-form-field {
  width: 95%;
  max-width: 300px;
}
```
Basically, I just want to assign a CSS class to all of my controls inside of a form group. I can accomplish the effect I want like this:

`MyControl: { grid: { control: "test-class" } }`

But this requires me to specify the ID of each control in order for the class to be applied. This is not ideal, as I have controls that get added dynamically at run time.

I saw this issue, [821](https://github.com/udos86/ng-dynamic-forms/issues/821) but I don't think this is exactly what I am looking for. When I try this approach:

```
formLayout: DynamicFormLayout = {
    formGroup: {
      grid: {
        children: "test-class" 
      }
    }
  };
```

This does not apply the "test-class" CSS class to any of the controls in the formgroup. Am I doing this wrong or is there a better way to apply a CSS class for all the controls in my formgroup?

**Comment by Karamuto** [comment]
Hello @CAlex-Wilson ,

could you also provide the formModel?
Without it its hard to recreate your situation.

Greetings

**Comment by CAlex-Wilson** [comment]
```
//FORM LAYOUT - This works, but I have to reference every control's ID
 dynamicFormLayout= { 
    FirstName: {
        grid: {
            control: "test-class"
        }
    },
    LastName: {
        grid: {
            control: "test-class"
        }
    },
    ClientAssignedID: {
        grid: {
            control: "test-class"
        }
    }
};
```

```
//FORM MODEL WITH CUSTOM STYLE
    let dynamicFormModel: DynamicFormControlModel[] = [
      new DynamicInputModel({
        id: "FirstName",
        label: "First Name:",
        maxLength: 50,
        inputType: "text",
        required: true,
        additional: {
          color: "accent"
        },
        autoComplete: "off"
      }),
      new DynamicInputModel({
        id: "LastName",
        label: "Last Name:",
        maxLength: 50,
        inputType: "text",
        required: true,
        additional: {
          color: "accent"
        },
        autoComplete: "off"
      }),
      new DynamicInputModel({
        id: "ClientAssignedID",
        label: "ID:",
        maxLength: 50,
        inputType: "text",
        required: true,
        additional: {
          color: "accent"
        },
        autoComplete: "off"
      }),
    ];
```

@Karamuto here is just one of many. I usually am creating the formModel dynamically based on certain data from my database, but for simplicity sake, here is one of my fixed forms. I have some forms over 20 controls long and I don't always have their defined ID before runtime. So setting up a layout for each of these controls individually is not ideal. More or less, is there a better way to accomplish this at the moment without potentially breaking other CSS in my app using ::ng-deep or global styles? It might be something simple, I just am not aware of it yet.

Thank you for your reply and your time!

**Comment by Karamuto** [comment]
@CAlex-Wilson ,

try wrapping the form controls in a 'DynamicFormGroup' control, this could get a fixed id.

With this you could use the method from #821

**Comment by CAlex-Wilson** [comment]
@Karamuto This works, but it still does not allow me to style the width of the input controls. Here is the what I set up in my app for demo purposes:

```
//LAYOUT
public formLayout: DynamicFormLayout = {
    dialogGroup: {
      grid: {
        children: "test-class-green",
        container: "test-class-blue",
        control: "test-class-yellow"
      }
    }
  };
```
```
// MY CSS
.test-class-green {
  background-color: green !important;
  width: 80% !important;
  margin: auto;
  color: green !important;
}

.test-class-blue {
  background-color: rgba(63, 127, 191, 0.52) !important;
  width: 100% !important;
  margin: auto;
}

.test-class-yellow {
  background-color: rgba(191, 191, 63, 0.52) !important;
  width: 80% !important;
  margin: auto;
}
```

```
// FORM MODEL
 dynamicFormModel: DynamicFormControlModel[] = [
    new DynamicFormGroupModel({
      id: "dialogGroup",
      legend: "Name",
      group: []
    })
  ];
```
```
//FORM MODEL
    let dynamicFormModel: DynamicFormControlModel[] = [
      new DynamicInputModel({
        id: "FirstName",
        label: "First Name:",
        maxLength: 50,
        inputType: "text",
        required: true,
        additional: {
          color: "accent"
        },
        autoComplete: "off"
      }),
      new DynamicInputModel({
        id: "LastName",
        label: "Last Name:",
        maxLength: 50,
        inputType: "text",
        required: true,
        additional: {
          color: "accent"
        },
        autoComplete: "off"
      }),
      new DynamicInputModel({
        id: "ClientAssignedID",
        label: "ID:",
        maxLength: 50,
        inputType: "text",
        required: true,
        additional: {
          color: "accent"
        },
        autoComplete: "off"
      }),
    ];
```
```
/* This is how I am wrapping the dynamicFormModel with the DynamicFormGroupModel. I pass in the dynamicFormModel when I generate my dialog. This works as expected.*/
 
ngOnInit() {
    let inputModel = this.dynamicFormModel[0] as DynamicFormGroupModel;

    this.dialogPassedPayload.dynamicFormModel.forEach(control => {
      inputModel.group.push(control);
    });

    this.formGroup = this.formService.createFormGroup(this.dynamicFormModel);
  }
}

```
Here is a screenshot of the output:
![snip_20181207123119](https://user-images.githubusercontent.com/32232614/49663473-c707b700-fa1c-11e8-8e26-b3589d63021d.png)

This does not affect the width like I want. I am not sure what I am missing. Thanks for the help so far! I hadn't been using the DynamicFormGroupModel.

**Comment by Karamuto** [comment]
@CAlex-Wilson ,

is you css in the components css or globally defined?

If its in the component, the ViewEncapsulation will prevent the styles from work. I would suggest to place them into the global styles, in this case they should work fine.

**Comment by CAlex-Wilson** [comment]
@Karamuto All the styles I posted above are defined in my global styles.scss. The width is never applied, because the classes are not set on the right elements to do so, from what I can tell.

The picture in my last post corresponds to the classes. The background colors match the class names for clarity.

### **Here is my .test-class-green class:**
![green](https://user-images.githubusercontent.com/32232614/49751186-c9674c80-fc7a-11e8-8360-cb4de8241313.png)
### **Here is my .test-class-yellow class:**
![yellow](https://user-images.githubusercontent.com/32232614/49751187-ca987980-fc7a-11e8-8216-9391698887b2.png)
### **Here is my .test-class-blue class:**
![blue](https://user-images.githubusercontent.com/32232614/49751192-ce2c0080-fc7a-11e8-87be-c976668acb79.png)

None of these adjust the width. They just seem like containers for the form itself. The Green class is the exception. It is being applied to the form control labels. The only ways I have been able to adjust the width so far is on `.mat-form-field{}` and when I define styles on every individual object in my formControl.

Thanks!

**Comment by Karamuto** [comment]
@CAlex-Wilson ,

there is actually no good way to specify anything but the main container of the child elements with the specification.

The best way I can think of is creating a mixin which contains this basic styles for  your classes 'child-classes'. For example like this:

```
@mixin form-field-styles($color) {
  .mat-form-field {
     width: 80%;
     margin: auto;
     background-color: $color !important;
  }
}

.test-class-yellow {
  @include form-field-styles(rgba(191, 191, 63, 0.52));
}

...

```

This is just an example, I don't know if I correctly defined the mixin here, but I think you could try it like this.

**Comment by CAlex-Wilson** [comment]
@Karamuto I haven't used `@mixin` before. I think this will work out just fine. You have saved me from a huge headache. Thank you so much!

**Comment by Karamuto** [comment]
@CAlex-Wilson 
you are welcome

**Comment by ankitLu** [comment]
For others who encounter this same issue, for not being able to increase the width of the control, and @mixin is something I haven't tried yet.
The width of controls is restricted because the <input> element is wrapped with a restrictive width <div>
I was able to apply this css (via global stylesheet) on all the controls
`.dynamic-form {
    div {
    width: 200px;
  }
}`

where dynamic-form is my css class on grid controls and contact is ID of my dynamicFormGroupModel
` contact: {
        grid: {
            control: "dynamic-form",
        },`
