### ISSUE TITLE
Rich Text / CKEditor for Material?

### ISSUE THREAD

**Issue by kwoxford** [udos86/ng-dynamic-forms#901]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

What about rich text for Material? CKEditor already has an Angular component but the only way to use it AFAIK is to replace the TextArea component, and of course there are plenty of times when you don't want HTML to appear in your data.

**Comment by Karamuto** [comment]
Hello @kwoxford ,

as this currently only a [proposal](https://github.com/angular/material2/issues/4444) in a prototype state I would be against it. If you still want to add this, you could create you own custom compent. You don't need to replace it if you use my suggestion from #882 .

**Comment by udos86** [comment]
@Karamuto Thanks for clearing this topic!

As long as there is no native Material editor you need to plug in a custom component.
