### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by sunger** [udos86/ng-dynamic-forms#906]
## I'm submitting a

<pre><code>
[ X] Bug / Regression
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `^7.0.2`
[X ] Material  
</code></pre>

## Description
when i add DynamicFormsCoreModule, after build with:
ng build
or
ng build --prod --build-optimizer
than get runtime error on lazy load:

ERROR Error: Uncaught (in promise): Error: Cannot find 'VarsModule' in 

VarsModule is my module name

but when delete DynamicFormsCoreModule ,all is ok,

and with npm start on dev all is ok

my demo:

VarsModule
--------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { SharedModule } from '@ngx-starter-kit/shared';
import { GlobleVarComponent } from './containers/globlevar/globlevar.component';
import { DynamicFormsCoreModule } from '@ng-dynamic-forms/core';
// import { DynamicFormsMaterialUIModule } from '@ng-dynamic-forms/ui-material';

@NgModule({
  imports: [
    CommonModule,
    SharedModule,
    ReactiveFormsModule,
    FormsModule,
    DynamicFormsCoreModule,
    // DynamicFormsMaterialUIModule,
    RouterModule.forChild([
      /* {path: '', pathMatch: 'full', component: InsertYourComponentHere} */
      { path: '', redirectTo: 'vars', pathMatch: 'full' },
      {
        path: 'vars',
        component: GlobleVarComponent,
        data: { title: 'gb', depth: 2 },
      },
    ]),
  ],
  declarations: [GlobleVarComponent],
})
export class VarsModule {}

GlobleVarComponent
---------------------------------------------
import { Component, OnInit } from '@angular/core';
import { MatSnackBar, MatSnackBarConfig } from '@angular/material';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
// import { DateAdapter } from '@angular/material';

declare var outJs: any;

@Component({
  selector: 'app-test-hollo',
  template: `<h1>Hello </h1>`
})
export class GlobleVarComponent implements OnInit {

  constructor(
    private snackBar: MatSnackBar,

  ) {}

  ngOnInit() {

  }

}

**Comment by udos86** [comment]
@sunger 

I cannot relate any bug here to the library itself.
