### ISSUE TITLE
Bindings/Lifecycle Hooks in CustomFormControl are not working 

### ISSUE THREAD

**Issue by iceman91176** [udos86/ng-dynamic-forms#910]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hello & happy new year ;-)

I created my own custom form control with my own model.
I created it as described in the README. I am able to add the control, and it is rendered, but none of my input bindings are passed to my FormControl, and my Lifecyclehooks (ngOnInit) in the Control-Component are not called either.

Just the constructor is called, and that's it.

When adding the CustomFormControl manually (with the model-driven reactive forms approach) it works perfect.

Model-Definition
<pre>
<code>
export const DYNAMIC_FORM_CONTROL_TYPE_SVCITEMCONTACT = "SVCITEMCONTACT";

export interface ServiceItemContactDFCControlModelConfig extends DynamicFormValueControlModelConfig<string> {
    itemId:number;
    requiredContactRoles?:string[];
}

export class ServiceItemContactDFCControlModel extends DynamicFormValueControlModel<string> {
    @serializable() itemId:number;
    @serializable() requiredContactRoles:string[];
    @serializable() readonly type: string = DYNAMIC_FORM_CONTROL_TYPE_SVCITEMCONTACT;
    constructor(config: ServiceItemContactDFCControlModelConfig, layout?: DynamicFormControlLayout) {
        super(config, layout);
        this.itemId = config.itemId;
        this.requiredContactRoles = config.requiredContactRoles || [];
    }
}
</code>
</pre>

My DynamicFormControlComponent - Implementation

<pre>
<code>

export class ServiceItemContactDFCControlModel extends DynamicFormValueControlModel<string> {
    
    @serializable() itemId:number;
    @serializable() requiredContactRoles:string[];
    
    @serializable() readonly type: string = DYNAMIC_FORM_CONTROL_TYPE_SVCITEMCONTACT;
     
    constructor(config: ServiceItemContactDFCControlModelConfig, layout?: DynamicFormControlLayout) {
        super(config, layout);
        this.itemId = config.itemId;
        this.requiredContactRoles = config.requiredContactRoles || [];

    }
   
}
</code>
</pre>

Component-Template for my DynamicFormControlComponent 

`<ng-container [formGroup]="group">{{ model | json}}<service-item-contacts [formControlName]="model.id"                            
                            [ngClass]="[getClass('element', 'control'), getClass('grid', 'control')]"
                            (blur)="onBlur($event)"
                            (change)="onChange($event)"
                            (focus)="onFocus($event)">
                            [itemId]="model.itemId"
                            [requiredContactRoles]="model.requiredContactRoles"></service-item-contacts> 
</ng-container>`

As you can see i am displaying the model in the component for debugging-purposes. The model has all properties it was configured with
<pre>
<code>
{
	"asyncValidators": null,
	"errorMessages": null,
	"hidden": false,
	"id": "itemContactRelation",
	"label": null,
	"labelTooltip": null,
	"controlTooltip": null,
	"layout": null,
	"name": "itemContactRelation",
	"relation": [],
	"updateOn": null,
	"validators": null,
	"disabled": false,
	"additional": null,
	"hint": null,
	"required": false,
	"tabIndex": null,
	"value": null,
	"type": "SVCITEMCONTACT",
	"itemId": 10230092,
	"requiredContactRoles": ["contactCommercial"]
}
</code>
</pre>

My Form-Control is rendered, but since all input-bindings are **undefined**, and the ngOnInit-Hook is not called, it is of no use.

I am lost here - it looks like there is something missing. But i don't know what ;-)

Best regards
Carsten

**Comment by Karamuto** [comment]
Hello @iceman91176 ,

I am a liitle at a loss here, as I can't see an ngOnInit hook anywhere in the code you mentioned and you also didn't show us the html template where you call you component.

Whats also missing is the part where you provide your new component to the library.

**Comment by iceman91176** [comment]
Hello @Karamuto,

thank you - i didn't include my custom-form-control for 2 reasons
1. it is working without dynamic-forms integration
2. i can't disclose parts of it. I'll see if i can strip out those parts

I added the HTML-Template above - here it is. Now nicely formatted ;-)
```
<ng-container [formGroup]="group">
{{ model | json}}
<service-item-contacts
 [formControlName]="model.id" 
 [ngClass]="[getClass('element', 'control'), getClass('grid', 'control')]"
 (blur)="onBlur($event)" 
 (change)="onChange($event)"
 (focus)="onFocus($event)"
 [itemId]="model.itemId"
 [requiredContactRoles]="model.requiredContactRoles">
</service-item-contacts
</ng-container>
```
And now i saw my mistake - i had a closing tag in my selector :-( I removed it and it works without problems.

Just for information - here is how the new control is provided

```
export const DFC_PROVIDER: Provider = {
  provide: DYNAMIC_FORM_CONTROL_MAP_FN,
  useValue: (model: DynamicFormControlModel): Type<DynamicFormControl> | null  => {

      switch (model.type) {
          
          case DYNAMIC_FORM_CONTROL_TYPE_ARRAY:
            return DynamicMaterialFormArrayComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_CHECKBOX:
            return DynamicMaterialCheckboxComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_CHECKBOX_GROUP:
            return DynamicMaterialFormGroupComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_DATEPICKER:
            return DynamicMaterialDatePickerComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_GROUP:
            return DynamicMaterialFormGroupComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_INPUT:
            let inputModel = model as DynamicInputModel;

            return inputModel.multiple ? DynamicMaterialChipsComponent : DynamicMaterialInputComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_RADIO_GROUP:
            return DynamicMaterialRadioGroupComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_SELECT:
            return DynamicMaterialSelectComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_SLIDER:
            return DynamicMaterialSliderComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_SWITCH:
            return DynamicMaterialSlideToggleComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_TEXTAREA:
            return DynamicMaterialTextAreaComponent;

        case DYNAMIC_FORM_CONTROL_TYPE_SVCITEMCONTACT:
          return ServiceItemContactDFCComponent;
          
        default:
            return null;

        }
     }
}
@NgModule({
    entryComponents: [ServiceItemContactDFCComponent],
    providers: [
        DFC_PROVIDER,.....
```

As you see, to use my custom component & the default components i shamelessly copied the mapping function.

**Comment by Karamuto** [comment]
@iceman91176,

I am glad you problem could be solved.
Is there any reason you repeated everything in your 'DYNAMIC_FORM_CONTROL_MAP_FN'?

As you only need to add/override the custom components here, there is no need to repeat the default components.
