### ISSUE TITLE
Relations across groups

### ISSUE THREAD

**Issue by alfonso-eusebio** [udos86/ng-dynamic-forms#912]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi,
As far as I can see, you can only create relations from one control to another within the same immediate group. This is becoming quite limiting in my case.
In the code in seems that the search for related controls is performed within the context of the current group.

Would it be possible to create relations across groups at present, somehow?
If not, any chance that the logic could be changed so that relation creation is triggered once the whole "tree" is built and all control IDs are available?

Thanks in advance.

**Comment by binshi50** [comment]
I have exactly the same issue. I've spent a lot of time to make the form completely configurable except for this limitation, and really don't want to give up. Any idea what's the chance the proposal will be accepted? And if it's accepted, what could be the timeline that it's implemented?  
Thanks A LOT.

**Comment by udos86** [comment]
@alfonso-eusebio @binshi50 

I'll try to make this work in `8.0.0` which will contain a major refactored version of related form control feature.
