### ISSUE TITLE
DynamicSelectModel - selected option

### ISSUE THREAD

**Issue by gitbankom** [udos86/ng-dynamic-forms#916]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[ * ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[* ] Prime NG
</code></pre>

## Description
Can you please give me an example how to set the selected (default) option in the <p-dropdown> component?
Which property defines the selected value? For example:
----------------------------------------------------------------------
 new DynamicSelectModel<string>({

                id: "roomSize",
                label: "Room Size",
                placeholder: "Room Size",
                options: [
                    {
                        label: "Single Room",
                        value: "1"
                    },
                    {
                        label: "Double Room",
                        value: "2"
                    },
                    {
                        label: "Business Suite",
                        value: "3"
                    },
                    {
                        label: "Presidential Suite",
                        value: "4"
                    },
                    {
                        label: "Storeroom",
                        value: "5"
                    }
                ]
}),
--------------------------------------------------------------------
How do i get the Double room (value:2) to be selected by default?

Thank you

**Comment by Karamuto** [comment]
Hello @gitbankom ,

the DynamicSelectModel has a property 'value'. If you want to preselect an option from you options, 'value' needs to have the same value, as the option you want to select.

In you example: if you want to select "Double Room", you need to have 'value: 2' in the select model.

Greetings

**Comment by SoulOnFire** [comment]
```typescript
// You can always set the selected option dynamically  if you needs too
set2Selected() {
      this.model.valueUpdates.next(2);
}
```
