### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by jmorenomarti** [udos86/ng-dynamic-forms#917]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[X] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.4.7`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi, we're using this fantastic library and we'd like to obtain [JSON Form Models](https://github.com/udos86/ng-dynamic-forms#json-form-models) from our backend.
The idea is to convert [FHIR Questionnaires](https://www.hl7.org/fhir/questionnaire.html) to JSON Form Models and return them to the frontend side so we can import and render them.

Do you have the **types definitions** for the JSON Form models?

We're using the 5.4.7 version, but logically it doesn't have to be those specific typings.

Thank you in advance!!!

Jesús

**Comment by Karamuto** [comment]
Hello @jmorenomarti ,

I don't think I really get you question, as JSON does not have typings, they got something called JSON Schema, but there are currently none for the library ( would be really complex ).

If you want to extract JSON's for the library I would suggest to build some examples which could render your questionaires and use the JSON.stringify(<yourModel>) to retrieve the corresponding JSON.

Greetings

**Comment by jmorenomarti** [comment]
Hello!
Thank you for your answer.
I'll try to explain...

For example, we have type definitions for FHIR JSON Objects: [@types/fhir](https://www.npmjs.com/package/@types/fhir) so, when you're typing in VSCode, you have the intellisense help available:

![image](https://user-images.githubusercontent.com/24249912/51606470-5526f680-1f12-11e9-8527-7e2120ba57bb.png)

So we need something similar for JSON Forms Models.

For example for this "input item":
```
{
        "type": "INPUT",
        "id": "sampleInput",
        "label": "Sample Input",
        "maxLength": 42,
        "placeholder": "Sample input"
}
```
we have this type definition:

**common-item.interface.ts**
```
export abstract class CommonItem {
    private type?: string;
    
    id: string;
    label: string;

    constructor(type: string) {
        this.type = type;
    }
}
```
**input-item.interface.ts**
```
import { CommonItem } from './common-item.interface';

export const DYNAMIC_FORM_CONTROL_TYPE_INPUT = 'INPUT';

export class InputItem extends CommonItem {

    constructor() {
        super(DYNAMIC_FORM_CONTROL_TYPE_INPUT);
    }
    value?: any;
    maxLength?: number;
    placeholder?: string;
}
```

Thank you!!!
Regards.

**Comment by jmorenomarti** [comment]
Thank you so much! I will try to use the model types you mentioned.

Regards!

**Comment by about-code** [comment]
Note that while JSON does not have a notion of explicit types, there are libraries like https://quicktype.io which are able to generate Typings from JSON sample data by infering the type from the sample values. E.g. from sample data like

```js
{
   "foo": "some text",
   "bar": 5
}
```
quicktype can infer a TypeScript interface

```ts
export interface YouNameIt {
   foo: string;
   bar: number;
}
```
when given a type name *YouNameIt*. You can try it directly using app.quicktype.io. Maybe this helps.
