### ISSUE TITLE
Angular 7 prod build, again customValidator is not provided via NG_VALIDATORS or NG_ASYNC_VALIDATORS  

### ISSUE THREAD

**Issue by rernens** [udos86/ng-dynamic-forms#918]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

CRITICAL ISSUE !

Angular 7.2.1

While this was properly working in Angular 6, after building an application for production with angular 7, ng-dynamic-forms no longer locates validators and async validators throwing the usual message

> validator "xxxx" is not provided via NG_VALIDATORS, NG_ASYNC_VALIDATORS or DYNAMIC_FORM_VALIDATORS

despite validators and async validators being provided as per documentation in the app.module

```
providers: [
    AppEntityServices,
    { provide: EntityServices, useExisting: AppEntityServices },
    { provide: APP_BASE_HREF,
      useValue: '/'
    },
    { provide: LocationStrategy,
      useClass: HashLocationStrategy
    },
    { provide: Languages,
      useValue: Config.GET_SUPPORTED_LANGUAGES()
    },
    { provide: DateAdapter,
      useClass: FrenchDateAdapter
    },
    ...VALIDATORS_PROVIDERS
  ],
```
where VALIDATORS_PROVIDERS comes from the following

```
// angular

import { NG_ASYNC_VALIDATORS, NG_VALIDATORS } from '@angular/forms';

// libs

import { DYNAMIC_VALIDATORS, Validator, ValidatorFactory } from '@ng-dynamic-forms/core';

// app

import {
  loginExists,
  sirenExists,
  sirenIsValid,
  siretExists,
  siretIsValid,
  tokenIsValid,
  userExists
} from './async.validators';
import {
  delegateExists,
  employeeExists,
  isCheckboxChecked,
  isStrongPswd,
  isValidFile,
  isValidNir,
  isValidPswd
} from './sync.validators';


export const VALIDATORS_PROVIDERS = [
  { provide: NG_ASYNC_VALIDATORS,
    useValue: loginExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: userExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: sirenExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: sirenIsValid,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: siretExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: siretIsValid,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: tokenIsValid,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidPswd,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isStrongPswd,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isCheckboxChecked,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidFile,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidNir,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: employeeExists,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: delegateExists,
    multi: true
  },
  { provide: DYNAMIC_VALIDATORS,
    useValue: new Map<string, Validator | ValidatorFactory>([
      ['loginExists', loginExists],
      ['userExists', userExists],
      ['sirenExists', sirenExists],
      ['sirenIsValid', sirenIsValid],
      ['siretExists', siretExists],
      ['siretIsValid', siretIsValid],
      ['tokenIsValid', tokenIsValid],
      ['isValidPswd', isValidPswd],
      ['isStrongPswd', isStrongPswd],
      ['isCheckboxChecked', isCheckboxChecked],
      ['isValidFile', isValidFile],
      ['isValidNir', isValidNir],
      ['employeeExists', employeeExists],
      ['delegateExists', delegateExists]
    ])
  }
];
```
and in models , reference to the validators is made as follow  

```
new DynamicInputModel({
        id: 'siren',
        inputType: 'text',
        mask: [ /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/, /\d/ ],
        autoComplete: AUTOCOMPLETE_OFF,
        placeholder: '?',
        hint: '?',
        validators: {
          required: null
        },
        asyncValidators: {
          sirenExists: {
            name: 'sirenExists',
            args: null
          },
          sirenIsValid: {
            name: 'sirenIsValid',
            args: null
          }
        },
        errorMessages: {
          required: '?',
          sirenExists: '?',
          sirenIsValid: '?'
        },
        updateOn: 'blur'
      }),
```

I tried to also include the providers in the lazy loaded modules but no luck.

Am I doing something wrong or has something changed  since Angular 7 that I am missing ?

Urgent help ( or fix ) welcome.

**Comment by rernens** [comment]
@udos86 

hi Udo,

Sorry to insist but this issue is blocking a deployment in production. 

Further investigation shows that the issue comes from DYNAMIC_VALIDATORS injection token that is unresolved (returning undefined) in DynamicFormValidationService when compiling in production.

Thanks for your help.

**Comment by udos86** [comment]
@rernens Hi!

Actually this should still work as designed. Nothing has changed here from Angular 6 to 7.

It's hard to tell from afar without having a live demo showing the exception.

Are you using `npm link` in your project environment?

**Comment by udos86** [comment]
@rernens 

Did you try to remove the extended validators notation and instead just using `validatorName: args`?

**Comment by rernens** [comment]
@udos86 

Hi Udo

Have a look at http://moncse.biz than click on the top right menu Deja Client ? Than when the login screen appears, click on Nouveau client ? At the bottom left of the logon screen.

The registration screen will fail to load properly due to the dynamic_validator token issue.

**Comment by rernens** [comment]
@udos86 

> Could you show how you are importing DynamicFormsCoreModule?i

import { DynamicFormsCoreModule } from '@ng-dynamic-forms/core';

In the root app.module

> Did you try to remove the extended validators notation and instead just using validatorName: args?

No, will try later tonight when back at home.

**Comment by rernens** [comment]
@udos86 

I found out that if I change the production configuration to optimization: false, it than works !

Hope it helps.

**Comment by udos86** [comment]
@rernens Thanks for providing that information.

Are you aware of what that optimization flag exactly does under the hood?

**Comment by rernens** [comment]
@udos86 

As far as I know, but I have not been able to find out more information on this, it is the tree-shaking process that removes unused code form the libraries that support it.

**Comment by udos86** [comment]
@rernens Thank you so far. I'll do some further investigation.

Unfortunately my internet connection is currently down and I am not capable of being online all the time.

**Comment by rernens** [comment]
@udos86 

Hi Udo

I can live with it for now with optimization disabled. It slows the initial load but remains acceptable at that stage.
 
When you have a chance could you have a look at my remarks on #903 and tell me what you think.

**Comment by guilhermehtk** [comment]
Taking advantage of the theme, I can not perform the injection of some custom validator if it is not in the app.module, is there any way to be able to perform this injection from other modules? This is the same case that was reported on this issue.

Sorry for my bad english.

**Comment by guilhermehtk** [comment]
Great, thanks for the explanation @rernens

**Comment by rernens** [comment]
@udos86 

hi Udo,

Any progress on this ? 

Size of the bundle starts to matter for my client as we move progressively the different components live. And without optimization, and though no tree-shaking, the size of the bundle almost double.

I have continued to make research on this matter and did not find on my side what was wrong with the injection token, being said that I am definitely not a specialist on those things.

**Comment by udos86** [comment]
@rernens 

The problem is I am not capable of reproducing this anymore neither with Angular CLI nor with manually using ngc. 

I'll do some further tests tonight.

Is there any chance you could provide a Stackblitz or something else extracting the problem?

**Comment by rernens** [comment]
@udos86 

You can use again http://www.moncse.biz, I deployed a version with optimization: true a minute ago.

I will build a new project and extract from the main one the registration process with the associated validators to see if I reproduce the problem on a project of a smaller size.

**Comment by rernens** [comment]
@udos86 

hi Udo,

Weird !!!  A reduced version of the application does not generate the issue. which means that there is something that interferes with your code.

I have generated an optimized version with sourcemap and debugging shows that when you invoke new InjectionToken, the injection token routine is called which returns the injection token.

In the case of the reduced application, the same line of code gets into the new InjectionToken routine and retrieves the content of the DYNAMIC_VALIDATORS token !!!

I have tried injecting the DYNAMIC_VALIDATORS token from various places to see if it would change something but no luck !

Then, I finally found what was the difference between the full application and the reduced application !!!

In the real application, I had defined all the validators providers in a const inside the index file where all the validators were defined as follow :

```
export const VALIDATORS_PROVIDERS = [
  { provide: NG_ASYNC_VALIDATORS,
    useValue: loginExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: userExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: sirenExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: sirenIsValid,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: siretExists,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: siretIsValid,
    multi: true
  },
  { provide: NG_ASYNC_VALIDATORS,
    useValue: tokenIsValid,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidPswd,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isStrongPswd,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isCheckboxChecked,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidFile,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidNir,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: employeeExists,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: delegateExists,
    multi: true
  },
  { provide: NG_VALIDATORS,
    useValue: isValidCreditCardNr,
    multi: true
  },
  { provide: DYNAMIC_VALIDATORS,
    useValue: new Map<string, Validator | ValidatorFactory>([
      [ 'loginExists', loginExists ],
      [ 'userExists', userExists ],
      [ 'sirenExists', sirenExists ],
      [ 'sirenIsValid', sirenIsValid ],
      [ 'siretExists', siretExists ],
      [ 'siretIsValid', siretIsValid ],
      [ 'tokenIsValid', tokenIsValid ],
      [ 'isValidPswd', isValidPswd ],
      [ 'isStrongPswd', isStrongPswd ],
      [ 'isCheckboxChecked', isCheckboxChecked ],
      [ 'isValidFile', isValidFile ],
      [ 'isValidNir', isValidNir ],
      [ 'employeeExists', employeeExists ],
      [ 'delegateExists', delegateExists ],
      [ 'isValidCreditCardNr', isValidCreditCardNr ]
    ])
  }
];
```
and within the app.module providers, I was including the validators in the following manner :

```
providers: [
    AppEntityServices,
    { provide: EntityServices, useExisting: AppEntityServices },
    { provide: APP_BASE_HREF, useValue: '/' },
    { provide: LocationStrategy, useClass: HashLocationStrategy },
    { provide: Languages, useValue: Config.GET_SUPPORTED_LANGUAGES() },
    { provide: LOCALE_ID, useValue: 'fr' },
    { provide: MAT_DATE_LOCALE, useValue: 'fr'},
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]},
    { provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: loginExists,
      multi: true
    },
    ...VALIDATORS_PROVIDERS,
    fakePaymentGatewayProvider
  ]

```

This works just fine without optimization. BUT IT DOES NOT WORK WITH OPTIMIZATION.

While NG_VALIDATORS and NG_ASYNC_VALIDATORS are recognized, DYNAMIC_VALIDATORS is not.

Il needs to be explicitely defined in the providers of the app module  to work as follow :

```
providers: [
    AppEntityServices,
    { provide: EntityServices, useExisting: AppEntityServices },
    { provide: APP_BASE_HREF, useValue: '/' },
    { provide: LocationStrategy, useClass: HashLocationStrategy },
    { provide: Languages, useValue: Config.GET_SUPPORTED_LANGUAGES() },
    { provide: LOCALE_ID, useValue: 'fr' },
    { provide: MAT_DATE_LOCALE, useValue: 'fr'},
    { provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]},
    { provide: MAT_DATE_FORMATS, useValue: MAT_MOMENT_DATE_FORMATS },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: loginExists,
      multi: true
    },
    /*
      embedding the validators providers with the following notation won't work
      DYNAMIC_VALIDATORS won't be recognized !
      need to be defined explicitely in app module providers
      weird !!!!

        ...VALIDATORS_PROVIDERS,

     */
    { provide: NG_ASYNC_VALIDATORS,
      useValue: loginExists,
      multi: true
    },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: userExists,
      multi: true
    },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: sirenExists,
      multi: true
    },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: sirenIsValid,
      multi: true
    },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: siretExists,
      multi: true
    },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: siretIsValid,
      multi: true
    },
    { provide: NG_ASYNC_VALIDATORS,
      useValue: tokenIsValid,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: isValidPswd,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: isStrongPswd,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: isCheckboxChecked,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: isValidFile,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: isValidNir,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: employeeExists,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: delegateExists,
      multi: true
    },
    { provide: NG_VALIDATORS,
      useValue: isValidCreditCardNr,
      multi: true
    },
    { provide: DYNAMIC_VALIDATORS,
      useValue: new Map<string, Validator | ValidatorFactory>([
        [ 'loginExists', loginExists ],
        [ 'userExists', userExists ],
        [ 'sirenExists', sirenExists ],
        [ 'sirenIsValid', sirenIsValid ],
        [ 'siretExists', siretExists ],
        [ 'siretIsValid', siretIsValid ],
        [ 'tokenIsValid', tokenIsValid ],
        [ 'isValidPswd', isValidPswd ],
        [ 'isStrongPswd', isStrongPswd ],
        [ 'isCheckboxChecked', isCheckboxChecked ],
        [ 'isValidFile', isValidFile ],
        [ 'isValidNir', isValidNir ],
        [ 'employeeExists', employeeExists ],
        [ 'delegateExists', delegateExists ],
        [ 'isValidCreditCardNr', isValidCreditCardNr ]
      ])
    },
    fakePaymentGatewayProvider
  ]
```

I wish I could understand why ! If anyone knows, I would like to understand.

**Comment by Karamuto** [comment]
Hello @rernens,

sorry if I reply lately here. Maybe you got an issue similiar to the one I had in the past.

Actually I needed to place the 'DYNAMIC_VALIDATORS' map into a const to work properly, like this:

```
export const validatorsMap: Map<string, Validator | ValidatorFactory> = new Map<string, Validator | ValidatorFactory>([
  ['backendValidator', backendValidator]
]);

...

providers: [
        {
          provide: NG_ASYNC_VALIDATORS,
          useValue: backendValidator,
          multi: true},
        {
          provide: DYNAMIC_VALIDATORS,
          useValue: validatorsMap
        },
        {
          provide: DynamicFormService,
          useClass: DynamicFormExtendedService
        }
]

```

As mentioned I don't know if the problem lies there, but I think I had problems in the past when the build optimizer was involved, that he needs the references to be constants or statics to work properly. (tree shaking?)

Greetings

**Comment by rernens** [comment]
@Karamuto 

Hi, I will give it a try and see if moving it back as it was implemented before, implementing your suggestion. I'll keep you posted.

**Comment by ironbirdie** [comment]
I'm trying to implement a similar case, but i can't get the async-validators to work, could u possibly give me an example of one? thx in advance
