### ISSUE TITLE
Sample Json 

### ISSUE THREAD

**Issue by elvispdosreis** [udos86/ng-dynamic-forms#919]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

could you please provide me with an example json of how to use the group and bootstrap grid

![din](https://user-images.githubusercontent.com/15267623/51800672-bce28780-2219-11e9-91ae-921cda199722.JPG)

it is possible to mount a component with append

```
<div class="input-group">
   <input type="text" class="form-control" aria-label="Text input with dropdown button">
   <div class="input-group-append">
      <select class="custom-select">
         <option selected>Choose...</option>
         <option value="1">One</option>
         <option value="2">Two</option>
          <option value="3">Three</option>
      </select>
     </div>
 </div>
```

**Comment by udos86** [comment]
Please have a look at the sample code. Everything should be in there...
