### ISSUE TITLE
DynamicPrimeNGCalendarComponent - NG Build prod fails with error Expected 2 arguments, but got 1

### ISSUE THREAD

**Issue by vinothsubramanian** [udos86/ng-dynamic-forms#921]
## I'm submitting a

<pre><code>
[ X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.0.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[X ] Prime NG
</code></pre>

## Description

NG Build for Prime NG fails with error on calendar component:
`ERROR in node_modules\@ng-dynamic-forms\ui-primeng\ui-primeng.d.ts.DynamicPrimeNGCalendarComponent.html(35,17): : Expected 2 arguments, but got 1.
node_modules\@ng-dynamic-forms\ui-primeng\ui-primeng.d.ts.DynamicPrimeNGCalendarComponent.html(15,17): : Expected 2 arguments, but got 1.
node_modules\@ng-dynamic-forms\ui-primeng\ui-primeng.d.ts.DynamicPrimeNGCalendarComponent.html(6,17): : Expected 2 arguments, but got 1.
node_modules\@ng-dynamic-forms\ui-primeng\ui-primeng.d.ts.DynamicPrimeNGCalendarComponent.html(7,17): : Expected 2 arguments, but got 1.`

**Comment by vinothsubramanian** [comment]
@udos86 I have created a pull request.  Could you please check it and merge if it is looking good to you.  We would like to have this fixed as soon as possible for our production build.

**Comment by flavglen** [comment]
> @udos86 I have created a pull request. Could you please check it and merge if it is looking good to you. We would like to have this fixed as soon as possible for our production build.

Awesome work Ram.

**Comment by udos86** [comment]
I'll deploy a patch tomorrow

**Comment by vinothsubramanian** [comment]
Thank you
