### ISSUE TITLE
DynamicTextAreaModel with 'minLength': 0 in "validators" still requires at least one character gets entered :: stackblitz link provided

### ISSUE THREAD

**Issue by fbayanati** [udos86/ng-dynamic-forms#925]
## I'm submitting a

<pre><code>
[X] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
DynamicTextAreaModel with 'minLength': 0 in "validators" still requires at least one character gets entered, please look into the [stackblitz](https://stackblitz.com/edit/angular-textarea-minlength0-validation).

`    const myTextArea = new DynamicTextAreaModel({
      id: "myTextArea",
      label: "My Textarea",
      validators: {
          "required": null,
          "minLength": 0
      }
    });`

It behaves like when you have the 'minLength': 1 for the DynamicTextAreaModel validators property.
To fix I totally dropped validators, but would be good if we could keep it and set it to 0 the min length validation was not necessary.

Please advise.

**Comment by Karamuto** [comment]
Hello @fbayanati ,

when you have minlength at 0 why even use the validator in the first place?

Seems like a similiar issue to this angular issue here: https://github.com/angular/angular/issues/23749

I think its a problem with the angular validator itself instead of dynamic forms

**Comment by udos86** [comment]
@Karamuto 

Thank you for helping out here! I also could not evaluate a legitimate bug here.
