### ISSUE TITLE
patchValue does not update DynamicNGBootstrapCheckboxComponent

### ISSUE THREAD

**Issue by monstrfolk** [udos86/ng-dynamic-forms#929]
## I'm submitting a
<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `7.0.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
patchValue does not update DynamicNGBootstrapCheckboxComponent model.value

**Comment by Karamuto** [comment]
Hello @monstrfolk ,

as mentioned by @rernens in #927 , using patchValue is not the recommended way to update the form controls. Use model.valueUpdates.next(<my-value>) instead.
