### ISSUE TITLE
ERROR Error: "There exists no control with id: myInput and/or index 0"

### ISSUE THREAD

**Issue by darrenmothersele** [udos86/ng-dynamic-forms#933]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

When using the [Form Arrays](https://github.com/udos86/ng-dynamic-forms#form-arrays) example from the documentation I get 

    ERROR Error: "There exists no control with id: myInput and/or index 0"

I've created a StackBlitz to demonstrate.

https://stackblitz.com/edit/angular-yssvbv

Click on the first "Remove Item" button (the item is removed).

Then click on the button which is now the first "Remove Item" button. Error is reported in console.

**Comment by guilhermehtk** [comment]
When the development branch will be merged friend @Karamuto?

**Comment by Karamuto** [comment]
Hello @guilhermehtk ,

the part is already merged but there wasn't released a new version yet. For this we have to wait for @udos86 .
