### ISSUE TITLE
insert new group to existed FormGroup

### ISSUE THREAD

**Issue by akeske** [udos86/ng-dynamic-forms#935]
## I'm submitting a

<pre><code>
[ x ] Bug / Regression
[ ] Feature Request / Proposal
[ x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Can I insert a DynamicFormGroupModel inside an existing  formgroup, like function insertFormGroupControl which inserts an array of DynamicFormControlModel[] into a formGroup.
I wrote something but obviously has this error 'Argument type DynamicFormGroupModel is not assignable to parameter type DynamicFormModel' but it can compile and works almost well until you hit two times the same button, it will stop update the json and I can not understand why.

[app.zip](https://github.com/udos86/ng-dynamic-forms/files/2897284/app.zip)

**Comment by Karamuto** [comment]
Hello @akeske ,

I have made a stackblitz from your example: https://stackblitz.com/edit/angular-yykzcx

Could you explain what is not working here exactly?

Greetings

**Comment by akeske** [comment]
Just push the "second button" multiple times you will see tha it will stop update the json

[code](https://stackblitz.com/edit/angular-kx1pbx)

**Comment by Karamuto** [comment]
If I remove you 'if' it suddenly works fine:

https://stackblitz.com/edit/angular-kx1pbx

You remove statement actually always cleans everything, so if you double press a button the group before is always removed and you can't see any difference.

**Comment by akeske** [comment]
Sorry, I don't get it which if do you remove?

**Comment by Karamuto** [comment]
You are doing this:

```
if (this.formModel.length > 1) {
      this.formService.removeFormGroupControl(
        1, this.formGroup, this.formModel
      );
    }
```

and as this condition is always true, you form group will always be cleaned out

**Comment by akeske** [comment]
I want to replace the existed form with the same one. This meaning I want ot remove the last inserted and insert it again. 

> second() {
    console.log(this.formModel.length);
    if (this.formModel.length === 2) {
      this.formService.removeFormGroupControl(
        1, this.formGroup, this.formModel
      );
    }
    setTimeout(() => {
      this.formService.insertFormGroupControl(
        1, this.formGroup, this.formModel, TEXT_FORM
      );
    }, 1);
  }

If I set timeout then it works fine but why?

[code](https://stackblitz.com/edit/angular-i1crkt?file=src/app/app.component.ts)

**Comment by Karamuto** [comment]
Ok I finally get what you mean :-)

As there are asynchronous processes working when you remove the the same form group first it seems there is not enough time before the new one is inserted ( even though its the same one )

Maybe you should just check if your form group is already in use in some way, a variable holding reference to the last inserted form for example. Like this you problem should also be solvable.

**Comment by akeske** [comment]
I 'm very happy :P 
 Do you have any example or somothing to find a way to solve it and post a soluion?

**Comment by akeske** [comment]
ok 
`if (this.formModel[1].id !== TEXT_FORM.id) {`
thanks for your help, maybe in the future I will use a variable
