### ISSUE TITLE
PrimeNG Group Sections

### ISSUE THREAD

**Issue by datajango** [udos86/ng-dynamic-forms#938]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ x] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x ] Prime NG
</code></pre>

## Description
I want to customize  ng-dynamic-forms/packages/ui-primeng/src/form-group/dynamic-primeng-form-group.component.html to add section headers for each group.   I made changes by adding the ui-primeng folder to my local project and changing the import statements in app.module.ts.  This approach worked but its not the best approach.  Is there a better way to customize ui-primeng controls?

**Comment by Karamuto** [comment]
Hello @datajango ,

this should be what you search for: https://github.com/udos86/ng-dynamic-forms#custom-form-controls

With this you can replace the default form-group with you custom form group.

Greetings
