### ISSUE TITLE
conditionally update form with new validators and error messages

### ISSUE THREAD

**Issue by bobingham** [udos86/ng-dynamic-forms#940]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `5.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[x ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Forgive my ignorance on this one, I am a relative newbie.
When the user saves the form I check some values and (if some condition) wish to return the user to the form with new validators and an error message displayed:
```
  handleCalmingDown() {
    let textModel = _.find(this.formModel, function (a) { return a.id == 'text' }) as DynamicTextAreaModel;
    textModel.validators = {
        value: "",
        required: null,
        minLength: 2
    }
    textModel.errorMessages = {
      required: "required."
    }
    textModel.valueUpdates.next();
  }
```
Is _valueUpdates()_ the correct method to use here?  Basically the user has made some selections which mean the text area input should be complete with at least two letters.  How do I update the form with the error message displayed?

**Comment by Karamuto** [comment]
Hello @bobingham ,

valueUpdates is a Subject which can update the related form control by the provided parameter.

Sadly you problem description is not clear enough for me to provide a solution.
