### ISSUE TITLE
support for ng-zorro-antd

### ISSUE THREAD

**Issue by Isaac-91** [udos86/ng-dynamic-forms#943]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ x ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

hi, i would like to know if there will be any support for ng-zorro-antd

**Comment by Karamuto** [comment]
Hello @itzhak91 ,

there is currently no support planned for ng-zorro antd. I think there is currently no one whth the free time to do so :/

**Comment by ddvkid** [comment]
@Karamuto @udos86 I can help with it if you guys welcome PRs :)

**Comment by Karamuto** [comment]
PR's are always welcome, they if they don't descrease the overall code coverage too much.

**Comment by udos86** [comment]
closed due to inactivity
