### ISSUE TITLE
p-dropdown PrimeNg no longer supports 'autoWidth'

### ISSUE THREAD

**Issue by jasperbosch** [udos86/ng-dynamic-forms#945]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x ] Prime NG
</code></pre>

## Description

Since v7.1.0 PrimeNg no longer supports 'autoWidth' on de p-dropdown element. See https://github.com/primefaces/primeng/issues/7337

This issue breaks the build.

**Comment by udos86** [comment]
@jasperbosch Thanks for reporting that!
