### ISSUE TITLE
How to create simple help or paragraph?

### ISSUE THREAD

**Issue by hervehobbes** [udos86/ng-dynamic-forms#950]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Hello,

First thank you for this excellent piece  of code.

In my forms I need to insert some help texts that can be created with simple paragraphs (with different colors), is there a way to do it?

For example after and before a group of fields, I need to put some texts to help the user to understand, so I don't need to insert some input fields in relations with this help texts.

**Comment by Karamuto** [comment]
Hello @hervehobbes ,

I hope I unserstood you correctly.

This should be what you are looking for: https://github.com/udos86/ng-dynamic-forms#custom-templates

**Comment by hervehobbes** [comment]
Hello,

Thank you for your answer, I saw it but I thought it was "really" when you want to use a new "design" for a form field (and optionally its label). If I can use it just for displaying text it will be ok.

Thanks again.

**Comment by Karamuto** [comment]
You can use to display anything you like in relation to a form control/and or group. Its just a way to insert static templates into the dynamic context.

**Comment by hervehobbes** [comment]
ok, I will use it, thanks a lot!

**Comment by Karamuto** [comment]
@hervehobbes ,

could your problem be resolved?

**Comment by hervehobbes** [comment]
Hello,

First thank you for the follow up.
In fact no.

I'm parsing an XML file and I convert its elements in something like your example:
https://github.com/udos86/ng-dynamic-forms/blob/master/sample/app/ui-material/material-sample-form.model.ts

But I don't understand how I will include, inside this array of objects my own elements, let say `HelpModel` or `TitleModel`.

These object will just need to display some html paragraphs of h1 to h6 titles.

I hope to be clear enough...

**Comment by Karamuto** [comment]
Hmm there is still a little information missing, would you be able to provide an example of the XML file you are parsing?

**Comment by hervehobbes** [comment]
Hello,

I'm not sure the XML will be of any help.

It is describing a form with several groups of fields, I have some` <group>`, `<field>` and `<option>` tags that I dynamically convert to a `DynamicFormModel` with `DynamicSelectModel`, `DynamicInputModel`, `DynamicFormGroupModel` etc , but inside this XML I also defined some other elements to the grammar to display text and titles **inside** the generated form.

So let say, I have some `<text>` and `<title>` tags inside my XML, what I want to do is to add them inside the generated form and html on the form of, for example `<p>text</p>` and `<h1>title</h1>`

Is that more clear?

bye

**Comment by Karamuto** [comment]
Ok, I think I understand now.

I think there are 2 ways you could accomplish this. 

1. The way I mentioned first with custom templates. You can accomplish this, by creating an array containing descriptions for the <ng-template [modelId]="id_of_related_control"></ng-template>, for which it should be rendered.

2. Create custom form controls like  mentioned here: https://github.com/udos86/ng-dynamic-forms#custom-form-controls, as your 'controls' are actually read only there would be no logic behind it.

**Comment by hervehobbes** [comment]
Thanks for the answer.
I understand the second method but not the first one.
For the first one, do I have to use a `DynamicFormArrayModel` ?

**Comment by hervehobbes** [comment]
Hello, 

Ignore my remark concerning `DynamicFormArrayModel `, my error was coming from the fact that your README.md is mentioning `ARRAY` in the example :

` <ng-template modelType="ARRAY">`

**Comment by hervehobbes** [comment]
Hello,

I finally opted for a custom form control, this example helped me a lot:
https://stackblitz.com/edit/angular-ng-dynamic-forms

Thank you for your help and for this library!

**Comment by Karamuto** [comment]
Ok the most important thing is that you could solve your problem.

glhf
