### ISSUE TITLE
Error message placeholder issue

### ISSUE THREAD

**Issue by seanbotha123** [udos86/ng-dynamic-forms#951]
## I'm submitting a
<pre><code>
[ x ] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `7.1.0`

[ x ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
When having a max value validator of `0` on a form control and specifying an errorMessage of `max: 'Must contain equal to or less than {{ max }} characters.'`

On the `dynamic-form-validation.service.ts` on method `parseErrorMessageConfig` the value would always return as `null`, because `0 === false`:

![image](https://user-images.githubusercontent.com/5496698/55614009-58e5bd80-578c-11e9-81ae-ac234455117c.png)

Expected error message is as follows: `Must contain equal to or less than 0 characters.`, but the generated error message is: `Must contain equal to or less than null characters.`

**Comment by Karamuto** [comment]
Merged it, thanks for you pull request!

**Comment by seanbotha123** [comment]
@Karamuto thanks! Do you have timelines on a new release?

**Comment by Karamuto** [comment]
Sadly no, as I have no direct way to contact @udos86  here.
