### ISSUE TITLE
angular-Build is failing

### ISSUE THREAD

**Issue by aaronbach** [udos86/ng-dynamic-forms#953]
## I'm submitting a

<pre><code>
[ x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `7.1.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

In Version `7.1.1` I get the following error during the build of my angular application:
```
WARNING in ./src/app/.../_.module.ngfactory.js
"export 'ɵa' (imported as 'i53') was not found in '@ng-dynamic-forms/core'
```

With Version `7.1.0` everything is working fine.

**Comment by Karamuto** [comment]
Hello @aaronbach ,

sadly this doesn't really explain your problem. I am using this version myself in a bigger project and does not encounter you issue.

Maybe you should state how you are using the library, maybe there is something else that is causing you issue.

**Comment by udos86** [comment]
@aaronbach Hi!

Could you please provide a sample project showing this behavior?

**Comment by coreuter** [comment]
Hi @udos86,

I ran into the same problem as @aaronbach after upgrading to `7.1.1.` While trying to create a sample project which shows the error I realized, that this error doesn’t occur in every project I use your library with.

I’ve created a lib in a @nrwl/nx workspace which imports @ng-dynamic-forms@7.1.1 -> everything is working fine and no errors are shown during build. 
As soon as I import my custom lib into another project of mine (which uses @ng-dynamic-forms@7.1.1, too), the error occurs. If I revert @ng-dynamic-forms to 7.1.0 in my project, everything works fine again.

It seems that `7.1.1` is not happy if both, the imported lib and the project, use @ng-dynamic-forms.

**Comment by aaronbach** [comment]
Hi @udos86,

I'm in the same situation like @coreuter. I'm using the angular Framework `mdbootstrap`. In Projects where I dont use this, I have no problems.

**Comment by udos86** [comment]
@aaronbach 

The project has now been switched to Angular CLI. I will release a new version within the next couple of days. Please report if this problem still occurs then.

**Comment by udos86** [comment]
Closed due to inactivity
