### ISSUE TITLE
Question: How to remove label from material form control container?

### ISSUE THREAD

**Issue by darrenmothersele** [udos86/ng-dynamic-forms#954]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `7.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

How do I override the logic in `hasMatFormField()` when using my own custom Material form control?

https://github.com/udos86/ng-dynamic-forms/blob/master/packages/ui-material/src/dynamic-material-form-control-container.component.ts#L84

I have implemented a custom Form Control and custom Form Control Model. 
But, because of the logic quoted above, I can't disable the label displayed via `DynamicMaterialFormControlContainerComponent`.

**Comment by Karamuto** [comment]
Hello @darrenmothersele,

as you can acually see inside there, you can see here:

```
return matFormFieldTypes.some(type => this.model.type === type) || (
            this.model instanceof DynamicFormValueControlModel &&
            this.model.getAdditional("isFormFieldControl")
        );
```

there is a "isFormFieldControl" property to use in this case, the only condition is that your form model extends the DynamicFormValueControlModel... why I actually used that one I don't know anymore I hope this does not make any problems

**Comment by udos86** [comment]
@Karamuto 

Thank you so much for your support and keeping this thing going here.

I'll try to deliver contributions on a regular basis again after being away for some private reasons...

**Comment by Karamuto** [comment]
Hello @udos86 ,

glad to see you back. Its no problem, I can't spare too much of my freetime either.
