### ISSUE TITLE
Support HTML content in material component labels

### ISSUE THREAD

**Issue by Ventzy** [udos86/ng-dynamic-forms#966]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[x] Feature Request / Proposal
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `7.0.4`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Label in material components does not support HTML. 

For example _dynamic-material-input.component.html_
```
    <ng-container *ngIf="model.label" ngProjectAs="mat-label">
        <mat-label>{{ model.label }}</mat-label>
    </ng-container>
```

Simply changing to `<mat-label [innerHTML]="model.label"></mat-label>` as done long ago for regular labels (https://github.com/udos86/ng-dynamic-forms/issues/157) should do the trick.

**Comment by udos86** [comment]
@Ventzy Hi!

This will be part of the next major version.
