### ISSUE TITLE
New relations documentation not correct

### ISSUE THREAD

**Issue by CAlex-Wilson** [udos86/ng-dynamic-forms#976]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `8.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I upgraded to the latest version to get access to the new Match system for related controls but I was having trouble getting it to work.

Per the documentation I converted my relation DynamicTextAreaModel to this:

```
new DynamicTextAreaModel(
    {
        id: "myTextArea",
        label: "My Textarea",
        relations: [
            {
                match: MATCH_HIDDEN,
                when: [
                    { id: "mySelect", value: "option-3" }
                ]
            }
        ]
    }
```

This does not work. The documentation should be this:

```
new DynamicTextAreaModel(
    {
        id: "myTextArea",
        label: "My Textarea",
        relations: [
            {
                match: HiddenMatcher.match,
                when: [
                    { id: "mySelect", value: "option-3" }
                ]
            }
        ]
    }
```
match: MATCH_HIDDEN **--- should be --->** match: HiddenMatcher.match
I was about to post this as a bug, but I can see that it may just be an error in the docs.

**Comment by udos86** [comment]
@CAlex-Wilson 

I can't see any mistakes here. It works as documented in the [sample application](https://github.com/udos86/ng-dynamic-forms/blob/master/src/app/ui-bootstrap/bootstrap-sample-form.model.ts#L163).

**Comment by Karamuto** [comment]
Can't see any mistakes here either. Working stackblitz here:

https://stackblitz.com/edit/angular-g26yv9

**Comment by stevehoper** [comment]
@Karamuto 
Is the relation function actually working now or need other dependencies?
https://stackblitz.com/edit/angular-g26yv9
Tried both sample form data and link above, nothing shows/hides on select.

**Comment by jfcere** [comment]
@Karamuto is it just me or your stackblitz is not working (at least in Chrome)?

**Comment by stevehoper** [comment]
@jfcere stackblitz example is not working, you may want to clone the sample project and run it in your local.

**Comment by jfcere** [comment]
@stevehoper nope, not working ... I've opened a new issue with reproduction example: https://github.com/udos86/ng-dynamic-forms/issues/1002
