### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError. Button disabled when formGroup is invalid

### ISSUE THREAD

**Issue by Londeren** [udos86/ng-dynamic-forms#978]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><button type="submit" [disabled]="formGroup.invalid">Save</button><code>
NG Dynamic Forms Version: `7.2.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I'm trying to disable submit button when form is invalid. In dev mode I've got an error `Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'disabled: false'. Current value: 'disabled: true'.`

**Comment by Karamuto** [comment]
Hello @Londeren ,

could you provide a minimum example or better a stackblitz which includes the error? This way its easier to solve your problem.

**Comment by Londeren** [comment]
Hi! I think this is [the bug in angular](https://github.com/angular/angular/issues/23657) and [this one](https://github.com/angular/angular/issues/18004)

**Comment by tonyshare** [comment]
in my solution use ngif to disable it before it init

**Comment by tonyshare** [comment]
@Londeren it is not a bug of angular, it is a mechanism of angular. In my situation, just look the code below:

`new DynamicInputModel({
      id: 'mobile',
      label: 'phone',
      required: true,
      maxLength: 18,
      minLength: 7,
      pattern: '^\\d+$',
      errorMessages: {
        required: '{{label}}is needed',
        maxLength: '{{label}}must shorter than 18 letters',
        minLength: '{{label}}must longer than 7 letters',
        pattern: '{{label}}只能是英文字母和数字',
      },
      value: '1234567',`
the next steps is my test of the  `ExpressionChangedAfterItHasBeenCheckedError` :
vale sets                                                                        result
the `value` is empty                                            error occur
the `value`  less than 7 letters                         error occur 
the `value`  more than 18 letter                       error occur 
the `value`  between 7-18                                error disappear
remove `required` key                                       error disappear

i am also test the only one validation rule with `required` key, if you set the  `value`  key empty, the error will occur,  if you set the  `value`  key not empty, the error will disappear.

i guess the it is the bug of ng-dynamic-forms, it did not set the value in the correct life cycle.

my solution is give the form some value that needs the validation. and patch the value in the `AfterViewInit` life cycle, look at the following codes:
` ngAfterViewInit(): void {
    timer(0).subscribe(
      () => this.onClear(),
    );
  }`

look at  the code, i am using the rxjs `timer`  observable and give it a value of zero. it is very strange that if i use the `of(null)`, the error will occur, but i am using a timer even give it a value **zero**  the error will disappear, i did not know why. hope it is helpful for you.

**Comment by Karamuto** [comment]
Hello again,

yeah as @Londeren has already figured out, this actually an angular 'feature' to show an error if one changes values outside of the angular lifecycle. By angular logic, its not ok to change value expression after ngOnInit but before ngAfterViewInit. I also ran bunches of time into this. But there actually exists some more or less dirty "workarounds".

1. use a timeout like @Londeren  has done it, observable timer(0) or setTimeOut( () => {} ), actually result in the same: we get something asyn to the current process. This works ~ 50% the time.

2. use the 'ChangeDetectorRef' by injecting the service. Then call 'markForCheck' or 'detectChanges' afterwards, so angular knows you want to recheck the current state.

3. use the 'ngZone' also by injecting the service. with ngZone.run( () => {} ) you can are actually allowed to bypass the check of angular and are able to change you values freely. But beware, as you also need explicitly now need to call 'detectChanges' for angular to update you view.

These are more less my experiences in this issue.

**Comment by Londeren** [comment]
@Karamuto I didn't use timeouts :) I used `*ngIf=true`

**Comment by Karamuto** [comment]
Ups I used your name instead of @tonyshare, sorry for this. :)
