### ISSUE TITLE
validator "existingNameValidator" is not provided via NG_VALIDATORS, NG_ASYNC_VALIDATORS or DYNAMIC_FORM_VALIDATORS

### ISSUE THREAD

**Issue by tonyshare** [udos86/ng-dynamic-forms#981]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Help
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `8.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I am using ng-dynamic-forms to create a async validate form to check whether the username existing
**async validator function:**

`

export function existingNameValidator(userService: UserService): AsyncValidatorFn {
  return (control: AbstractControl) => {
    return userService.checkUserProperty({username: control.value}).pipe(
      map(res => res['valid'] ? null : {nameTaken: true}),
    );
  };
}
`

**create form model**

`createFormModel(): DynamicFormModel {

    return [
      new DynamicInputModel({
        id: 'username',
        label: '用户名',
        asyncValidators: {
          existingNameValidator: null,
        },
      }),
      new DynamicInputModel({
        id: 'password',
        label: '密码',
      }),
      new DynamicInputModel({
        id: 'name',
        label: '姓名',
      }),
      new DynamicInputModel({
        id: 'mobile',
        label: '电话',
      }),
      new DynamicInputModel({
        id: 'type',
        label: '类别',
      }),
      new DynamicInputModel({
        id: 'email',
        label: '邮箱',
      }),
    ];
  }
`

**app module porvider**

`providers: [

    {
      provide: NG_ASYNC_VALIDATORS,
      useValue: existingNameValidator,
      multi: true,
    },
    {
      provide: DYNAMIC_VALIDATORS,
      useValue: new Map<string, Validators | ValidatorFactory>([
          ['existingNameValidator', existingNameValidator],
      ]),
    },
  ],

providers in app.module`

when i run the app i got the following errors:

_AddComponent_Host.ngfactory.js? [sm]:1 ERROR Error: validator "existingNameValidator" is not provided via NG_VALIDATORS, NG_ASYNC_VALIDATORS or DYNAMIC_FORM_VALIDATORS
    at DynamicFormValidationService.push../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormValidationService.getValidatorFn (core.js:3352)
    at core.js:3389
    at Array.map (<anonymous>)
    at DynamicFormValidationService.push../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormValidationService.getValidatorFns (core.js:3377)
    at DynamicFormValidationService.push../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormValidationService.getAsyncValidators (core.js:3476)
    at DynamicFormService.push../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormService.createAbstractControlOptions (core.js:3625)
    at core.js:3694
    at Array.forEach (<anonymous>)
    at DynamicFormService.push../node_modules/@ng-dynamic-forms/core/fesm5/core.js.DynamicFormService.createFormGroup (core.js:3670)_

i struggled for some times and get nothing. any suggestions please?

``

**Comment by Karamuto** [comment]
Hello @tonyshare,

I tried your code in a stackblitz and resulted in this: https://stackblitz.com/edit/angular-1zsqzm

The problem "my" example here has is that factory support is not really given in any way. The ValidationService seems to always expect a normal ValidationFn or AsynacValidationsFn to be returned ( which can't be true for a factory )

@udo I think there is a bug here which should be resolved.
Maybe we also need something like the 'deps' array used in angulars factory providers to resolve the required parameters.

**Comment by tonyshare** [comment]
thanks for your answer , i solve the problem by imports the FormModule into the app module. and then  i got following errors:



## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Help
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `8.0.1`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

I am using ng-dynamic-forms to create a async validate form to check whether the username existing
**async validator function:**

`

export function existingNameValidator(userService: UserService): AsyncValidatorFn {
  return (control: AbstractControl) => {
    return userService.checkUserProperty({username: control.value}).pipe(
      map(res => res['valid'] ? null : {nameTaken: true}),
    );
  };
}
`

**create form model**

`createFormModel(): DynamicFormModel {

    return [
      new DynamicInputModel({
        id: 'username',
        label: '用户名',
        asyncValidators: {
          existingNameValidator: null,
        },
      }),
      new DynamicInputModel({
        id: 'password',
        label: '密码',
      }),
      new DynamicInputModel({
        id: 'name',
        label: '姓名',
      }),
      new DynamicInputModel({
        id: 'mobile',
        label: '电话',
      }),
      new DynamicInputModel({
        id: 'type',
        label: '类别',
      }),
      new DynamicInputModel({
        id: 'email',
        label: '邮箱',
      }),
    ];
  }
`

**app module porvider**

`providers: [

    {
      provide: NG_ASYNC_VALIDATORS,
      useValue: existingNameValidator,
      multi: true,
    },
    {
      provide: DYNAMIC_VALIDATORS,
      useValue: new Map<string, Validators | ValidatorFactory>([
          ['existingNameValidator', existingNameValidator],
      ]),
    },
  ],

providers in app.module`

when i run the app i got the following errors:

AddComponent_Host.ngfactory.js? [sm]:1 ERROR Error: Expected validator to return Promise or Observable.
    at toObservable (forms.js:653)
    at Array.map (<anonymous>)
    at FormControl.asyncValidator (forms.js:641)
    at FormControl.push../node_modules/@angular/forms/fesm5/forms.js.AbstractControl._runAsyncValidator (forms.js:2920)
    at FormControl.push../node_modules/@angular/forms/fesm5/forms.js.AbstractControl.updateValueAndValidity (forms.js:2893)
    at FormControl.push../node_modules/@angular/forms/fesm5/forms.js.AbstractControl.enable (forms.js:2855)
    at FormControl.push../node_modules/@angular/forms/fesm5/forms.js.FormControl._applyFormState (forms.js:3373)
    at new FormControl (forms.js:3239)
    at core.js:3695
    at Array.forEach (<anonymous>)

**Comment by tonyshare** [comment]
i found the problem is that  it needs to pass the userService to the async validator existingNameValidator , but where and  how to pass it ?

**Comment by Karamuto** [comment]
Thats exactly what I meantioned before. There is currently no way to provide the Service for a validator. But i had used a 'workaround' in my application by injecting the service into the component renderering the form and use it there. But this can't be a perfect solution on the long run.

**Comment by tonyshare** [comment]
I want to save some time for using dynamic form, it is failed! but  i learned some. thanks for @Karamuto for your kind answer.

**Comment by tonyshare** [comment]
@Karamuto i have solved the problem by using formControl's **setAsyncValitaor** function, that is:
formGroup.get('control id').setAsyncValidators(asyncValidatorCreator(asyncValidatorService));
thus we pass the service to async validator successfully, hope it is helpful.

**Comment by Karamuto** [comment]
Hello @tonyshare ,

good to hear that you could resolve your problem, but I think its still a bug and you method is more like a workaround. So I will reopen the issue.

**Comment by udos86** [comment]
@tonyshare 

You can make this work without any workaround, you just missed out to pass the `userService` as value to your `existingNameValidator` in your model:

```
  new DynamicInputModel({
    id: 'username',
    label: '用户名',
    asyncValidators: {
      existingNameValidator: userService,
    },
  }),
```

@Karamuto  I'm aware that the current API might not be very convenient but I cannot classify this as a bug as you can make it work out-of-the-box.

**Comment by tonyshare** [comment]
thanks a lot @udos86 it works, but i have another question about how can i pass one more parameter to the validator? the usage scenarios is that  i want to check the unique validation for two or three field, so i need to pass the field control to  async validator, thus i can bind  multiple field's values to check.

**Comment by udos86** [comment]
@tonyshare You're welcome!

> the usage scenarios is that i want to check the unique validation for two or three fields, so i need to pass the field control to async validator, thus i can bind multiple field's values to check.

You'd either pass an array (existingNameValidator: [userService, ...], ) or use a form group validator.

**Comment by tonyshare** [comment]
thanks @udos86
