### ISSUE TITLE
Support SurveyJS?

### ISSUE THREAD

**Issue by patran** [udos86/ng-dynamic-forms#984]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `8.0.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

https://surveyjs.io/

It would be cool if ng-dynamics-forms could support the surveyjs.io data structure. Any thoughts on a strategy to implement?

**Comment by udos86** [comment]
@patran Hi!

Sorry, at the moment there are no plans to extend the project in this direction.
