### ISSUE TITLE
Add support for custom material admin templates

### ISSUE THREAD

**Issue by patran** [udos86/ng-dynamic-forms#986]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[X] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Is there a guide to add support for custom admin templates such as the one below?  We like to integrate ng-dynamic forms with the look'n feel and components provided by various admin templates. Thank-you!

https://wrappixel.com/demos/angular-admin-templates/material-angular/landingpage/index.html

**Comment by udos86** [comment]
@patran Hi!

Thank your for your interest in using the library.

If you'd like to add support for a special UI library you would have to create a custom UI package for NG Dynamic Forms. 

However from what I've seen from the docs this could actually work out of the box as Material Pro seems to be using the default Material components. 

Maybe just give it a try?
