### ISSUE TITLE
PrimeNG spinners do not work unless a min/max value is specified

### ISSUE THREAD

**Issue by nbjohan** [udos86/ng-dynamic-forms#989]
## I'm submitting a
<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `8.1.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x] Prime NG
</code></pre>

## Description

**Current behaviour:**
PrimeNG spinners do not increase/decrease the value of the input if the min/max values are not specified.

**Expected behaviour:**
The spinner should increase/decrease the value even in no min/max parameter is specified.

**Cause:**
The spin function of the spinner component explicitly checks for 'undefined'. See https://github.com/primefaces/primeng/blob/master/src/app/components/spinner/spinner.ts#L161

The dynamic-primeng-spinner.component.html passes null if the min/max is not specified.
See https://github.com/udos86/ng-dynamic-forms/blob/3bb75f8f9e4dbc78ec8e0aab5f48f99ff5adcade/projects/ng-dynamic-forms/ui-primeng/src/lib/spinner/dynamic-primeng-spinner.component.html#L6

**Solution:**
I think this can be fixed by checking the parameters in the template: `dynamic-primeng-spinner.component.html`

```
[min]="model.min === null ? undefined : model.min"
[max]="model.max === null ? undefined : model.max"
```

Its also possible to change the null fallback in `DynamicInputModel`, but that will affect other components aswel, which may cause similar sideeffects as wel.

If you think this is the correct solution, I can provide a PR.

**Comment by udos86** [comment]
@nbjohan Thanks for reporting this!

> If you think this is the correct solution, I can provide a PR.

It is the correct solution. I you'd like to provide a PR please remember to add your code on the `development` branch (see [CONTRIBUTING.md](https://github.com/udos86/ng-dynamic-forms/blob/master/CONTRIBUTING.md)). 

Thanks!
