### ISSUE TITLE
Problem with relation in checkboxGroup

### ISSUE THREAD

**Issue by stevehoper** [udos86/ng-dynamic-forms#990]
## I'm submitting a

<pre><code>
[x ] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Relations condition id was not found when used in checkboxGroup with the following error msg. 
Error msg: No related form control with id undefined could be found.
Am I using the wrong syntax to use "when" in textInput relations if "rootPath" is mapping to DynamicCheckboxGroupModel? How to identify the DynamicCheckboxModel in DynamicInputModel relations condition?

Thanks.

formModel:
new DynamicCheckboxGroupModel({

                id: "bsCheckboxGroup",
                label: "Checkbox Group",
                group: [
                    new DynamicCheckboxModel({

                        id: "checkboxGroup1",
                        label: "Checkbox 1",
                        value: true
                    }),
                    new DynamicCheckboxModel({

                        id: "checkboxGroup2",
                        label: "Checkbox 2",
                        value: true
                    })
                ]
            }),

            new DynamicInputModel({
                hint: "Just a sample help text",
                id: "bsInput12",
                label: "Input",
                maxLength: 51,
                placeholder: "example input",
                relations: [
                    {
                        match: MATCH_DISABLED,
                        when: [{rootPath: "bsCheckboxGroup.checkboxGroup1", value: true}]
                    },
                    {
                        match: MATCH_HIDDEN,
                        when: [{rootPath: "bsCheckboxGroup.checkboxGroup2", value: true}]
                    },

                ],
            })

formGroup value:
bsFormGroup1:
bsCheckboxGroup:
checkboxGroup1: true
checkboxGroup2: true
__proto__: Object
bsDatePicker: Fri Jul 26 2019 11:19:14 GMT-0400
bsInput: null
bsInput12: null
bsSelect: "option-3"

**Comment by udos86** [comment]
@stevehoper Hi!

You actually would have to use the fully qualified path: 

`rootPath: "bsFormGroup1.bsCheckboxGroup.checkboxGroup1"`

However there is a bug preventing this from working when you are referencing more than one form controls via `rootPath`. This will be fixed with the next patch version.
